### PR TITLE
Test Bench Works with Repeated Column Names

### LINKED ISSUE #755: TestBench breaks with repeated column names
**Describe the bug**
When the name for different input/output columns is set to be the same, the generate data function counts them as one column (taking the last one I think) due to the way the data is stored in an object. 

**To Reproduce**
1. Go to https://circuitverse.org/testbench
2. Add some input and output columns
3. Rename some of the columns to be the same
4. "Click GenerateData and Copy to Clipboard"
5. See Error

**Expected behavior**
Should have a seperate input/output array for each column in the test data generated.

**Screenshots**
image

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #755 

#### Describe the changes you have made in this pr -
I had to completely rewrite the `generateTestData()` function. The result is still the exact same, but now, users can have repeated column names! The data format has remained the same. Additionally, the test bench will load in the data.

### CODE REVIEW

**Comment by NumberC** [comment]
@tachyons I was wondering if this could be merged. If not, what should I fix?

**Comment by NumberC** [comment]
@tachyons Can you check this PR? If not, do you know who can approve or merge it?

**Comment by NumberC** [comment]
@tachyons why can't this be merged?

**Comment by tachyons** [comment]
Because this pr pending review from @satu0king

**Comment by NumberC** [comment]
@satu0king Can you check this PR?

**Comment by satu0king** [comment]
@NumberC , The testbench is going to be completely rewritten as part of GSoC (potential project). If you are interested, consider applying to the same.

**Pull request closed without merging**
