### PR TITLE
Removing Invalid Emails using Devise Regular Expressions

### LINKED ISSUE #505: Invalid emails being allowed in 'add collaborator'
**Is your feature request related to a problem? Please describe.**
I tried to add invalid email and it showed it was valid.
Email that I added was test@rosy
**Describe the solution you'd like**
Invalid emails should get removed.

**Additional context**
Screenshot attached.
invalid

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #505 

#### Describe the changes you have made in this pr - 
I have updated the Utils.rb file to match the regular expression from the devise.rb file to remove invalid emails.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Change the title of the PR to something meaningful and also the commit message.

**Comment by Shivansh2407** [comment]
@Ananthavijay Done 👍

**Comment by Shivansh2407** [comment]
Please review and merge @Ananthavijay , @tachyons .

**Comment by Shivansh2407** [comment]
Thank you @tachyons Sir

**Pull request merged**
