### PR TITLE
Finalise Edit Group Name page

### PR DESCRIPTION
**Pull request by aayush-05**
image
image
image
image

Note: This has been done on top of #1443

### CODE REVIEW

**Comment by aayush-05** [comment]
@tachyons @nitin10s please have a look at this

**Comment by aayush-05** [comment]
Update: Some stuff was breaking on extra-small displays; fixed now.
image

**Comment by aayush-05** [comment]
@nitin10s please review this one

**Comment by nitin10s** [comment]
Add autofocus please

**Comment by aayush-05** [comment]
It will be done via #1461, both of these pages are using the same form.

**Comment by satu0king** [comment]
LGTM. But why are there changes in all files when only Group Page got edited?

**Comment by aayush-05** [comment]
Because the base branch on which this PR has been done is actually another PR to this repo (#1443). So the changes shown are actually cummulative for both PRs (say #1443 and #1456)

**Comment by tachyons** [comment]
Why error message says 0 error ?

**Comment by aayush-05** [comment]
I manually typed it in HTML to show how an error message would look, since couldn't produce one from backend :p

**Pull request merged**
