### PR TITLE
conditionally show Insert SubCircuit and Open Project button

### LINKED ISSUE #914: Insert subcircuit button still visible even if there are no subcircuits
**Describe the bug**
A clear and concise description of what the bug is: When there are no SubCircuits there shouldn't be a button to _Add SubCircuit_ as it may be confusing to first time users.

Similiar behaviour is observed when trying to open offline projects. 

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Click on Circuit -> Insert Subcircuit
3. See error

**Expected behavior**
If there are no subcircuits or offline projects, no button indicating _Insert SubCircuit_ or _Open Project_ should be visible respectively. 

**Screenshots**
Screenshot from 2020-02-19 19-56-48
Screenshot from 2020-02-19 19-47-27

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 18.04

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Nitish145**
Conditionally show **Insert SubCircuit** and **Open Project** button in jquery dialog

Fixes #914 

#### Describe the changes you have made in this pr -
-> Added conditional logic to show/disable the above mentioned dialog buttons

### Screenshots of the changes (If any) -
Screenshot from 2020-02-19 23-29-13
Screenshot from 2020-02-19 23-29-08

### CODE REVIEW

**Comment by Nitish145** [comment]
@tachyons please review and merge

**Comment by Nitish145** [comment]
@satu0king reviews please

**Comment by Nitish145** [comment]
@satu0king is this a valid enhancement or should i let it go?

**Comment by Nitish145** [comment]
@sato0king please have a look at this..

**Comment by satu0king** [comment]
image
image

Its not coming for me correctly

**Comment by satu0king** [comment]
Resolved by #1283

**Pull request closed without merging**
