### PR TITLE
Update PR and Issue templates

### LINKED ISSUE #461: Improve PULL_REQUEST.md template
**Is your feature request related to a problem? Please describe.**
Currently, the PR template is very basic and has only 2 sections.
**Describe the solution you'd like**
More sections can be added. Consult this : [1](https://github.com/perry-contribs/concerto/blob/master/.github/pull_request_template.md) [2](https://github.com/adobe/aio-cli-plugin-cna/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Describe alternatives you've considered**

**Additional context**
Intended to be worked under GCI'19. Refer [this](https://github.com/CircuitVerse/Interactive-Book/issues/5) issue too 

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by yummypasta**
Fixes #461 

#### Describe the changes you have made in this PR -
Slightly changed wording of Bug Report template, added more sections and guidelines to the PR template

### CODE REVIEW

**Comment by aayush-05** [comment]
We can even have a dedicated section for screenshots in the bug template @sakshi1499

**Comment by sakshi1499** [comment]
Yes, that would be great @aayush-05

**Comment by yummypasta** [comment]
@aayush-05 Yep, the template already has a screenshots section, it's just not shown in the diff

**Comment by sakshi1499** [comment]
@namantechlabs Can you push your changes here? It would be so much better to have things in one place.

**Comment by sakshi1499** [comment]
@yummypasta naman and you are working together for the new changes in PR template so I'll suggest if you both target different areas. I have seen your PR and I have suggested naman to make changes accordingly. For any further changes please see once that there are no duplicates. I'll distribute if there are any changes between you two accordingly. Thanks

**Comment by aayush-05** [comment]
@tachyons please review this. The template task got two instances. So @yummypasta made some initial changes in the template and we asked the second student to make the rest of the changes above this pr.
Since this is not the final version, this isn't the one getting merged; so should I approve this and we can see the merging part in the pr by the second student.

**Comment by aayush-05** [comment]
@yummypasta have a look here. You reverting the commit, closed this pr without it getting merged.

**Comment by yummypasta** [comment]
@aayush-05 Sorry. I didn't think I would need feature branches at the time and I put everything on master. New PR is #791

**Pull request closed without merging**
