### PR TITLE
Updated pull request & issue templates. 

### PR DESCRIPTION
**Pull request by namantechlabs**
Updated pull request template according to Issue  #461 for GCI :)

### CODE REVIEW

**Comment by namantechlabs** [comment]
@aayush-05, Please have a look.

**Comment by aayush-05** [comment]
There's a repetitive section for "Describe the changes this PR makes"; let us just have the first one for the bug description only.

image

**Comment by sakshi1499** [comment]
@namantechlabs please update as aayush mentioned

**Comment by namantechlabs** [comment]
@aayush-05 @sakshi1499 I have updated the file, Please review. Thanks.

**Comment by sakshi1499** [comment]
Hi naman, I doubt you have changed as we mentioned. Please see yummypasta's PR once. We want you to not have those changes in this PR. Please only keep the add ons that you have made after his changes. Okay? @namantechlabs

**Comment by namantechlabs** [comment]
Hi @sakshi1499, I don't understand. The files are same as his, but I have changed the languages at different places to make it sound better. Could you please be specific as what changes have not been done? Regards.

**Comment by sakshi1499** [comment]
Hey naman what I meant was that the some of the changes you have made are great and nicely done, however some changes are exactly same like I think the one in attach a screenshot. So I am saying please make sure that there are no sentences that are as it is. We want to different PRs to be merged having two separate changes. Okay? Thanks :)

**Comment by namantechlabs** [comment]
Okay, I get it now. Will do the same. Thanks.

**Comment by namantechlabs** [comment]
Hi @sakshi1499 @aayush-05, I have made the changes as required, please have a look. Thanks.

**Comment by sakshi1499** [comment]
naman
   

Here in the above screenshot, the change you have made is at all required.


yummy

Yummypasta has already mentioned about the description of bug and he has intentionally removed the particular line you added again. Naman we are not looking forward to remove and the same content again and again. Please look for some valid changes and make sure that they are totally different than his PR. @namantechlabs

**Comment by namantechlabs** [comment]
Hi @sakshi1499, I have reverted back the changes and have also added another question, "Is this the first time you are experiencing this issue?". Kindly have a look. Thanks.

**Pull request closed without merging**
