### PR TITLE
Add new footer for the new UI

### PR DESCRIPTION
**Pull request by mohit-003**
New footer is added for the new UI

### Screenshots of the changes (If any) -
image
### For 576px< screen-size <768px
image
### For mobile view:
image

### CODE REVIEW

**Comment by Ananthavijay** [comment]
will it be good to move the social icons to the footer instead of the navbar, like "Connect with us: "? whatsay?

**Comment by Ananthavijay** [comment]
And what about copyright statement in the footer?

**Comment by nitin10s** [comment]
Yes! forgot about the social icons. We should add them in the footer and remove them from Navbar. I'll send the design on Slack. About copyright, let's wait because I am not sure what statement to put in exactly.

**Comment by nitin10s** [comment]
I see there were a few problems with the placement of social icons on lg screens.

**Comment by mohit-003** [comment]
I'll fix it now

**Comment by nitin10s** [comment]
@tachyons Merge this with the new commit. I've checked.

**Comment by nitin10s** [comment]
@tachyons I checked the new commit. The issue is fixed.

**Pull request merged**
