### PR TITLE
Added option to directly edit the project title from header in Simulator

### LINKED ISSUE #1808: Add feature to directly edit the project title
**Is your feature request related to a problem? Please describe.**
Right now, a prompt opens up asking for the title, we can improve this experience if we could directly edit the project title by clicking on it.

**Describe the solution you'd like**
Edit the project title by directly clicking on the title, it can be implemented by using an input tag in place of the span tag 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes #1808 

#### Describe the changes you have made in this PR -
1. Made header project title editable from the header itself.
2. Linked Header project title and sidebar project title so that the one changes itself automatically when there is any change in another.

### Screenshots of the changes (If any) -
**Initial State**
image

**On hover and click**
image

**Automatic sync when one of the 'projects title' input changes**
image

### CODE REVIEW

**Comment by abstrekt** [comment]
Should have made changes on `/new_UI` branch @dipanshparmar

**Comment by dipanshparmar** [comment]
> Should have made changes on `/new_UI` branch @dipanshparmar

@abstrekt Okay! closing this PR then

**Comment by dipanshparmar** [comment]
@abstrekt should I also push the changes to the new_UI branch or the master branch?

**Comment by abstrekt** [comment]
> 
> 
> @abstrekt should I also push the changes to the new_UI branch or the master branch?

Anything related to the simulator should be pushed to the new_UI, for the rest you can target master

**Comment by dipanshparmar** [comment]
> > @abstrekt should I also push the changes to the new_UI branch or the master branch?
> 
> Anything related to the simulator should be pushed to the new_UI, for the rest you can target master

Thanks for the information :smile:

**Pull request closed without merging**
