### PR TITLE
Fixed the Navbar in Mobile View

### PR DESCRIPTION
**Pull request by devartstar**
Initially, the Navbar on expanding was getting hidden behind the widgets so in order to avoid that I implemented the widgets to move down as the navbar expands.

Screenshots of the changes -
Navbar Close -
NavbarClose
Navbar Open -
NavbarOpen

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by ShreyaPrasad1209** [comment]
@devartstar can you add a screenshot of the navbar in open state after your fix?

**Comment by devartstar** [comment]
@ShreyaPrasad1209  Yes Sure ... I have already uploaded the screenshot of the navbar in the open and closed state above ... but I am uploading it again.
Screenshot (630)

**Comment by devartstar** [comment]
@ShreyaPrasad1209 can you please further check if my code requires any further modifications or if it's good for merging.

**Comment by devartstar** [comment]
The issue related to this PR is - #2108 
https://github.com/CircuitVerse/CircuitVerse/issues/2108

**Comment by ShreyaPrasad1209** [comment]
@devartstar there are some merge conflicts, please resolve them so that I can approve your PR

**Comment by devartstar** [comment]
> 
> 
> @devartstar there are some merge conflicts, please resolve them so that I can approve your PR

Is there any way to know why is there conflicts in those files ... is it because when i made the PR it was according to the latest code at that time and some other PR's has been approved till now to the code-base has changed.

**Pull request closed without merging**
