### PR TITLE
Added Color Property

### LINKED ISSUE #49: Color setting for 7-segment displays
The 7-segment and hex displays are lacking a color setting, which would be great to have. The variable LED is also lacking a color setting.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #49 

#### Describe the changes you have made in this PR -
I have Added Color Property to VariableLed, HexDisplay, SevenSegDisplay and SixteenSegDisplay.
 
### Screenshots of the changes (If any) -
Patch41

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
Please review @satu0king 👍

**Comment by yash15601** [comment]
@Shivansh2407  fix code climate issues

**Comment by Shivansh2407** [comment]
@yash15601 actually all the issues are related to code refactoring which is a task to be done during GSoC under Project 2. @satu0king please let me know your views on this 👍

**Comment by shubhankarsharma00** [comment]
@Shivansh2407 I think I might be missing something obvious here but the color does not change. Can you help me find the code responsible for redrawing the LED with changed color?

**Comment by abstrekt** [comment]
ummm...

**Comment by abstrekt** [comment]
update?

**Comment by satu0king** [comment]
@Shivansh2407 , as others pointed out the colors don't actually change just be setting `this.actualColor`, you will need to make changes to the draw logic as well.

**Comment by Shivansh2407** [comment]
Sure, I am working on this and will come up with a fix soon.

**Comment by satu0king** [comment]
Closing this PR as this is for old user interface. Thanks!

**Pull request closed without merging**
