### PR TITLE
download as svg

### PR DESCRIPTION
**Pull request by abstrekt**
#### Describe the changes you have made in this PR -
added `canvas2svg` module as a dependency.

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by satu0king** [comment]
@abstrekt I think you did npm install instead of yarn install. There should be only yarn.lock, not package.lock

**Comment by abstrekt** [comment]
> 
> 
> @abstrekt I think you did npm install instead of yarn install. There should be only yarn.lock, not package.lock

yes I kindof forget that, fixed now!

**Comment by abstrekt** [comment]
fixed it @satu0king

**Comment by abstrekt** [comment]
somethings wrong pls hold on

**Comment by abstrekt** [comment]
Okay 👍👍

**Pull request merged**
