### PR TITLE
safe html now loaded

### LINKED ISSUE #277: safe html for description on tags page
**Describe the bug**
when the html is not plain the whole html of project description is rendered

**To Reproduce**
1. Go [here](https://circuitverse.org/projects/tags/test)

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #277 

#### Describe the changes you have made in this pr -
now loads safe html

### CODE REVIEW

**Comment by shubhankarsharma00** [comment]
@satu0king @tachyons please review it.

**Comment by tachyons** [comment]
Can you check if description is rendered correctly ?

**Comment by shubhankarsharma00** [comment]
@tachyons yeah it rendered correctly
tags page:
image
show html:
image

**Comment by tachyons** [comment]
Thanks

**Pull request merged**
