### PR TITLE
Added Font Awesome Icons

### LINKED ISSUE #1041: Can't see icons while editing layout.  [new UX]
**Describe the bug**
glyphicons not working in `simulator\embed.html.erb`  and  `simulator\edit.html.erb`. 

**To Reproduce**
1. Go to 'localhost/3000'
2. Try edit layout option or look for this:

image

**Expected behavior**
this is not visible:
image 
these icons not visible:
image 
also the icons used in `embed.html.erb` not visible

**Desktop (please complete the following information):**

**Additional context**
I think importing glyphicons will work. 

**Are you working on this issue? (Yes/No)**
No.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1041 

#### Describe the changes you have made in this PR -
I have added Font Awesome Icons instead of Glyphicons. Now they are working in the simulator.
 
### Screenshots of the changes (If any) -
Capture
Capture1

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@tachyons amd @nitin10s review this please 👍

**Comment by Shivansh2407** [comment]
I was thinking to add Tooltip to the Icons. I would like to hear your views on this @tachyons and @nitin10s .

**Comment by satu0king** [comment]
> I was thinking to add Tooltip to the Icons. I would like to hear your views on this @tachyons and @nitin10s .

Yes please add a tool tip but do that in a separate PR.

**Comment by Shivansh2407** [comment]
> > I was thinking to add Tooltip to the Icons. I would like to hear your views on this @tachyons and @nitin10s .
> 
> Yes please add a tool tip but do that in a separate PR.

Ok @satu0king will Open a PR soon. Please review this and merge 👍 .

**Pull request closed without merging**
