### PR TITLE
Fix Login/SignUp pages - New UI

### PR DESCRIPTION
**Pull request by aayush-05**
Made Login/SignUp pages responsive and more true to the prototypes.
**Screenshots**
1. Login Page
image
--------------------------------------------------------------------------------------------------------------
2. SignUp Page
image
--------------------------------------------------------------------------------------------------------------
3. Forgot Password Page
image

_(Could get the screenshot for Edit Password Page because mail service doesn't work on local server)_

### CODE REVIEW

**Comment by aayush-05** [comment]
@tachyons am I supposed to use 1 space for identation. Currently using 2 spaces and still hound is showing identation error ?

**Comment by tachyons** [comment]
It says you used tabs instead of spaces

**Comment by Ananthavijay** [comment]
should we have ````Confirm Password```` field in the Signup page?

**Comment by aayush-05** [comment]
> It says you used tabs instead of spaces

Exactly, I don't know why it is showing so, I manually typed in two spaces to avoid it, but still no use. Try selecting the indented part, you will see there's only two characters space.

**Comment by aayush-05** [comment]
Done @tachyons , it can be merged now.

**Comment by tachyons** [comment]
`(Could get the screenshot for Edit Password Page because mail service doesn't work on local server)`

It does

**Comment by aayush-05** [comment]
I was getting this error while sending the email :
image
I even tried changing the localhost url port to 3000 in environments/development (since my server is running on that post rather than 8080), but still the same error.
Is there something I am doing wrong @tachyons ?

**Comment by tachyons** [comment]
https://mailcatcher.me/

**Comment by aayush-05** [comment]
It worked ! But I have to reinstall mailcatcher to make it run, I saw it is there in the gemfile. But the official website recommends not putting it there, and installing it separately by whoever wants to work with mails (not sure about it).
image

Shall I make a note in readme and remove it from gemfile @tachyons ?

**Comment by tachyons** [comment]
Sure

**Pull request merged**
