### PR TITLE
Refactor JS and CSS of simulator (Fixes #824)

### LINKED ISSUE #824: Simulator Code Problems
**Describe the bug**
Currently the simulator page page uses the application layout which contains lots of changes which the simulator page does not require. There are also style issues in the simulator in the master branch

**Solution**
- Create base stylesheet for simulator layout
- Create base javascript for simulator layout
- Fix style overriding issues in master branch

**Other Information**
Created as a GCI task by @Abhiram-vv, @vishnu-v-v, @tachyons & Alan Joseph

### PR DESCRIPTION
**Pull request by JoshHeng**
Fixes #824 

JS and CSS have been moved to a minimal amount of base files, without uneeded code from the application layout.
The code has also been moved to the assets directory and pipeline.
Some styling issues have also been fixed.

### CODE REVIEW

**Comment by JoshHeng** [comment]
CircleCI seems to be failing because I have refactored lots of lines or there is another error on their side. There's nothing we can now do with Hound.

**Comment by tachyons** [comment]
Awesome work, build is failing because assets location is now updated, https://github.com/CircuitVerse/CircuitVerse/blob/b3efdfe25528883208f120f742d6b8099e4f4a08/app/views/assignments/_form.html.erb#L1 for instance loading css won't work without stylesheet link tag if we move assets from public to app/assets

**Comment by JoshHeng** [comment]
> 
> 
> Awesome work, build is failing because assets location is now updated,
> 
> https://github.com/CircuitVerse/CircuitVerse/blob/b3efdfe25528883208f120f742d6b8099e4f4a08/app/views/assignments/_form.html.erb#L1
> for instance loading css won't work without stylesheet link tag if we move assets from public to app/assets

@tachyons Fixed

**Comment by tachyons** [comment]
Please resolve conflicts

**Comment by JoshHeng** [comment]
> Please resolve conflicts

Conflicting changes merged

**Comment by tachyons** [comment]
CI is failing

**Comment by JoshHeng** [comment]
> CI is failing

`rspec ./spec/system/assignment_spec.rb:14 # Assignments when user is mentor should create assignment`
`rspec ./spec/system/assignment_spec.rb:31 # Assignments when user is mentor should be able to edit assignment`

I am unable to determine the exact problem with my code

**Comment by tachyons** [comment]
Try running that spec in local machine and see what happens

**Comment by Ananthavijay** [comment]
I found the reason why the tests are failing.
These are failing after merging this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/837).
As you can see there is no CSS for the class ````trumbowyg-editor````. According to the  test, capybara should fill the description in the class ````trumbowyg-editor```` but as there is no css for the class it is returning the error.

**Comment by JoshHeng** [comment]
> 
> 
> I think this reason why the tests are failing.
> Tests are failing after merging this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/837).
> As you can see there is no CSS for the class `trumbowyg-editor`. According to the test, capybara should fill the description in the class `trumbowyg-editor` but as there is no css for the class it is returning the error. But i dont understand how this test is passing in all other recent PR's.

All the CSS changes in that PR seem to have automatically been updated in this PR during the merge. I cannot see anything involving CSS that is different.

**Comment by Ananthavijay** [comment]
I am actually saying that even in that PR there is no CSS.

**Comment by satu0king** [comment]
Will merge #826. This PR takes a step forward and puts everything in the asset pipeline. However, this has conflict and will definitely conflict with other pending PRs.

**Comment by satu0king** [comment]
Closing this PR due to heavy conflict.

**Pull request closed without merging**
