### PR TITLE
wire node overlapped on circuit elements is now extendible

### LINKED ISSUE #856: Cable Node above elements cannot be moved
**Describe the bug**
When a cable node is placed above any element attempt to move the node results in moving the element

**Expected behaviour**
When the node selection mark appears, the element selection mark should not be visible and moving should result in moving the node 

ezgif-2-9ff3623a3335

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by jha11aditya**
Fixes #856

#### Describe the changes you have made in this pr -
I put condition that the node can be extended if it is hovered upon.
And a CircuitElement can be dragged if it was last selected otherwise it was also being dragged when the wire node was being extended.

### CODE REVIEW

**Comment by Shweta0002** [comment]
@tachyons , It can be merged !! It's working fine for me.

> Fixes #856
> 
> #### Describe the changes you have made in this pr -
> I put condition that the node can be extended if it is hovered upon.
> And a CircuitElement can be dragged if it was last selected otherwise it was also being dragged when the wire node was being extended.
>

**Comment by jha11aditya** [comment]
@MrBartusek Could you please post a gif of both elements moving. Because I didn't encounter that.

**Comment by MrBartusek** [comment]
@jha11aditya I just checked it and for some reason, it is working now, probably I broke something. One slight fix I would implement is a disabling element highlight when a node is highlighted. Awesome work 🚀 

image

**Comment by satu0king** [comment]
Good Attempt, Looks like it might work, on hold for now as this apparently insignificant change can have lasting consequences.

**Comment by satu0king** [comment]
@mahmodHammad can u review this?

**Comment by mahmodHammad** [comment]
@ i will 👍

**Comment by mahmodHammad** [comment]
Awesome work, i believe it should work.
@satu0king this can get merged

**Pull request closed without merging**
