### PR TITLE
fix(typo-email): typo in email fix

### LINKED ISSUE #3968: [TYPO]: In the add mentors in my groups instead of "email ID" it should be "email" only
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the add mentors in my groups instead of "email ID" it should be "email" only

### Steps To Reproduce

1.go to dropdown  near your profile in the navbar
2.click my groups
3.create a group
3.in add mentor you came to see the typo

### Expected Behavior

"email" should be there instead of "email ID"

### Screenshots

Screenshot (221)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #3968 

#### Describe the changes you have made in this PR -
I fix the typo and change to "email " instead of email ids
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by VaibhavUpreti — CHANGES_REQUESTED** [review]
Could you fix this for other locales too? I can see this mistake in [hindi](https://github.com/CircuitVerse/CircuitVerse/blob/d0c2bd61fbe4d4f53a80dab6b6c50c505ae24f3b/config/locales/views/groups/hi.yml#L3C167-L3C171) as well.

**Comment by harshsharma-11** [comment]
sure @VaibhavUpreti sir please merge this one ,and i will try for hindi

**Comment by vedant-jain03** [comment]
> sure @VaibhavUpreti sir please merge this one ,and i will try for hindi

You can commit in this PR

**Comment by harshsharma-11** [comment]
> > sure @VaibhavUpreti sir please merge this one ,and i will try for hindi
> 
> You can commit in this PR

okk

**Comment by harshsharma-11** [comment]
> 



> > sure @VaibhavUpreti sir please merge this one ,and i will try for hindi
> 
> You can commit in this PR
@vedant-jain03 sir please merge this one it will be my first pr that get merged .I will create anothere pr for hindi as well,  it will
motivates me
i hope you understand sir please !!!!!!!!!!!!!!!!!

**Comment by harshsharma-11** [comment]
@vedant-jain03 sir please merge this one it will be my first pr that get merged .I will create anothere pr for hindi as well,  it will
motivates me
i hope you understand sir please !!!!!!!!!!!!!!!!!

**Comment by VaibhavUpreti** [comment]
> @vedant-jain03 sir please merge this one it will be my first pr that get merged .I will create anothere pr for hindi as well, it will motivates me i hope you understand sir please !!!!!!!!!!!!!!!!!

No need to split it, you can commit it here only.

**Comment by harshsharma-11** [comment]
@VaibhavUpreti i made pr for hindi as well please check

**Pull request closed without merging**
