### PR TITLE
Fixed the more button in my Favourites page

### LINKED ISSUE #1573: My favourites page's More button has a bug
**Describe the bug**
My favourites page's More button has a bug

**To Reproduce**
1. Go to 'My Favourites'
2. Click on 'More' of any circuit that is not created by you
3. See error

**Expected behavior**
The author's circuit page should open.

**Screenshots**
favo

**Additional context**

**Are you working on this issue? (Yes/No)**
I would like to. Can anyone tell me if I am correct, but I think this [ line ](https://github.com/CircuitVerse/CircuitVerse/blob/aee080ea19615612ca8fc98a5c8d8e0deaab5d07/app/views/users/logix/favourites.html.erb#L39)should be linked to `<%= user_project_url(project.author, project) %>` instead. Want reviews. I can't seem to able to login using Gitpod's Workspace

### PR DESCRIPTION
**Pull request by nileshdas**
Fixes #1573

#### Describe the changes you have made in this PR -
Changed the URL for more button in the favourites page
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by nitin10s** [comment]
@aayush-05

**Comment by aayush-05** [comment]
No need to change path to url

**Comment by nileshdas** [comment]
@aayush-05 Changed it.

**Comment by nitin10s** [comment]
Thanks for your contribution! 😄

**Pull request merged**
