### PR TITLE
GCI: 2019 - Find and Fix Typos

### PR DESCRIPTION
**Pull request by prakhargurunani**
GCI username: Kingpin
Task: Find and Fix Typos
Task Type: Documentation / Training
Mentors: Sakshi Munjal

Please review my work.

### CODE REVIEW

**Comment by prakhargurunani** [comment]
I have updated the PULL_REQUEST_TEMPLATE.md. It had a typo error.

**Comment by prakhargurunani** [comment]
There were no changes in the documentation.

**Comment by sakshi1499** [comment]
@prakhargurunani you aren't supposed to make a PR directly. You have to first claim a task on the dashboard and then submit a PR. Have you claimed this task?

**Comment by prakhargurunani** [comment]
@ankitkataria please merge

**Pull request merged**
