### PR TITLE
Make urls more friendly using friendly ids

### PR DESCRIPTION
**Pull request by tachyons**
This is to make urls more friendly to read

Previous
`users/165/projects/65675`
New
`users/165/projects/flip-flop`

This feature is backward compatible and all the previous urls work as before

### CODE REVIEW

**Comment by satu0king** [comment]
Looks great! But what happens if there are duplicate names? We need to test the backward compatibility part before deploying.

**Comment by tachyons** [comment]
It will append unique postfix to fix duplication, fixed all the backward compatibility issues I could find, you can check beta.circuitverse.org

**Comment by satu0king** [comment]
What happens when the circuit name is changed?

**Comment by tachyons** [comment]
We aren't updating slug when the circuit name changes, but we can add that behaviour by just adding one line to the code, previous urls still work for the backward compatbility

**Comment by tachyons** [comment]
https://stackoverflow.com/a/17765270

**Pull request merged**
