### PR TITLE
test: tests added for LMS Integration - GSoC'21 - Ayan Biswas

### PR DESCRIPTION
**Pull request by ayan-biswas0412**
#### Describe the changes you have made in this PR -
Tests added to check that CircuitVerse as an LTI Provider is working successfully
### Screenshots of the changes (If any) -
image

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@Commit-Lint review

**Comment by ayan-biswas0412** [comment]
@Commit-Lint review

**Comment by ayan-biswas0412** [comment]
@Commit-Lint review

**Comment by ayan-biswas0412** [comment]
Can you please see and merge if the test cases are sufficient @tachyons @Shivansh2407

**Review by tachyons — APPROVED** [review]

**Review by Shivansh2407 — APPROVED** [review]
LGTM :tada:

**Pull request merged**
