### PR TITLE
Added tooltip on hover

### LINKED ISSUE #590: Small size and overflowing text of circuit elements in Simulator.
**Describe the bug**
The circuit elements are very small sized and text is overflowing in some of them too.Without zooming its pretty hard to read.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'simulator'
3. See the circuit elements on the right.

**Expected behavior**
The circuit elements must be big enough to be visible clearly and text overflow must be fixed too

**Screenshots**
IMG_20191109_145054
IMG_20191109_145126

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: Brave
 - Version : 0.70.123 

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by KaustubhDamania**
Fixes #590 

#### Describe the changes you have made in this PR -
Added tooltip on hover on each element

### Screenshots of the changes (If any) -

Before - 

Screenshot from 2020-03-20 20-01-49

After - 

Screenshot from 2020-03-20 20-01-34

### CODE REVIEW

**Comment by KaustubhDamania** [comment]
@nitin10s can you review this please?

**Comment by KaustubhDamania** [comment]
@nitin10s Cool, I'll try that :+1:

**Comment by KaustubhDamania** [comment]
@nitin10s here's the screenshot with downward tooltip.

Screenshot from 2020-03-21 16-50-59

However I'm facing an issue when the element is the bottommost, the tooltip is overlapping with the bottom menu items. I tried to fix using z-index but it didn't work, hence I had kept the tooltip at the center of the element. 

Screenshot from 2020-03-21 16-51-39

**Comment by satu0king** [comment]
I think we can close this PR as the current version seems to be alright.

**Comment by aayush-05** [comment]
@tachyons can we close this

**Comment by KaustubhDamania** [comment]
> @tachyons can we close this

@aayush-05 yes, I had asked on community channel on Slack that which one looks better, the current one or the one which I made. I didn't get any response on that, still I can improvise this PR if required.

**Comment by satu0king** [comment]
We are going to revamp the simulator, so this will be implemented based on that design.

**Pull request closed without merging**
