### PR TITLE
Added Bit converter

### PR DESCRIPTION
**Pull request by ryuk156**
#### Describe the changes you have made in this PR -
Added js script for bit coverter which convert bcd to dec, hex to dec, dec to bcd ,dec to hex, hex to bcd etc i give a try to implement it with modal will fix issues related to it soon  
### Screenshots of the changes (If any) -
image

image

### CODE REVIEW

**Comment by yash15601** [comment]
@satu0king  Review please will fix this issues soon

**Comment by yash15601** [comment]
@Shivansh2407 Good idea will try for this i m still working in this😊

**Comment by satu0king** [comment]
> @Shivansh2407 Good idea will try for this i m still working in this😊

Please add a WIP tag to your PR

**Comment by satu0king** [comment]
I reviewed the functionality, works great. Some suggestions
1. Instead of "convert to", automatically display both the values.
1. Don't name it as bit convertor - name it as "hex - decimal - binary calculator"
1. Can you make it possible to edit the circuit with the window open, ideally window shouldn't take so much space
1. You can make it smaller by having a drop down "hex", "decimal", "binary" 

I am imaginign something like this 

[hex] [a]

Decimal  - 10
Binary - 1010

[hex] -> Drop down 
[ef01] -> user input

**Comment by yash15601** [comment]
@satu0king  will try for this things you said

**Comment by satu0king** [comment]
@Shivansh2407 @ryuk156 anyone working on this?

**Comment by ryuk156** [comment]
For now I'm not working on this @Shivansh2407  if you want you can 😅

**Comment by ryuk156** [comment]
@Shivansh2407  are you working on this

**Comment by Shivansh2407** [comment]
No. I did not started my work on this Issue. I thought you were working on it. I would like to work on it👍

**Comment by ryuk156** [comment]
Can I make pr I'm working  on this @Shivansh2407  if you don't  mind

**Comment by Shivansh2407** [comment]
@ryuk156 this is your PR only. Go ahead and make changes to this PR.

**Comment by ryuk156** [comment]
Okay😇

**Pull request closed without merging**
