### PR TITLE
Generate truthtable for the circuit and export (#604 #514)

### LINKED ISSUE #604: There should be a Generate Truth Table From Circuit feature.
**Is your feature request related to a problem? Please describe.**

There should be a Generate Truth Table From Circuit feature. This would help in better understanding of the circuit. 

**Are you working on this? (Yes/No)**
No.

### PR DESCRIPTION
**Pull request by gkan30**
Fixes #604  #514 

#### Describe the changes you have made in this pr -
The tools menu now has a new tool feature to it - "Generate Truth Table"
The tool generates a truth table for the circuit in the scope, i.e; the current circuit
It then provides you a option to download the truth table, which then outputs a CSV file.
The tool can be viewed in action below

### Screenshots of the new feature -
GIF of the basic workflow
TruthTableDemoFinal

**Example** : No Inputs are given, so truth table cannot be generated. Hence it shows this.
Screenshot_3

**Example** : I did not label the output node, so it shows as **NL** (short for **Not Labelled**).
Screenshot_1

**Example** : With subcircuit module
Screenshot_2

### Conclusion
The truth table is a very important and powerful tool for representation and analysis of any logic circuit. I believe that this tool will be of great help to many judging by the fact that there were many issues published.Thus, this feature should be added.
If you find any bugs, discrepancies or any other problems or suggestions , feel free to convey it to me.
Cheers!

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@gkan30 I have fixed the downloading Issue in #895 and also No inputs given issue in #931 . Feel free to suggest changes in those PRs if you want. I would request you to close this to remove duplicates 👍 .

**Comment by gkan30** [comment]
@Shivansh2407 This PR targets the generation of the truth table from the circuit.
The issues you have specified do not deal with this in any fashion and should be considered as a entirely different issue.
In the issue that you specified, you export the truth table of combinational analysis.
This issue generates a truth table from the circuit and gives you an option to download it
I dont think it is a duplicate.

**Comment by gkan30** [comment]
@satu0king @tachyons please review this. It can be rather useful feature once implemented

**Comment by gkan30** [comment]
@satu0king @tachyons can you guys help me resolve codeclimate issues?

**Comment by satu0king** [comment]
We have an option to save as PDF now, not sure we need this feature.

**Comment by gkan30** [comment]
> We have an option to save as PDF now, not sure we need this feature.

@satu0king 
The export is not the main feature.
The main feature is creating a truth table for the circuit I designed in the simulator.
Like if I created a complex circuit , there will be a truth table generated for that particular circuit.
I have explained in great detail in the GIF.
Please go through it once. Getting a truth table for the circuit we designed seems crucial feature for analysis.

**Pull request closed without merging**
