### PR TITLE
X scroll#956

### PR DESCRIPTION
**Pull request by dkapur17**
Fixes #

Fixed the unwanted x-scroll and added a little distance between the CircuitVerse logo in the footer and "Follow us on" text.

#### Describe the changes you have made in this pr -

Changed the padding and margin bootstrap classes as required.

### Screenshots of the changes (If any) -

X-Scroll Fixed

### CODE REVIEW

**Comment by dkapur17** [comment]
@tachyons and @ankitkataria please review this 👍

**Comment by tachyons** [comment]
Add before and after screenshots

**Comment by dkapur17** [comment]
### Before
* No space between the CircuitVerse Logo and "Follow us on:" in the footer.
* Some extra whitespace of the right side causing there to be an unwanted horizontal scrollbar

X-Scroll-Issue

### After
* Added some space between the CircuitVerse Logo and "Follow us on:" in the footer.
* Removed the extra whitespace on the right side, so no more horizontal scrollbar.

X-Scroll-Fixed

**Comment by tachyons** [comment]
Handled in another PR

**Pull request closed without merging**
