### PR TITLE
Added option to search for projects in the dashboard

### LINKED ISSUE #1806: Add a search bar in the user's dashboard
**Is your feature request related to a problem? Please describe.**
Right now, the user's dashboard doesn't have any option to search for a particular project (circuits).

**Describe the solution you'd like**
A search bar will improve the user's experience as they will be able to search for the required project easily.

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes #1806 

#### Describe the changes you have made in this PR -
1. Added search bar in the dashboard so that the user can search for the projects easily
2. Implemented fusejs to achieve fuzzy searching.

### Screenshots of the changes (If any) -
**Before**
image

**After**
image

**On Search**
image

**Note:** Right now the threshold for fuzzy search is the default (0.6). If any changes are needed in the threshold, then please let me know.
image

### CODE REVIEW

**Comment by dipanshparmar** [comment]
@satu0king please have a look at this new PR.

**Comment by satu0king** [comment]
Merged in #1926

**Comment by satu0king** [comment]
@dipanshparmar, oh you raised a new PR just now, I was working on the same as well. Can you check if you have added improvements to my PR, then we can integrate both of them. Sorry for that.

**Comment by dipanshparmar** [comment]
@satu0king No problem! I don't think so my PR has any improvements over yours as we both worked on fusejs.io with default options.

**Comment by satu0king** [comment]
> @satu0king No problem! I don't think so my PR has any improvements over yours as we both worked on fusejs.io with default options.

Ah okay. I checked once, I don't think you sorted the results as per fuse.js ranking. Without sorting, the results will not be good. Check my PR as to how I did that.

**Comment by satu0king** [comment]
Also I got slightly confused because you closed the previous PR and opened this new one. Avoid doing that, it is almost always better to update an existing PR instead of closing/opening a new PR.

**Comment by dipanshparmar** [comment]
> > @satu0king No problem! I don't think so my PR has any improvements over yours as we both worked on fusejs.io with default options.
> 
> Ah okay. I checked once, I don't think you sorted the results as per fuse.js ranking. Without sorting, the results will not be good. Check my PR as to how I did that.

Sure! I'll have a look.

**Comment by dipanshparmar** [comment]
> Also I got slightly confused because you closed the previous PR and opened this new one. Avoid doing that, it is almost always better to update an existing PR instead of closing/opening a new PR.

Okay! I'll keep that in mind for the next time :smile:

**Pull request closed without merging**
