### PR TITLE
fixed overlapping issues in simulator

### LINKED ISSUE #1945: Bugs
**Describe the bug**
1.) The "TIMING DIAGRAM" is overlapping to one more template in the screen sizes 1143px or less
2.) The toggling on of the navigation bar at screen sizes less than 991px, the contents of the navigation bar are hidden

**To Reproduce**
1. Go to 'https://beta.circuitverse.org/'
2. Click on 'simulator'
3. Reduce the screen size using chrome dev tools

**Expected behavior**
The contents of navbar after toggling on of the navbar should be seen clearly
No two templates should overlap each other

**Screenshots**
1.) 
download (4)
2.)
download (3)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser :  Chrome

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes #1945 

#### Describe the changes you have made in this PR -
1. Fixed overlapping issues

### Screenshots of the changes (If any) -
**Before**
image
**After**
image

***
**Before**
image
**After**
image

***
image
I felt like that this was intentional so I just moved it to the left bottom for better UI

### CODE REVIEW

**Review by abstrekt — APPROVED** [review]
LGTM

**Review by shubhankarsharma00 — APPROVED** [review]

**Comment by satu0king** [comment]
@dipanshparmar can you fix the conflict and we acn merge this?

**Comment by dipanshparmar** [comment]
@satu0king please go ahead.

**Comment by dipanshparmar** [comment]
@satu0king any updates on this?

**Comment by dipanshparmar** [comment]
@tachyons Can you please check this one as well?

**Pull request closed without merging**
