### PR TITLE
New UI - contribute page

### PR DESCRIPTION
**Pull request by aayush-05**
**Screenshots**

1.
image
---------------------------------------------------------------------------------------------------------------
2.
image
---------------------------------------------------------------------------------------------------------------
3.
image

### CODE REVIEW

**Comment by aayush-05** [comment]
@tachyons @nitin10s

**Comment by shubhankarsharma00** [comment]
looks good :+1:

**Comment by Ananthavijay** [comment]
@tachyons @shubhankarsharma00  Check this one also: https://github.com/CircuitVerse/CircuitVerse/pull/840

**Comment by nitin10s** [comment]
I sent you the icons for Student, Developer and Teacher... Please use that.

**Comment by aayush-05** [comment]
I tried, but those icons have a lot of white space around them so they don't scale well when placed in the webpage. Can you remove the extra white background they have around them ?

**Comment by nitin10s** [comment]
Sent you the changed ones, please replace.

**Comment by aayush-05** [comment]
@nitin10s made the required changes.
image

**Pull request merged**
