### PR TITLE
Renaming tabs and circuit merged withmaster  

### LINKED ISSUE #655: Change Project Name by clicking name on top of page.
**Is your feature request related to a problem? Please describe.**
If I want to change name of project while creating a circuit I have to go to the box at the bottom left, which is visible only in the default setup of page which we can access by deselecting any element, etc.

**Describe the solution you'd like**
I suggest that double clicking the title at the top of the page should make it possible to change the name of the Project. This feature can also be added to the names of circuits.

**Describe alternatives you've considered**
Alternative can be to just add a button beside the title which will enable "Edit Mode" and we'll be able to edit all names like Project, Circuit, etc.

**Are you working on this? (Yes/No)**
Nope. For GCI 2019

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #655 and merge conflicts in #885 

#### Describe the changes you have made in this PR -
Just merged some conflicts which I believe were mainly due to #1349  

### Screenshots of the changes (If any) -
PR

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by shubhankarsharma00** [comment]
Btw as I was solving merge conflicts this PR isn't still ready and a lot of work is needed for eg if I draw an element and I select tab and press delete element gets deleted moreover it still won't work unless the simulation area was selected last. 
problem
In this gif, I am continuously trying to rename by clicking on the circuit but it doesn't work until I select the grid.

**Comment by shubhankarsharma00** [comment]
Made some changes now clicking even when `globalScope.root` is not last selected will set simulationArea.lastSelected as `globalScope.root` and then sleects the whole name (which I prefer over placing the cursor at start). I set a 100ms timeout (in this time showProperties is called and the input box is setup in DOM) Please tell me if there is better way to do this.

**Comment by satu0king** [comment]
@shubhankarsharma00 can you redirect this PR to new_UI branch? Thanks!

**Comment by shubhankarsharma00** [comment]
@satu0king on it.

**Comment by satu0king** [comment]
Closing PR as this is old UI. Thanks!
This is implemented in the new UI.

**Pull request closed without merging**
