### PR TITLE
[GCI] Improve Profile Page

### PR DESCRIPTION
**Pull request by NumberC**
Issue #589 for GCI

So far, I have setup the form. How do you want me to handle the data entered in it? Should it go to the database? If so, what's the structure?

### CODE REVIEW

**Comment by tachyons** [comment]
@nitin10s

**Comment by nitin10s** [comment]
Hey! Can you please attach a screenshot? Thanks.

**Comment by NumberC** [comment]
@nitin10s Those are the options. When you click on any of those buttons, the fields will change to the fields required for a teacher or student. 
Capture

**Comment by nitin10s** [comment]
Looks pretty clean to me if we judge by the aesthetics. Good work.

**Comment by NumberC** [comment]
To refactor my fork, I will be closing this and making a new PR. The result will still be the same

**Comment by NumberC** [comment]
Nevermind, that was meant for another PR

**Pull request closed without merging**
