### PR TITLE
Fix footer allignment

### LINKED ISSUE #1142: Fix footer alignment
**Describe the bug**
Fix footer elements alignment for smaller displays. Make sure it doesn't create any horizontal scroll on the page.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rishipurwar1**
Fixes #1142 

#### Describe the changes you have made in this PR -
Fix footer alignment in mobile view

### Screenshots of the changes (If any) -
**Before**
**MOBILE VIEW**
bug

**PC**
bud1142

**After Fix**
**Mobile View**
bug1142

PC
bug1142

### CODE REVIEW

**Comment by rishipurwar1** [comment]
Please review my pr @nitin10s @tachyons @aayush-05

**Comment by aayush-05** [comment]
There seems some unrelated changes, please remove them. Also attach screenshots for pc as well.

**Comment by rishipurwar1** [comment]
Please check fixes @aayush-05 and screenshot updated

**Comment by aayush-05** [comment]
@tachyons @nitin10s this  can be closed >> fixed with new UI

**Pull request closed without merging**
