### PR TITLE
added truncate() method to project.name, partialzied project cards

### PR DESCRIPTION
**Pull request by abstrekt**
A simple fix for un-even cards, title longer than 21 characters shall be truncated.
Firefox_Screenshot_2020-04-02T18-17-32 869Z

### CODE REVIEW

**Comment by abstrekt** [comment]
@tachyons

**Comment by tachyons** [comment]
Since we are using same ui component in multiple places, can you extract this into a rails partial

**Comment by abstrekt** [comment]
@Tachyons
like this?
_title.html.erb:
```
<%= truncate( @title, length: 18) %>
```
_dashboard.html.erb:
```
<h3 class="cardname"><%= render 'title' %></h3>
```
how to add the project.name to this variable title?

**Comment by abstrekt** [comment]
> 
> 
> @abstrekt It would be better if you reduce the length to 18 so that the cards with fitting title are even with those having longer titles. Currently the public tag goes in the next line when longer title is there.
> With length 21 :
> Capture1
> 
> With length 18 :
> Capture

kk

**Comment by tachyons** [comment]
No, the entire ui component, something like 


_project_card.html.erb

**Comment by abstrekt** [comment]
> 
> 
> No, the entire ui component, something like
> 
> _project_card.html.erb

acha okay, & how to initialize the variables with values while rendering?

**Comment by abstrekt** [comment]
@tachyons 
Firefox_Screenshot_2020-04-03T11-56-20 835Z

**Comment by tachyons** [comment]
You need to pass variables to partial, refer rails guide

**Comment by abstrekt** [comment]
@tachyons please check

**Comment by tachyons** [comment]
@nitin10s

**Comment by nitin10s** [comment]
LGTM @aayush-05 ?

**Comment by aayush-05** [comment]
Looks good; although can it be merged after my PRs because the favourites, Circuits and User Profile page will be combined into a single page.

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed >> card styles have been changed a bit in the new UI and this got implemented. Thanks @abstrekt

**Pull request closed without merging**
