### PR TITLE
Added a consistent color scheme in the Combinational Analysis Tool

### LINKED ISSUE #1748: Inconsistent color scheme in the Combinational Analysis Tool
**Describe the bug**
The Combinational Analysis Truth Table has a green and white color scheme which isn't consistent with the theme of the simulator.

**To Reproduce**
1. Go to [Simulator Beta Version](https://beta.circuitverse.org/simulator)
2. Click on ```Tools - > Combinational Analysis```
3. Enter the variables to see the table.

**Expected behavior**
A color scheme more consistent with the simulator theme

**Screenshots**
image

**Are you working on this issue? (Yes/No)**
No, open for triage

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes #1748

#### Describe the changes you have made in this PR -
I have added a consistent color scheme in the Combinational Analysis Tool...

### Screenshots of the changes (If any) -
Before->

After->
Screenshot (13)
Screenshot (14)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Prerna-0202** [comment]
@gr455, Can you please review my pr and provide me with the feedback...

**Review by abstrekt — COMMENTED** [review]
This green is part of the theme, this doesn't need a change. @Prerna-0202 

But what you can work on is the alignment of the table, it's not centered properly, also the button padding is off.

**Comment by Prerna-0202** [comment]
Okay @abstrekt, Thanks for reviewing I will commit the changes as soon as possible...

**Comment by Prerna-0202** [comment]
@abstrekt, I have commit the changes. Can you please review my pr...

**Comment by Prerna-0202** [comment]
@abstrekt, I have commit the changes. Can you please review my pr once...

**Comment by nitin10s** [comment]
@abstrekt We are deliberately wanting to change the green to black because green elements like these are used as buttons in our interface everywhere. Also, the buttons are to be changed everywhere. I plan to design a set of buttons with varying hierarchies to solve this, so let's ignore buttons.

**Review by nitin10s — APPROVED** [review]

**Comment by gr455** [comment]
@abstrekt Let me know if this looks good to you so we can merge this

**Pull request merged**
