### PR TITLE
Dashboard now shows user has no projects in case of private projects

### LINKED ISSUE #2001: Dashboard : Blank Space when the User Has all private circuits
**Describe the bug**
When the user has no circuits, there is an indication shown by image that the user does not have any circuits. But if the user creates a new Circuit and Keeps the Project Acces type to be private, Then in that case ( if the user has all the circuits as private ) there is no image shown and the space remains blank.

**To Reproduce**
1. See this Profile https://circuitverse.org/users/59394 . It has only one circuit that too with Private access. If we add more private access projects then the blank space remains.

**Expected behavior**
The same Image with No Circuits Indication Can be displayed.

**Screenshots**
No Circuits : 

image

All Circuits with Private Access : 
 
From Main User Dashboard :
image

From Other User's End : 

image

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by sarthakm21**
Fixes #2001 

#### Describe the changes you have made in this PR -
The dashboard no longer shows a blank screen in the projects section when the user's projects are private. Instead, it now shows the user has no projects image.

### Screenshots of the changes (If any) -
private1
private2

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by satu0king** [comment]
@tachyons can u check this ?

**Comment by tachyons** [comment]
Can you love the filtering logic to controller ?

**Comment by sarthakm21** [comment]
@tachyons I'll have to introduce an additional variable for the index action that will only be used in the _dashboard partial to do that. Will that be alright?

**Comment by sarthakm21** [comment]
Can someone please guide me how to resolve this test coverage issue. I cannot find the test files for the controller.
Thanks in advance

**Comment by nitin10s** [comment]
Hey, are you still working on this PR? You can ask your doubts on Slack and somebody will help.

**Pull request closed without merging**
