### PR TITLE
image upload plugin

### PR DESCRIPTION
**Pull request by pavanjoshi914**
#### Describe the changes you have made in this PR -
1> integrating image upload plugin in trumbowyg
2> using imgur api as a image host for upload requests
3>integrating resizimg plugin for resizable images
4>integrating jquery-resizable plugin as a dependency
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by satu0king** [comment]
Awesome! Do you think we can have support for multiple fonts?

**Review by pavanjoshi914 — COMMENTED** [review]
> Awesome! Do you think we can have support for multiple fonts?

Not sure but I will try to figure out and will  update you with this !!!

**Comment by pavanjoshi914** [comment]
> Awesome! Do you think we can have support for multiple fonts?

Hii @satu0king  trumbowyg has a plugin for font family which support 13 different types of font family! 
here is the link https://alex-d.github.io/Trumbowyg/demos/#plugins-fontfamily

**Comment by satu0king** [comment]
> > Awesome! Do you think we can have support for multiple fonts?
> 
> Hii @satu0king trumbowyg has a plugin for font family which support 13 different types of font family!
> here is the link https://alex-d.github.io/Trumbowyg/demos/#plugins-fontfamily
> 
> shall I proceed for the PR for this...

Sure go ahead

**Pull request merged**
