### PR TITLE
Improved the color scheme and design of the navbar

### LINKED ISSUE #1239: UI Enhancement - Simulator nav-bar
**Regarding UI enhancement**

**Is your feature request related to a problem? Please describe.**
The navbar color scheme seems odd  , The popup is of black color which I don't consider going along with the design idea and vibe. Moreover there is no depiction of what's dropdown is currently being viewed

**Describe the solution you'd like**
I want that the dropdown should be of light black , and the menu item , to be of a different color which also matches with the dropdown's color.

**Additional context**
I can create a bar with initail width 0 and sweeps right when a dropdown's item will be hovered.

**Are you working on this? (Yes/No)**
yes

### LINKED ISSUE #1247: UI Enhancement - Color scheme of the Naviagation Bar
**Is your feature request related to a problem? Please describe.**
The colors of the navigation bar is not , in harmony and completely not par with current modern design trend and scheme

**Describe the solution you'd like**
As the modern design is completely based on flat design and placement , I want that only the logo should be on left , when we hover an item , the background and the color of font should change , moreover the dropdown color scheme is not at all matching the simulator's scheme

**Are you working on this? (Yes/No)**
Yes , I would Like to complete it in Summer .

### PR DESCRIPTION
**Pull request by RohitKumarGit**
Fixes #1247

#### Describe the changes you have made in this PR -
**what's done**
I changed the font , redesigned the hover effect with pure CSS , Implemented some modern design trends to make the navbar look awesome.

**what more I plan to do**

I am thinking of shifting most of the Nav elements to right , moving the signup button to sidebar.
I have designed the final navbar in adobe illustrator and will show you In my Proposal

### Screenshots of the changes (If any) -

**before**
captured

**after**
captured (1)

**please note**
I am planning to completely rearrange the navBar but as it will take time I am creating this PR to show my abilities to do it , I have a great layout in my mind which I am for sure going to show as a picture in final proposal.

### CODE REVIEW

**Comment by aayush-05** [comment]
@nitin10s can you check this please ?

**Comment by aayush-05** [comment]
@nitin10s

**Comment by nitin10s** [comment]
We plan to completely redesign the simulator.

**Comment by nitin10s** [comment]
So, closing this.

**Pull request closed without merging**
