### PR TITLE
fix: projects utility button alignment

### LINKED ISSUE #4202: 🐞 Bug: Project utility button(edit, delete, embed) are not aligned properly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see these buttons are not aligned vertically 
Screenshot from 2023-10-19 20-20-06

### Steps To Reproduce

1. Go To Circuitverse.org
2. Go to Simulator
3. Save Project Online
4. Go to Project
5. See the buttons are not aligned vertically 

### Expected Behavior

Screenshot from 2023-10-19 20-19-31

The Buttons can be aligned vertically by adding the projects-primary-button
image
I think this class was primarily made to align the primary button but we can also use this class to align the secondary button as well, I also think we should change its name to something like projects-button-content-center 

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS: Linux Mint 21.2 x86_64
- Browser: Brave 
- version: 1.59.117
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by theslowdeveloper**
Fixes #4202

#### Describe the changes you have made in this PR -
Changed the class name projects-primary-button to projects-button to generalise the class and added it to projects utility buttons such as edit, delete and embed for alignment.

### Screenshots of the changes (If any) -
Before - 
276657969-1b2c8c8d-4fec-45d5-bb6b-fbb148e0ea65
After -
276658135-8020e351-b957-4daa-999e-18fb738c5781

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by theslowdeveloper** [comment]
@tanmoysrt should i undo the last commit of target = _blank or create a new PR, the rails check is failing due to exceeded time limit.

**Comment by tanmoysrt** [comment]
> @tanmoysrt should i undo the last commit of target = _blank or create a new PR, the rails check is failing due to exceeded time limit.

Check once by reverting the changes, if not resolved, I am checking the CI

**Comment by tanmoysrt** [comment]
@theslowdeveloper it seems to be a CI issue, you can keep your PR as before, I will try to fix this EOD

**Review by tanmoysrt — CHANGES_REQUESTED** [review]
@theslowdeveloper keep the class name as before `projects-primary-button`

**Comment by theslowdeveloper** [comment]
> name as before

should i just make another PR or commit on this one ?

**Comment by tanmoysrt** [comment]
> > name as before
> 
> should i just make another PR or commit on this one ?

commit to this one

**Comment by theslowdeveloper** [comment]
for some reason it was aligning perfectly with just projects-primary-button, so I added inline-flex as well used inline bootstrap class
here is the current view
Screenshot from 2023-11-14 20-18-36

**Review by theslowdeveloper — COMMENTED** [review]
Done

**Review by tanmoysrt — APPROVED** [review]
Looks good !

**Pull request merged**
