### PR TITLE
Fix pagination overflowing on smaller screens

### LINKED ISSUE #494: Page index unresponsive
**Describe the bug**
Page Index unresponsive after 767x760px.

**How to correct it**
Use media query and verify responsiveness using inspection.

**Expected behavior**
"Previous" and "Next" buttons should maintain its width.

**Screenshots**

### PR DESCRIPTION
**Pull request by myfrom**
Fixes #494

#### Describe the changes you have made in this pr -
Added a media query that will make the pagination scrollable on smaller screens.

### Screenshots of the changes (If any) -
before & after
ezgif-4-fc3953238352

### CODE REVIEW

**Comment by tachyons** [comment]
Looks great, can you target this to stories/new_ux branch ?

**Comment by myfrom** [comment]
@ShreyaPrasad1209 Thank you

@tachyons Can I re-target an open PR or do I need to open a new one?

**Comment by tachyons** [comment]
Re target, no need to create new one

**Comment by myfrom** [comment]
@tachyons Done, sorry for the delay

**Pull request merged**
