### PR TITLE
issue 307,345 Fix

### LINKED ISSUE #307: Keyboard doesn't work in preview mode.
https://circuitverse.org/users/2418/projects/10802 

This circuit's keyboard doesn't work in preview mode. This will mostly need copying of some listener code from listeners.js to embedListeners.js

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by SubhajitCode**
Fixes #307  and #345 

#### Describe the changes you have made in this pr -
removed the "window.parent.addEventListener('keydown', function(e)" line as it was trying to access the parent which may be  in another domain so violets cross-origin policy of browsers 

And Implemented JavaScript Workaround so browser always force  focus on the inserted iframe and we can take our keyboard input from there 

### Screenshots of the changes (If any) -
Screenshot_20190402_184056

### CODE REVIEW

**Comment by jbox144** [comment]
I read that as "issue 307345 Fix", and thought this was a late april fools day joke.

Idk about you, but I have a suspicion we haven't reached 307345 issues.

**Comment by SubhajitCode** [comment]
Hmm comma in the title was  misleading indeed

**Comment by satu0king** [comment]
Interesting, I will have to check it more closely and see if this is a good fix. The setInterval thing is not a good idea though because then it will affect the host site.

**Comment by satu0king** [comment]
@ankitkataria, I think you worked on these listener changes. Can you take a look.

**Comment by SubhajitCode** [comment]
@satu0king I changed the script tag implementation instead added a mouse event listener to capture users mouse event and focus on the iframe content so that we can take input

**Comment by satu0king** [comment]
> @satu0king I changed the script tag implementation instead added a mouse event listener to capture users mouse event and focus on the iframe content so that we can take input

An iFrame embed should ideally not need any extra listener code injected into the parent. Maybe, what we are trying to do is not actually achievable without injecting extra code. @arkokoley might have more insights.

**Comment by SubhajitCode** [comment]
@satu0king Sir I changed the code.Now no extra code in iframe is required .....

**Comment by satu0king** [comment]
@ankitkataria @Amansingla97 Can you resolve this issue. This PR will solve the main issue. However, the keyboard input stops working. 

I would like to clarify the current code using `window.parent` works fine when embedded internally. Actually, there were issues with comments when we use `window.parent`. However, without `window.parent`, the keyboard wasn't working at all.

**Comment by satu0king** [comment]
I am merging this now as it is quite critical for `docs.circuitverse.org` to work correctly.

**Pull request merged**
