### PR TITLE
Feat: features to subcircuit

### PR DESCRIPTION
**Pull request by gr455**
Extension to the feature/subcircuit branch.
Makes [feature/subcircuit](https://github.com/CircuitVerse/CircuitVerse/tree/feature/subcircuit) compatible with new UI

### CODE REVIEW

**Comment by gr455** [comment]
@abstrekt @satu0king This is ready for review 🎉

**Comment by satu0king** [comment]
image

Not compiling for me :(

**Comment by satu0king** [comment]
@gr455 please can you add screenshots.

**Comment by satu0king** [comment]
Not showing anything for me

**Comment by gr455** [comment]
> image
> image
> 
> Not showing anything for me

Fixed in #1849

**Pull request merged**
