### PR TITLE
Finalise Comments Section

### PR DESCRIPTION
**Pull request by aayush-05**
**Screenshots**
1.
image
2.
image
3.
image
4.
image
5.
image

### CODE REVIEW

**Comment by aayush-05** [comment]
@nitin10s please have a look

**Comment by aayush-05** [comment]
Sure

**Comment by aayush-05** [comment]
@nitin10s please review again. Here are the updated changes:
image
image

**Comment by aayush-05** [comment]
For 1 and 4, made them left aligned (it got center aligned while fixing up merge conflicts). As for the prototype design, the issue is we are using commontator (rails plugin) and they provide a host of features other than what we are using. So it is a little trouble understanding all the code they have.
2 one is a feature if someone wants to restore his comment back. How does this icon look for that?
image
Fixed the 3 one @nitin10s

**Review by nitin10s — CHANGES_REQUESTED** [review]
Style the New comment button as primary button and make the text "+ Add Comment" and the subscribe button should be aligned to the Comments heading. Also, a checkbox would be more intuitive.

**Review by nitin10s — APPROVED** [review]
@satu0king @tachyons LGTM

**Pull request merged**
