### PR TITLE
fix: blank in profile for educational institute

### LINKED ISSUE #4104: bug: show `not entered` if educational institute is blank in profile
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the user doesn't provide any educational institute during his profile creation/updation, in the profile, it's showing nothing like you can see below in the image.

image

### Steps To Reproduce

1. Open main website [[circuitverse.org](https://circuitverse.org/)]
2. Login yourself
3. Go to your profile
4. Go to `Edit Details` page
5. Update profile with blank `Educational institute`
6. Check your profile
7. It will not show `Not Entered` anymore

### Expected Behavior

It should show `Not Entered` in the educational institute's value if the user hasn't provided one. It is the same as the `Country` detail.
Checkout the attached image for a reference

### Are you working on this issue?

No

### PR DESCRIPTION
**Pull request by niladrix719**
Fixes #4104

#### Describe the changes you have made in this PR -

1. when we are getting "" from the edit Form, we are changing it to 'Not Entered".
2. And in the Edit Form when value of Institute is "Not Entered" we are showing a blank input box.

### Screenshots of the changes (If any) -

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/11817298-7c58-4d6a-bbe4-22aee1cc9664

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by niladrix719** [comment]
cc @tanmoysrt @vedant-jain03

**Review by vedant-jain03 — CHANGES_REQUESTED** [review]
The code wise looks good but there are 2 possible ways we can solve this
1. You suggested: Looks good as we handle everything from backend
2. From frontend using if-else: 

Why I am emphasizing to choose 2nd for this case because of internationalization. So the current changes you suggested will solve the problem but it will be static english even for different languages, would recommend to opt for frontend approach

WDYT?

**Comment by niladrix719** [comment]
@vedant-jain03 I have switched to frontend approach , I think you are right it will make more sense to handle it through if else condition

**Comment by niladrix719** [comment]
https://github.com/CircuitVerse/CircuitVerse/assets/91966855/84d31a7b-dbee-4636-b2ef-6aa76a2de7a3

cc @vedant-jain03

**Review by tanmoysrt — APPROVED** [review]
LGTM

**Review by vedant-jain03 — APPROVED** [review]
Thanks @niladrix719 LGTM 🚀

**Pull request merged**
