### PR TITLE
Updated footer to be responsive to different screen sizes + typo fix

### PR DESCRIPTION
**Pull request by woswos**
Solves the footer issue mentioned in the comments of #192 and #195

Fixes #

- Old footer used to stretch the sponsor logos based on the screen size. So, sponsor logos were looking disproportional. Fixed the stretching issue.

- Code in the "Editing Projects" page was cleaned

- Fixed a small typo in the contribute page

#### Describe the changes you have made in this pr -

- _For the footer,_ Added responsive bootstrap columns to keep the proportions. Also added ability to break the long footer into two lines based on the screen size. Image widths were defined as percentages rather than hardcoded numbers

- _For the "Editing Projects" page_, Changed "container feature" class to "container" and added other lines for consistency in the code across different pages

- _For the typo_, the sentence was changed to "If you are a company or organisation, you can"

### Screenshots of the changes (If any) -
_Typo:_
Screen Shot 2019-04-06 at 12 14 55 PM

_Old footer at different screen sizes:_
Screen Shot 2019-04-06 at 4 12 25 AM
Screen Shot 2019-04-06 at 4 12 35 AM
Screen Shot 2019-04-06 at 4 12 45 AM

_New footer at different screen sizes:_
Screen Shot 2019-04-06 at 4 14 54 AM
Screen Shot 2019-04-06 at 4 15 08 AM
Screen Shot 2019-04-06 at 4 15 16 AM

### CODE REVIEW

**Comment by woswos** [comment]
Additionally,

- Code in the "Editing Projects" page was cleaned. Changed "container feature" class to "container" and added other lines for consistency in the code across different pages

- Fixed a small typo in the contribute page
Screen Shot 2019-04-06 at 12 14 55 PM

**Comment by woswos** [comment]
@tachyons I moved inline styles to the css file. Thank you for the advice.

**Comment by tachyons** [comment]
I think `public/css/logixRelease.css`  Shouldn't be the file that deals with layout styling, cc  @satu0king

**Comment by woswos** [comment]
@tachyons @satu0king  I totally agree but ```public/css/logixRelease.css``` is the only CSS file that is being included in all pages. Since the footer is a thing that needs to be on almost every page, I decided to put it in ```public/css/logixRelease.css```. In the future, I am planning to organize styling files a little be more and files require lots of commenting. There are almost no comments in the code at the moment.

**Comment by tachyons** [comment]
you can add in `app/assets/footer.scss` or just append in `app/assets/application.scss`

**Pull request merged**
