### PR TITLE
Fixed XSS issue in Combinational Analysis (#1720)

### PR DESCRIPTION
**Pull request by 1337w0rm**
XSS on Combinational Analysis Fix by stripping tags from user input before reflecting back to DOM.

### CODE REVIEW

**Comment by satu0king** [comment]
@gr455, @Shivansh2407 please review this PR

**Comment by gr455** [comment]
> @gr455, @Shivansh2407 please review this PR

Seems like the PR is incomplete

**Comment by 1337w0rm** [comment]
@gr455 What do you mean ?

**Comment by gr455** [comment]
> @gr455 What do you mean ?

Hey, I tried this locally, but it seems to not find the stripTags() function

**Comment by Shivansh2407** [comment]
Also will this be working for multiple Inputs like <script>alert(1)</script>, <script>alert(2)</script> ... etc. ? Please attach screenshots or a screen recording too.

**Comment by satu0king** [comment]
@gr455 Striptags is defined in `public/src/utils.js` I am not sure if its works properly though but we are using in a few places. However @1337w0rm didn't import it.

**Comment by gr455** [comment]
> @gr455 Striptags is defined in `public/src/utils.js` I am not sure if its works properly though but we are using in a few places. However @1337w0rm didn't import it.  

Yep @1337w0rm , please import it

**Comment by 1337w0rm** [comment]
@gr455 please review the changes.

**Review by gr455 — CHANGES_REQUESTED** [review]
Multiple errors:
1) The import is wrong. When using named imports, you must import as `import {stripTags} from './utils'`
2) You have used strip() function which is not found. Did you mean split()?

**Comment by 1337w0rm** [comment]
@gr455  Sorry for the trouble. I'm having trouble setting up the local development environment. I'm using gitpod for now but I think it is also not working as expected.

Made the changes please review.

**Comment by 1337w0rm** [comment]
@Shivansh2407 This works for comma seperated script tags as well.

[
image
](url)


[
image
](url)

**Review by Shivansh2407 — APPROVED** [review]
Working Well @1337w0rm 👍 .

**Review by gr455 — APPROVED** [review]
LGTM

**Pull request merged**
