### PR TITLE
fix(groups): prevent users from adding whitespace to group name

### LINKED ISSUE #2855: While creating a new group if i enter a blank space it is accepting blank space as group name
**Describe the bug**
While creating a new group if i enter a blank space it is accepting blank space as group name

**To Reproduce**
1. Go to 'Create group'
2. Enter blank space as group name 
3. Click on save

**Expected behavior**
it should show alert when blank space is entered

**Screenshots**

Screenshot (139)

Screenshot (140)

Screenshot (138)

**Are you working on this issue? (Yes)**

### PR DESCRIPTION
**Pull request by diivi**
Fixes #2855 

### Screenshots of the changes (If any) -

trying to create group name with whitespace

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Prerna-0202** [comment]
Hey @diivi, Thanks for making pr but this issue has been already solved. Please prefer to ask by commenting on the issues before start working.
You can find other open issues and start working by commenting.

**Comment by diivi** [comment]
Hi @Prerna-0202 , which branch has the fix? I was able to create a group with a blank name on the master branch so I made the PR. also if you could link the merged PR and/or close the issue it would be helpful for other contributors.

**Comment by diivi** [comment]
I can create a group with a whitespace name on the main website right now, maybe I am wrong about the branching here though?
blank name

**Comment by Prerna-0202** [comment]
Really very sorry @diivi, I understand the issue wrong, I thought without entering anything, It is saving the name. I am reopening the pr.

**Review by Prerna-0202 — APPROVED** [review]
Great work @divii 🎉,
Welcome to CircuitVerse.

**Review by vedant-jain03 — APPROVED** [review]
LGTM

cc @tachyons

**Comment by tachyons** [comment]
You can simply add presence validator to Group#name

**Comment by tachyons** [comment]
@diivi Have you tested that?

**Comment by diivi** [comment]
@tachyons presence validator work here, my bad.

**Pull request merged**
