### PR TITLE
Css correction of alert in case of invalid login and improving code structure

### LINKED ISSUE #22: Fix css and bootstrap for mobile
There are small css and bootstrap issues. For example, this is the sign in page on mobile below. 

image

### PR DESCRIPTION
**Pull request by Amansingla97**
Fixes #22 

### Screenshots of the changes (If any) 
screenshot 2019-03-02 at 11 36 02 pm
screenshot 2019-03-03 at 12 10 19 am

### CODE REVIEW

**Comment by armudgal** [comment]
Hi, thanks for the PR. please open a corresponding issue and reference it here.

**Comment by Amansingla97** [comment]
Done

**Comment by satu0king** [comment]
Hey, I just merged PR #156 so that has created some conflict, could you look into it? It seems a minor issue. Thanks!

**Comment by Amansingla97** [comment]
@satu0king kindly look into it merge it.

**Comment by Amansingla97** [comment]
@satu0king it was due to merge conflicts

**Comment by satu0king** [comment]
Looks good to me. Thanks

**Pull request merged**
