### PR TITLE
XSS on Combinational Analysis Fix ( Issue #1720 )

### PR DESCRIPTION
**Pull request by 1337w0rm**
XSS fix on Combinational Analysis by stripping tags from `inputListNames`and `outputListNames` before reflecting it to DOM.

### CODE REVIEW

**Comment by gr455** [comment]
Hey, looks good but can you add the change to public/src/<filename> instead of public/js/<filename>
Sorry I didn't mention that, but public/js is deprecated

**Review by gr455 — COMMENTED** [review]
Hey, looks good but can you add the change to public/src/<filename> instead of public/js/<filename>
Sorry I didn't mention that, but public/js is deprecated

**Comment by 1337w0rm** [comment]
Sure. Should I close this PR and open up a new one ?

**Comment by gr455** [comment]
> Sure. Should I close this PR and open up a new one ?

Not requied, you can make changes and push in your 'xssfix' branch and they'll automatically inegrate with this PR

**Comment by 1337w0rm** [comment]
I messed up something. I made a new PR. I'm Sorry Closing this one.

**Pull request closed without merging**
