### PR TITLE
Add Illustration for empty favourites  

### LINKED ISSUE #1237: An illustration on the 'favourites page', If there are no favourite projects of the user
**Is your feature request related to a problem? Please describe.**
If there are no favourites added by a user, show an illustration rather than just showing a message

**Additional context**

WhatsApp Image 2020-03-18 at 18 45 02

**Describe the solution you'd like**
An illustration like this
undraw_empty_xct9

**Are you working on this? (Yes/No)**
yes

### PR DESCRIPTION
**Pull request by akansha-singh**
Fixes #1237 

#### Describe the changes you have made in this PR -
Added an illustration if there are no Favourite projects of the user

WhatsApp Image 2020-03-20 at 20 57 10

In case the User have favourite projects 

WhatsApp Image 2020-03-20 at 20 59 09

### CODE REVIEW

**Comment by akansha-singh** [comment]
> This looks nice. It would be good if you could add the text "You don't have any favourite projects yet" below the illustration.

WhatsApp Image 2020-03-21 at 11 57 08

**Comment by yash15601** [comment]
@nitin10s  what about no projects ,should we add Illustraion  their also

**Comment by abstrekt** [comment]
Make sure these illustrations are copyright free, looking nice.

**Comment by nitin10s** [comment]
Yes, an illustration in no projects is needed as well. @akansha-singh Can you confirm the source of this illustration? Also, please post screenshots for mobile and tablet view as well.

**Comment by akansha-singh** [comment]
> Yes, an illustration in no projects is needed as well. @akansha-singh Can you confirm the source of this illustration? Also, please post screenshots for mobile and tablet view as well.

source of the illustration- https://undraw.co/illustrations

**Comment by akansha-singh** [comment]
> Yes, an illustration in no projects is needed as well. @akansha-singh Can you confirm the source of this illustration? Also, please post screenshots for mobile and tablet view as well.

WhatsApp Image 2020-03-21 at 16 59 41
WhatsApp Image 2020-03-21 at 16 59 59
WhatsApp Image 2020-03-21 at 17 00 17

**Pull request merged**
