### PR TITLE
Fix: Copy and Paste of TextBox #445

### LINKED ISSUE #445: Text tool not behaving well with hotkeys
**Describe the bug**
When typing out text in a Text element of Circuitverse, hotkeys result in weird blended behavior. E.g. typing Ctrl + C does copy the element, but also adds a "c" to the end of the text box. Weirdness for Ctrl + Z, Delete, apostrophe, etc.

**To Reproduce**
1. Make a Text element.
2. Type anything in the box.
2. Deselect it.
3. Reselect it.
4. Type Ctrl + C. Notice how "c" is appended to the text box.
5. Paste with Ctrl + V. Notice how the pasted text box also has the extra c.

**Expected behavior**
I feel that the best solution is to treat **typing within** a text box differently than **selecting** a text box.
1. On first placement of text box, enter **typing mode**. This could be indicated with a blinking cursor.
2. Exit **typing mode** by clicking anywhere else in circuit.
3. Any time later, single click on the text box to enter **selected mode**. As with other circuit elements, this **selected mode** could be indicated by changing the color of the text box.
4. Or, any time later, double-click the text box to re-enter **typing mode**. As I mentioned earlier, this can be indicated with a blinking cursor (and the original color).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69.0

**Additional context**
I often delete my own text boxes accidentally by typing "Delete" key.

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by pulkit-30**
Fixes #445 

##### Before:
We cannot copy and paste text box

https://user-images.githubusercontent.com/76155456/147568572-20385f17-e262-4eee-8714-4a3fc49ae3f9.mov

##### After :

https://user-images.githubusercontent.com/76155456/147578731-5aed2084-f0d5-4f89-9eae-a8b06b7ff465.mov

Kindly provide me with appropriate feedback so that I can continue working on this 😄

### CODE REVIEW

**Comment by pulkit-30** [comment]
@tachyons @gr455 @nitin10s please review this PR.

**Comment by pulkit-30** [comment]
@tachyons @gr455  please review this PR.

**Comment by gr455** [comment]
Looks good, can you fix codeclimate

**Comment by pulkit-30** [comment]
> Looks good, can you fix code climate
sure @gr455, may you please help me with this one...

> Method 'keyDown' expected a return value.

What should be returned?

**Comment by gr455** [comment]
> > Looks good, can you fix code climate
> 
> sure @gr455, may you please help me with this one...
> 
> > Method 'keyDown' expected a return value.
> 
> What should be returned?

Make it so that the other return statements in the function don't return anything either. Eslint is complaining that the function has some paths that return values and a path that returns nothing, this is an inconsistency. You can make it so that none of the paths return any value

**Comment by pulkit-30** [comment]
> Looks good, can you fix codeclimate

Fixed 😁... Please review

**Review by gr455 — APPROVED** [review]

**Review by Prerna-0202 — APPROVED** [review]

**Pull request merged**
