### PR TITLE
connect wires with clicks 

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #

#### Describe the changes you have made in this PR -
now we finally can connect 2 terminals with clicks 🎉
- on pressing CTR we can connect with clicks
wiresss1
- without pressing CTRL we can connect them with drag
wiresss2

### CODE REVIEW

**Comment by mahmodHammad** [comment]
@satu0king  @tachyons  @nitin10s 
review this, please!

**Comment by mahmodHammad** [comment]
@satu0king

**Comment by nitin10s** [comment]
How would people know this functionality of CTR?

**Comment by ryuk156** [comment]
Built in tutorial I think this is part of gsoc project  in tutorial  will be implementing how build small circuit  @nitin10s  I think

**Comment by mahmodHammad** [comment]
@nitin10s i think this sould be done during GSOC at the custome shortcut feature, or thr getting started tutorial

**Comment by mahmodHammad** [comment]
@satu0king  conflict resolved,  check again

**Pull request merged**
