### PR TITLE
fix: Moving a component mess up the connected wires

### LINKED ISSUE #2341: Delay 0 on non input/output components is possible
**Describe the bug**
Non input/components can be set to have delay 0, and will behave as though they have delay 0. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a component
2. Set its delay to 0
3. The component will behave as though it has delay 0
4. Saving or copying another component will reset the delay to 10

**Expected behaviour**
Since a component cannot be saved with delay 0, it should not be able to be given delay 0.

**Screenshots**
image

**Device Information:**
 - OS: Windows 10
 - Browser: Chrome

Are you working on this issue? No

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes #2341, #1493 

#### Describe the changes you have made in this PR -
1. Fixed:- We can work with delay 0, but we can't save a circuit with components having delay 0 (On saving the circuit, the delay automatically returns back to the default value). 
2. Fixed:- Moving a component mess up the connected wires.
3. Fixed:- Error messages do not remove even after resolving the issues.

Screenshots:-

Before:

[moving components before.webm](https://github.com/CircuitVerse/CircuitVerse/assets/89515816/686d5790-37b5-4a5b-88a1-a2666e1d5292)

After:

[moving components.webm](https://github.com/CircuitVerse/CircuitVerse/assets/89515816/56002072-3e78-410a-b4c5-66cdc78072f5)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by gr455 — APPROVED** [review]
Wiring works much better with this. Thanks!

**Comment by gr455** [comment]
@Prerna-0202 Can you fix codeclimate? Maybe make fadeTimeOut a global variable

**Comment by Prerna-0202** [comment]
> @Prerna-0202 Can you fix codeclimate? Maybe make fadeTimeOut a global variable

Done 👍

**Comment by gr455** [comment]
> > @Prerna-0202 Can you fix codeclimate? Maybe make fadeTimeOut a global variable
> 
> Done 👍

Thank you so much. LGTM, merging.

**Pull request merged**
