### PR TITLE
RAM component

### PR DESCRIPTION
**Pull request by fpintos**
This change implements a RAM component in CircuitVerse to address #81.

Two settings are available:
- addressWidth: 1 to 20, default=10. Controls the width of the address input.
- bitWidth: 1 to 32, default=8. Controls the width of data pins.

Amount of memory in the element is 2^addressWidth x bitWidth bits.
Minimum RAM size is: 2^1  x  1 = 2 bits.
Maximum RAM size is: 2^20 x 32 = 1M x 32 bits => 32 Mbits => 4MB.
Maximum 8-bits size: 2^20 x  8 = 1M x 8 bits => 1MB.
Default RAM size is: 2^10 x  8 = 1024 bytes => 1KB.
 
RAMs are volatile therefore this component does not persist the memory contents.

Changes to addressWidth and bitWidth cause data to be lost.
Think of these operations as being equivalent to taking a piece of RAM out of a 
circuit board and replacing it with another RAM of different size.

The contents of the RAM can be reset to zero by setting the RESET pin 1 or 
or by selecting the component and pressing the "Reset" button in the properties window.

The contents of the RAM can be dumped to the console by transitioning CORE DUMP pin to 1
or by selecting the component and pressing the "Core Dump" button in the properties window.
Address spaces that have not been written will show up as `undefined` in the core dump. 

NOTE: The maximum address width of 20 is arbitrary.
Larger values are possible, but in practice circuits won't need this much
memory and keeping the value small helps avoid allocating too much memory on the browser.
Internally we use a sparse array, so only the addresses that are written are actually
allocated. Nevertheless, it is better to prevent large allocations from happening
by keeping the max addressWidth small. If needed, we can increase the max.

An example of a circuit using the new component is shown below:
image

### CODE REVIEW

**Comment by satu0king** [comment]
Looks great! will have to test it thoroughly. 

Minor feature request, would it possible to show the address and data value on the RAM component itself. 

I think this would be great for debugging, what do you say? Something like this. 
image

This feature request can be a separate issue if required.

**Comment by fpintos** [comment]
I suppose we can show these values in the RAM itself; on the other hand, one could use a Tunnel for that.

**Comment by satu0king** [comment]
> I suppose we can show these values in the RAM itself; on the other hand, one could use a Tunnel for that:
> image

Yes, we can get around it with flags. The RAM looks great as it is now. I will check and merge it soon.

**Comment by jbox144** [comment]
> NOTE: The maximum address width of 20 is arbitrary.
Larger values are possible, but in practice circuits won't need this much

Is this a challenge?

**Comment by fpintos** [comment]
> > NOTE: The maximum address width of 20 is arbitrary.
> > Larger values are possible, but in practice circuits won't need this much
> 
> Is this a challenge?

Hehe...it is an assumption, based in absolutely no data at all. :-)

It might be interesting to try and see how big we can go.
I noticed that I can't create an Array with 2^32 entries, so max addressWidth can't be 32:
```js
var a = new Array(Math.pow(2,32))
VM74:1 Uncaught RangeError: Invalid array length
    at <anonymous>:1:9
```

One less address would be ok:
```js
new Array(Math.pow(2,32)-1).length == 4294967295
true
```

So let's assume we could do 2^31 instead.
How long would it take to fill up such an array?
CircuitVerse clock can be set at most to 50ms, so assuming we can write a new entry every clock cycle it would take 107374182400ms, ie, about 1243 days, or 3-and-a-half years to fill up that RAM. :-)

But the other problem is that we can't even fill up a 2^31 array in JavaScript.
I've tried this:
```js
console.time();
var a=new Array(Math.pow(2,<max bit width you are willing to try>));
for(var i=0; i<a.length; i++) { a[i] = 0xFFFFFFFF }
console.timeEnd();
```

In my machine things were happy all the way to 26 bits.
Nodejs ran out of heap when I tried with 27 and Chrome crashed.
With 28 bits, Edge crashed as well.

So, assuming we were to go with 26, we would still need 64 arrays to support the full 32-bit address space. If we try to fill up multiple 2^26 arrays to see how far we can go....
```js
console.time(); 
var x=new Array(64); 
for(var j=0; j<x.length; j++) { 
    console.log(j);
    var a=new Array(Math.pow(2,26)); 
    for(var i=0; i<a.length; i++) { a[i] = 0xFFFFFFFF }
    x[j] = a; 
}
console.timeEnd();
```
Node blows up while filling up the 2nd array - maybe it can go further if I tweak the settings...
Both Chrome and Edge crashed on the 6th array.

So, it seems pretty reasonable to say people shouldn't be trying to fill up such large arrays in the simulator. It would be nasty to run a simulation for 3 years only for it to blow up because we run out of memory. 

That being said, if someone needs to create an address space larger than 2^20 (as currently supported) they can multiplex several RAMs.

If nothing else, I have a newfound appreciation for our physical machines and their plenty of RAM and storage.
:-)

**Comment by jbox144** [comment]
I was kinda hoping the RAM component would look similar to the ROM component, meaning you could read the values directly. If I get around to it, I'll make a new RAM component complete with visual feedback, and a ROM component with custom bitwidth

**Comment by fpintos** [comment]
This is something we can solve with a DMA pin - suppose this RAM exports a single "direct memory access" pin; then other DMA-aware components could connect to this RAM and directly read/write the memory in bulk.
For example, I can think of DMA components like this:
- a FileWriter component, which saves the contents of the RAM to the host OS.
- a FileReader component, which takes the contents of a file and populates the RAM with it
- a graphics card, this would connect the RAM to a bunch of LEDs
- a memory viewer - this is your example, this would show the contents of the RAM;
  - but then there is the question of how to format; 
  - there can be one that formats the data as ASCII, another that does HEX, etc.

Having this "DMA" pin allows us to decouple the RAM from what you want to do with that RAM.

**Comment by satu0king** [comment]
> Having this "DMA" pin allows us to decouple the RAM from what you want to do with that RAM.

@fpintos I like this idea. 

> This is something we can solve with a DMA pin - suppose this RAM exports a single "direct memory access" pin; then other DMA-aware components could connect to this RAM and directly read/write the memory in bulk.
> For example, I can think of DMA components like this:
> 
> * a FileWriter component, which saves the contents of the RAM to the host OS.
> * a FileReader component, which takes the contents of a file and populates the RAM with it
> * a graphics card, this would connect the RAM to a bunch of LEDs
> * a memory viewer - this is your example, this would show the contents of the RAM;
>   
>   * but then there is the question of how to format;
>   * there can be one that formats the data as ASCII, another that does HEX, etc.
> 
> Having this "DMA" pin allows us to decouple the RAM from what you want to do with that RAM.

I really like this idea. It makes sense to have modular components which can work together.

**Comment by satu0king** [comment]
> * addressWidth: 1 to 20, default=10. Controls the width of the address input.

Is there a specific reason the default is 10? Is it to make the default memory 1KB? I think a default of 8 bits make more sense.

**Comment by satu0king** [comment]
That was some high quality code! Thank you for the PR. I like the improvement to tooltip.

**Comment by fpintos** [comment]
No particular reason; I suppose I was looking at 1K as a nice round number.
😊


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
