### PR TITLE
Add thumbnails for test-bench

### LINKED ISSUE #253: Improper thumbnail
**Describe the bug**
A proper thumbnail for test benches is not set.

**Expected behavior**
A more appropriate thumbnail must be shown, probably a default image for such objects may also seem fine. But a broken image looks odd.

**Screenshots**
Circuit

**Desktop :**
 - OS: Windows
 - Browser :chrome,
 -  Version : 73.0.3683.75

**Are you working on this issue? Yes**

### PR DESCRIPTION
**Pull request by monsij**
Two images TB_input.svg and TB_output.svg has been added for testbench icon

Fixes #253

### CODE REVIEW

**Comment by monsij** [comment]
@armudgal : Have a look now

**Comment by satu0king** [comment]
image

Please check how the icons look before sending in PR.

**Comment by satu0king** [comment]
You missed the case of the filenames. On mac it will work ... not on linux.

**Comment by monsij** [comment]
Shall I open a new issue for it or leave it for now ?

**Pull request merged**
