### PR TITLE
Responsive Navigation Menu

### LINKED ISSUE #1693: navbar UI fixes required in  new UI of simulator
**Describe the bug**
problem1:whe navbar collapse, sign in button and toggler overlap on each other 
problem2 : after clicking on toggler the content is not well displayed 

**To Reproduce**
1. Go to 'https://beta.circuitverse.org/simulator'
2.minimise browser window until toggler is visible on navbar
3. click on toggler 

**Expected behavior**
sign in button and toggler must not overlap on each other 
after clicking on toggler ,concise and clean look of items should be seen

**Screenshots**
nav

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by satu0king**
Fixes #1693
Adds a commit to #1725 

@pavanjoshi914 please check if this PR is working fine. I made some changes to your PR. 

@abstrekt please review.

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
@satu0king everything looks good





but if we increase username size for smaller windows it will collapse on left-aligned nav-items (I will fix that)


err1


username contains dropdown which also contain signout button,for user convinience isn't  it should be visible at any view ?
also same class is applied to sign in button this will hide, sign in button  for smaller views

**Comment by abstrekt** [comment]
konwarankita22@gmail.com

> 
> 
> @satu0king everything looks good
> 
> 
> 
> but if we increase project name size for smaller windows it will collapse on left-aligned nav-items (I will fix that)
> 
> err1
> 
> A small suggestion:-
> username contains dropdown which also contain signout button,also same class is applied to sign in button hiding username for smaller views will hide, sign in button and signout button also for smaller views
> From user point of view isn't it better to have them visible for all views?
> What's your opinion about it @abstrekt ?

@nitin10s

**Comment by satu0king** [comment]
I will make the change and merge @pavanjoshi914 
@abstrekt @nitin10s. We will need to undertake mobile support as a separate task as there is a lot more to do, we will handle fine tuning at the time.

**Comment by pavanjoshi914** [comment]
> I will make the change and merge @pavanjoshi914
> @abstrekt @nitin10s. We will need to undertake mobile support as a separate task as there is a lot more to do, we will handle fine tuning at the time.


ohk sure sir....

plzz also have a check on this ,
visiblity hidden is not vanishing  the block of username. when cursor goes through that  block area   ,cursor changes from arrow to hand 

Screenshot from 2020-10-01 19-18-30

**Comment by satu0king** [comment]
@pavanjoshi914 can you raise a new PR to fix this please?

**Comment by pavanjoshi914** [comment]
> @pavanjoshi914 can you raise a new PR to fix this please?

transferred commits to #1858

**Pull request closed without merging**
