### PR TITLE
[GCI] Implement new loading animation

### LINKED ISSUE #468: Loader redesign proposal
**Is your feature request related to a problem? Please describe.**
Currently, the loader is a blue diamond folding animation. For better impact, we may replace it with a new loader. Would look great if opposite arms of links in the circuitverse logo light up alternatively.

**Describe the solution you'd like**
The new proposed loader might build up on top of the [circuitverse logo](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/favicon.ico) 

**Describe alternatives you've considered**

**Additional context**
loadercc
Intended for GCI'19.

**Are you working on this? (Yes/No)**
No.

### PR DESCRIPTION
**Pull request by jrester**
Fixes #468

#### Describe the changes you have made in this pr -

Implement new loading animation for simulator and embedded circuits.

### Screenshots of the changes (If any) -

loading_animation

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
Looks great. Can you make another one where the connector links change the illumination? I mean the white connectors gain more intensity and then come back to normal intensity. My concern with this blue animation is that it doesn't match the color code of the app. Again, good job.

**Comment by jrester** [comment]
@Parikshit-Hooda something like this?
loading_animation

**Comment by Parikshit-Hooda** [comment]
@jrester which one do you prefer? Comparing makes me lean towards the blue one. Let me consult Nitin on this.

**Comment by nitin10s** [comment]
I agree with @Parikshit-Hooda , the blue one looks better.

**Comment by Parikshit-Hooda** [comment]
@jrester Please make sure it doesn't affect anything else from a responsiveness standpoint or any other.

**Comment by jrester** [comment]
@Parikshit-Hooda I also prefer the blue one. 
As far as I am concerned the loader should be responsive and always stay in the center of the simulation canvas. The `fadeIn()` and `fadeOut()` also seems to work completely fine.

**Comment by satu0king** [comment]
Looks amazing!

**Pull request closed without merging**
