### PR TITLE
Fixed the first 2 changes i intended for width being going beyond 100%

### LINKED ISSUE #192: CSS issues at multiple places, body width expanding more than vw.
#### I am submitting a -

**Bug Report**

**Would like to SELF ASSIGN the issue**

#### Describe your bug/feature -
Issue with the CSS at index and projet subpages in mobile view.

#### Expected behaviour -
1. Navbar and paginator should not occupy more than 100% of view width.
2.  Stars and views sub tab should not extend beyond 100% of the width in mobile view.
3. (Proposal) Search bar in the navigation pane should be at the top conventionally

#### Current behaviour -

fixed all the issue plus gave some custom propeties to paginaton.

#### Screenshots -

img_1621

img_1620

img_1619

#### Are you working on the issue?

Yes

### PR DESCRIPTION
**Pull request by blackwolf08**
Fixes #192

### CODE REVIEW

**Comment by agarwalrounak** [comment]
Same here, use the Pull Request template. Also, mention the issue  number after `Fixes #`
For example `Fixes #n` , where `n` is the issue number.

**Comment by blackwolf08** [comment]
> Same here, use the Pull Request template. Also, mention the issue number after `Fixes #`
> For example `Fixes #n` , where `n` is the issue number.

**Comment by blackwolf08** [comment]
@agarwalrounak thanks updated wherever intended, cheers!

**Comment by satu0king** [comment]
image
This doesn't look very neat. I know if the circuit name is too long, the original CSS breaks and we need to fix that.

**Comment by blackwolf08** [comment]
Sure will use media queries and overflow property to see what’s best

**Comment by armudgal** [comment]
@blackwolf08 Please don't use media queries directly, use bootstrap classes wherever possible.

**Comment by armudgal** [comment]
Any updates here?

**Comment by kunalvishnoi** [comment]
@armudgal if @blackwolf08 is not resolving the issue i would like to work on the same.

**Comment by armudgal** [comment]
@kunalvishnoi Please respond on the original issue. Thanks

**Comment by armudgal** [comment]
Hi @blackwolf08, if you plan on working on it in future, please drop a comment here. I am closing it for now, thanks

**Pull request closed without merging**
