### PR TITLE
replaced logix with circuitverse routes

### LINKED ISSUE #2528: Remove all ocuurances of logix from codebase
Circuitverse was originally named as logix, but we still have references to it in the codebase and that is ambiguous to the new contributors. Replace the occurrences of logix with Circuitverse without changing any changes to the end user experience

### PR DESCRIPTION
**Pull request by Kartikay304**
Fixes #2528 

#### Describe the changes you have made in this PR -

1. Changed routes
2. Changed controllers
3. Changed helpers
4. Changed some files in simulator

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/40604582/136667032-3e80ebd5-8b02-476d-9191-a12951f7867a.mp4

@tachyons 

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tachyons** [comment]
PR should be logically grouped, CI should pass in each PRs

**Comment by Kartikay304** [comment]
> PR should be logically grouped, CI should pass in each PRs

Okay sir, PR is now passed in circle Ci 🙂.

**Comment by tachyons** [comment]
There are some conflicts

**Comment by vedant-jain03** [comment]
I have not played unprofessionaly I was expecting to make contribution in a team but you raised a PR by yourself for the routes and controllers and As I said in th teams that we should not work in files but in view , routes and controllers. As you can see in my pr I have added just the views part and also mention this PR for routes and controller part.

I also have messaged you in the team about the same , I have leaved the team in the slack and also I have messaged  final in th team that I will be workingin views files as I dont have knowledge of routes and controller much you did.

Parden but I am not playing anything unprofessional . My main motive was to make a fresh pr for views routes and controller seaprately as mentor said in the issue.

If communtiy still think I have played unprofessionaly then sir can revery my pr and kartik can make fresh for the whole issue.

My motive is to contribute .
Thankyou

**Comment by Kartikay304** [comment]
Well I didn't saying that your Pr should be reverted, don't try to put your words in my mouth. It's is not the solution. The solultion your should work on the files that  you have agreed..working on. Your last message which I saw was "I am not working in the issue".You said you only worked in views. 
But at least try to remember that you and I both agreed have divided the files in views.. And locale into two parts.... And If working together don't leave the team in mid. That also coke under unprofessional behavior... Now are you working on some other files which are related to this issue or not. As I am also working on the same issue..

**Pull request closed without merging**
