### PR TITLE
Fixes Three In a Row Elements

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes https://github.com/CircuitVerse/CircuitVerse/pull/1233#issuecomment-602029888

#### Describe the changes you have made in this PR -
I have fixed the elements panel to display three elements by default.

### Screenshots of the changes (If any) -
patch-37

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@satu0king please review and merge 👍

**Comment by Shivansh2407** [comment]
@satu0king please review 👍

**Comment by satu0king** [comment]
@Shivansh2407 can you check in the current version if it is 3 rows for you?

**Comment by Shivansh2407** [comment]
@satu0king I have checked. It is available two in a row. I have updated to show three elements in a row

**Comment by Shivansh2407** [comment]
Fixed in the recent commit

**Pull request closed without merging**
