### PR TITLE
Fixing Check Box Problem

### PR DESCRIPTION
**Pull request by Subhraneel77**
Fixes #2875

#### Describe The Changes you have made in this PR -

Added a CSS property where the position is made Static  as well as modified the div element  under .primary-checkpoint-container

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@Subhraneel77 Thankyou for working on the issue, but this issue is under review and also raised by [Ankur-Agrawal-ece20](https://github.com/Ankur-Agrawal-ece20), on the basis contribution guideline if someone is already working on the issue and raised a PR, another issue would not be entertained.
We are glad you have worked on the issue but contribution guidelines are must to follow for contribution.

**Comment by vedant-jain03** [comment]
@Kartikay304 @pulkit-30 can we close this?

**Comment by pulkit-30** [comment]
> @Kartikay304 @pulkit-30 can we close this?

Yep!

**Comment by Kartikay304** [comment]
> @Kartikay304 @pulkit-30 can we close this?

Sure

**Pull request closed without merging**
