### PR TITLE
Docs for creation of Facebook, Google, Github App

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/792

#### Describe the changes you have made in this pr -
- Made a seperate wiki page for creation of Google, Facebook, Github app and linked it with readme.

### CODE REVIEW

**Comment by tachyons** [comment]
Can we do this in wiki instead

**Comment by Ananthavijay** [comment]
Fine @tachyons

**Comment by Ananthavijay** [comment]
Done @tachyons 
Check the page here : https://github.com/CircuitVerse/CircuitVerse/wiki/Create-Apps

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209 @tachyons Have a look at the [wiki page](https://github.com/CircuitVerse/CircuitVerse/wiki/Create-Apps).

**Comment by tachyons** [comment]
Resolve conflicts please

**Comment by Ananthavijay** [comment]
@tachyons I will remove the commit and will request @JoshHeng to add this is in his "Restructure Readme" PR .

**Comment by Ananthavijay** [comment]
I will close this PR, just check the [wiki page](https://github.com/CircuitVerse/CircuitVerse/wiki/Create-Apps).

**Pull request closed without merging**
