### PR TITLE
fix(ci): fixed major CI problems related to missing canvas and outdated node.

### PR DESCRIPTION
**Pull request by salmoneatenbybear**
## Summary by CodeRabbit

- **New Features**
	- Introduced Node.js version 18 in multiple workflows for improved compatibility.
	- Added steps for generating documentation using JSDoc.
	- Enhanced CI workflow for Ruby on Rails with PostgreSQL and Redis services.

- **Bug Fixes**
	- Updated selectors for group member promotion and demotion to ensure correct modal targeting.

- **Chores**
	- Cleaned up configuration files by removing unnecessary comments and adding new gem entries in `rbs_collection.yaml`.

### CODE REVIEW

**Comment by salmoneatenbybear** [comment]
@tachyons 

The Ruby on Rails CI / test ( pull request ) is failing because : 

The CI failure with Steep is due to the RBS type definitions for kaminari-actionview and kaminari-activerecord being either outdated, incomplete, or both. To address this, we should first update our custom RBS stubs to reflect the latest gem APIs and ensure they are comprehensive. Additionally, if they are incomplete, we need to expand these stubs to cover all necessary methods and modules. As a long-term solution, contributing these updated and complete RBS definitions to the official RBS repository will enhance type safety for our project and benefit the broader Ruby community.

an alternative approach would be to temporarily exclude these gems from Steep's type checking until official RBS definitions are available or until we can contribute our own. This will allow the CI pipeline to pass while we explore long-term solutions for type safety.

I looked into the availability of RBS type definitions for the kaminari-actionview and kaminari-activerecord gems. It appears that these gems do not include built-in RBS type definitions, as there are no .rbs files in their repositories, nor any mention of RBS support in their documentation or release notes.

if you think that they exist and i might have missed them please point me to them, i will use them to fix the ci.

**Comment by tachyons** [comment]
you can update config to skip kaminari rbs

**Comment by salmoneatenbybear** [comment]
> you can update config to skip kaminari rbs

Noted, will get that done.

**Comment by salmoneatenbybear** [comment]
@tachyons 

ci is now fixed all checks are now passing.

**Pull request merged**
