### PR TITLE
fix(typo-hindi): typo in email hindi fixed

### LINKED ISSUE #3974: [typo]: hindi typo of email in add mentor
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

similar to #3968 but in hindi

### Steps To Reproduce

same steps as mentioned above

### Expected Behavior

it should be without id

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #3974 

#### Describe the changes you have made in this PR -
typo fixed for hindi email id 

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
CC @VaibhavUpreti  @vedant-jain03

**Review by pateldivyesh1323 — APPROVED** [review]
This can be merged.

**Comment by harshsharma-11** [comment]
@pateldivyesh1323 bro but i branch becomes outdated ,what to do

**Comment by pateldivyesh1323** [comment]
Maintainer needs to approve this

**Pull request closed without merging**
