### PR TITLE
Contributors page

### PR DESCRIPTION
**Pull request by harshitaaaaaa**
Fixes #
I have added a feature.

#### Describe the changes you have made in this PR -
I've made an HTML page mentioning the detials of the contributors.

### Comment:
I have added a dummy paragraph right below the title "Humans of CircuitVerse", instead of that some content according to the mentor has to be added.

### CODE REVIEW

**Comment by satu0king** [comment]
@harshitaaaaaa please reference #2005 in PR as fixes #2005

**Comment by satu0king** [comment]
Please share screenshots here. Also this has to come on the main app. So either it can go to public folder or better, it has to be added in logix_controller. 

How did you generate the content for each person, I hope you didn't do that manually? Also the exact content will need to be decided. The languages and number of commits are not very interesting. What is more interesting is features implemented and other contributions. Like for you - you designed the humans of circuitverse page. 

@ShreyaPrasad1209 please review this PR

**Comment by ShreyaPrasad1209** [comment]
@harshitaaaaaa few things I would like to clear before you move ahead-
- This page is supposed to follow CRUD (Create, Read, Update, Delete) operations and access will be given only to the contributers so the logic will be - if the user is present as a CircuitVerse contributor only then they can perform CRUD operations otherwise they can't. 
- You also have to check whether the user is logged in or not.
@robin025 you can help @harshitaaaaaa with this

**Review by ShreyaPrasad1209 — CHANGES_REQUESTED** [review]
@harshitaaaaaa few things I would like to clear before you move ahead-
- This page is supposed to follow CRUD (Create, Read, Update, Delete) operations and access will be given only to the contributors so the logic will be - if the user is present as a CircuitVerse contributor only then they can perform CRUD operations otherwise they can't. 
- You also have to check whether the user is logged in or not.
@robin025 you can help @harshitaaaaaa with this

**Comment by robin025** [comment]
Hi @ShreyaPrasad1209 , thanks for your reply. I was referring to #2005 as you mentioned to create a "Humans of CircuitVerse" markdown page.

So here my suggestion request!
To be able to use a markdown page that will show significant contributions of individual members in CircuitVerse so as to appreciate the efforts made by them ,we can use Jekyll theme which is a static website generator that’s designed for building minimal, static blogs and pages to be hosted on GitHub Pages.
With the help of jekyll ,it strips everything down to the bare minimum, eliminating a lot of complexity
1.We can easily transforms our plain text into static websites pages and blogs.
2.It requires no databases,cms or any updates
3.It supports static HTML, CSS javascript and even Markdown, so with the help of markdown we can easily use all types of labels like you mentioned in #2005
4.What’s best is it goes well with Github-Pages
5.It loads faster

Also to be able to create a CRUD functionality ,i don't think so this can happen in static website but we can create layouts for contributors in markdown, after that contributors just have to edit those markdown files and commit changes.

looking forward to your reply
thanks

**Comment by ShreyaPrasad1209** [comment]
@robin025 we can discuss the implementation details here

**Comment by robin025** [comment]
> @robin025 we can discuss the implementation details here


@ShreyaPrasad1209 i had a question in my mind ,like is this feature is only for contributors of Circuit Verse or for all the users

**Comment by robin025** [comment]
> @robin025 we can discuss the implementation details here

hi @ShreyaPrasad1209  if this [suggestion request](https://github.com/CircuitVerse/CircuitVerse/issues/2005#issuecomment-750414284) is fine with u I can complete this task with jekyll theme, but then dynamic functionality wont be possible.

**Pull request closed without merging**
