### PR TITLE
changing confirm, prompt of simulator to dialogs

### PR DESCRIPTION
**Pull request by abstrekt**
Fixes #

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by nitin10s** [comment]
Can you please also attach screenshots for the same? Thanks.

**Comment by abstrekt** [comment]
image
image
image
image
@nitin10s

**Comment by abstrekt** [comment]
> 
> 
>     1. After clicking Cancel the first time and then again opening the box - This appears:
>        image
fixed 
>     2. "New Project" doesn't work. Clicking on the option reloads the window.
I looked into it, that's one trouble with using modals instead of confirms, the new project function runs clear project first, previously we had confirm prompts in clear project func which used to pause the new project function until users gave a confirm, now the clear project is a modal and modals don't have that property.. what should be done?

**Comment by Prerna-0202** [comment]
@tachyons, I would like to work on this ...Can I start working??

**Comment by tachyons** [comment]
@Prerna-0202 yes

**Comment by Prerna-0202** [comment]
@tachyons, There is a problem while changing the save online prompt to the dialog, previously we had a prompt that used to pause the back function until users gave an input, now it is a modal dialog and modals don't have that property to wait until user gave the input... Can you please help me out?



https://user-images.githubusercontent.com/89515816/148682186-6ad2b324-28c7-4399-91e9-7d767a2df8b7.mov

**Comment by vedant-jain03** [comment]
> @tachyons, There is a problem while changing the save online prompt to the dialog, previously we had a prompt that used to pause the back function until users gave an input, now it is a modal dialog and modals don't have that property to wait until user gave the input... Can you please help me out?
> 
>  screen-capture.1.mov

I think @Prerna-0202 the post method is being called when save online button clicked, we have to change the scope to confirm button in popup.

**Comment by tachyons** [comment]
@devartstar FYI, alerts and prompts should be replaced like this

**Comment by devartstar** [comment]
> @devartstar FYI, alerts and prompts should be replaced like this

yes, will keep it in mind.

**Comment by tachyons** [comment]
Closing as we are doing this as part of vue based simulator

**Pull request closed without merging**
