### PR TITLE
feat: test-bench added in tutorial guide

### LINKED ISSUE #4410: Test Bench missing in Tutorial Guide
### Is your feature request related to a problem? Please describe

In the tutorial guide, all panels tour is covered except the test bench,

### Describe the solution you'd like

We need to Add a **test bench** to the tutorial guide 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by Malavi1**
Fixes #4410

#### Describe the changes you have made in this PR -

You can find an entire explanation in ##4426

### Screenshots of the changes (If any) -

Screenshot from 2024-01-11 13-14-49

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Malavi1** [comment]
@Prerna-0202 it's good to go IG!

**Comment by tanmoysrt** [comment]
Hi @Malavi1 , can you check this issue ?

When I was checking this PR, the tutorial guide was showing correctly, but it's showing incorrect way, check attached image

image

**Comment by Malavi1** [comment]
> Hi @Malavi1 , can you check this issue ?
> 
> When I was checking this PR, the tutorial guide was showing correctly, but it's showing incorrect way, check attached image
> 
> image

This is happening because if we change the test bench panel from it's default position.
While pop up it is taking the position reference of the panel it is showing like this IG. 

Screenshot from 2024-01-29 08-03-44

Screenshot from 2024-01-29 08-07-53

**Comment by tanmoysrt** [comment]
> > Hi @Malavi1 , can you check this issue ?
> > When I was checking this PR, the tutorial guide was showing correctly, but it's showing incorrect way, check attached image
> > image
> 
> This is happening because if we change the test bench panel from it's default position. While pop up it is taking the position reference of the panel it is showing like this IG.
> 
> Screenshot from 2024-01-29 08-03-44
> 
> Screenshot from 2024-01-29 08-07-53

I haven't changed the position i think. I will recheck.

**Comment by Malavi1** [comment]
@tanmoysrt did you check it!?

**Review by tanmoysrt — APPROVED** [review]
The added turorial guide working as expected.
Good to go :+1:

**Pull request merged**
