### PR TITLE
fix(notification): fixed footer of notification section

### LINKED ISSUE #4132: 🐞 Bug: Notification Page Style broken in mobile view & Large Screen(footer)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Notification Page is not responsive in mobile view.
 
nf

Footer in notification has extra white space below it.

### Steps To Reproduce

1. Sign in to your circuitverse account.
2. Open notification dropdown, click -> See all
3. Observe bug on this notification for mobile view and footer.

### Expected Behavior

Page must be responsive for all devices.

### Screenshots

_No response_

### Device Information [optional]

_No response_

### Additional context

_No response_

### Are you working on this issue?

No

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #4132 

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@VaibhavUpreti please review the pr

**Comment by harshsharma-11** [comment]
https://github.com/CircuitVerse/CircuitVerse/assets/138685168/98dc26bb-3c2c-4b3d-aa89-f2479167681b

**Comment by vedant-jain03** [comment]
@harshsharma-11 Thanks for raising a PR, no doubt it solves the issue but as per code of conduct until you have not being assigned to an issue, your PR is not going to be taken as valid. Please try to understand there are more contributors who are new and I anticipate your enthusiasm, but following norms/rules will help in longer run and keeps things legal and safe. I hope you understand.

Also I have seen you have been assigned https://github.com/CircuitVerse/CircuitVerse/issues/4089, I am marking that issue under hacktoberfest, looking forward to your PR

Happy hacking 🚀 

Closing this.....

**Comment by harshsharma-11** [comment]
> @harshsharma-11 Thanks for raising a PR, no doubt it solves the issue but as per code of conduct until you have not being assigned to an issue, your PR is not going to be taken as valid. Please try to understand there are more contributors who are new and I anticipate your enthusiasm, but following norms/rules will help in longer run and keeps things legal and safe. I hope you understand.
> 
> Also I have seen you have been assigned #4089, I am marking that issue under hacktoberfest, looking forward to your PR
> 
> Happy hacking 🚀
> 
> Closing this.....

i understand but ,if there are 2-3 comments already that are asking to assign issue to them so what's the meaning of asking to assign ,as 100% chances are there  that 1st comment will get assign with the issue .

**Pull request closed without merging**
