### PR TITLE
disable shortcuts on while reporting an issue 

### LINKED ISSUE #1326: Bug with Report Bug
report
**Describe the bug**
if the user accidentally pressed on a custom shortcut, it would be executed.

also **copy , past , cut doesnt' work**
**Are you working on this issue? (Yes/No)**
YES, I Already have Done this fix on my machine a will make a PR with the solution soon

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #1326

#### Describe the changes you have made in this PR -
- disable shortcuts on while reporting an issue 
- enable copy, past, and cut for reporting issue's text field

### CODE REVIEW

**Comment by mahmodHammad** [comment]
@satu0king  @tachyons  @nitin10s 
review, please!

**Comment by mahmodHammad** [comment]
@nitin10s it's a bug fix for. #1326

**Comment by ryuk156** [comment]
@satu0king @tachyons  this can be merged

**Comment by satu0king** [comment]
Looks like it works but I was having a bit of difficulty in merging conflicts, @mahmodHammad could you please send PR again

**Comment by mahmodHammad** [comment]
@satu0king 
conflict resolved 
please check again

**Comment by satu0king** [comment]
It works! but I think there is a minor issue while resolving the merge conflict - The report seems to be present at line 246 and line 335 as well. Could you look into it?

**Comment by mahmodHammad** [comment]
@satu0king  conflict resolved

**Comment by mahmodHammad** [comment]
@satu0king 
i didn't get what you mean, the code looks fine 
Please check again, I have resolved the conflict

**Comment by satu0king** [comment]
Merged via #1447

**Pull request closed without merging**
