### PR TITLE
fix(typo): overwrites

### LINKED ISSUE #3990: [typo]: "overwrites" is written as "overwites"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is a typo error where "overwrites " is write as "overwites"

### Steps To Reproduce

1.go to simulator 
2.create any project
3.save and then click add collaborator 
4.in form you can see this

Screenshot (253)

### Expected Behavior

overwrites

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #3990

#### Describe the changes you have made in this PR -
typo fixed "overwrites" insted of "overwites"
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
please check @VaibhavUpreti @vedant-jain03 please respond to my prs ,i have created 5,6 prs for other different issues also please respond

**Comment by harshsharma-11** [comment]
@tachyons please review

**Review by Arnabdaz — APPROVED** [review]

**Comment by Arnabdaz** [comment]
cc @tachyons

**Comment by harshsharma-11** [comment]
cc @tachyons  @vedant-jain03  please review

**Comment by harshsharma-11** [comment]
thanks a lot @tachyons it means a lot

**Pull request merged**
