### PR TITLE
Add Nepali Locale Support to CircuitVerse

### PR DESCRIPTION
**Pull request by Darshan808**
### Screenshots:
localhost_3000_
localhost_3000_contribute
Screenshot 2024-06-03 074408
localhost_3000_teachers
localhost_3000_about

## Summary by CodeRabbit

- **New Features**
  - Added support for the Nepali language across various application components, enhancing accessibility for Nepali-speaking users.
  - Introduced localization strings for user interfaces, forms, and notifications in Nepali, covering group management, assignments, projects, and pagination.

- **Improvements**
  - Expanded internationalization capabilities by including Nepali as an available locale.
  - Enhanced user experience with localized content for assignments, announcements, projects, groups, and user account management.

These updates aim to provide a more inclusive experience for users who prefer interacting with the application in their native language.

### CODE REVIEW

**Comment by tanmoysrt** [comment]
Looks good ! 
@Darshan808 great job.

btw CI has some issue, after fixing that I will merge it.

**Comment by tachyons** [comment]
Nepali language code is ne, not np, right ? np is the country code, right ?

**Comment by Darshan808** [comment]
Coderabbitai identified some typos, which have been corrected in my latest commit.

**Comment by Darshan808** [comment]
@tachyons @tanmoysrt 
Whenever you have the time, could you kindly review this PR? I would really appreciate your feedback, as I’ve put a lot of effort into it and am excited to see our Language being integrated into CircuitVerse through my contribution.

**Review by tachyons — APPROVED** [review]

**Pull request merged**
