### PR TITLE
Example page responsive#2857

### LINKED ISSUE #2857: Circuit-Cards on Example page are not responsive
**Describe the bug**
CircuitCards on [examples](https://circuitverse.org/examples) page are not responsive between 992/843 and 1199/843

**To Reproduce**
1. Go to 'https://circuitverse.org/examples'
2. resize window between 992 - 1199
3. see error

**Expected behavior**
Card Design should be responsive

**Screenshots**
Screenshot 2022-01-29 at 2 20 47 AM

**Device Information [optional]:**
 - OS: MacOS
 - Browser Chrome

**Are you working on this issue? (Yes/No)**
NO

### PR DESCRIPTION
**Pull request by Prakhargarg-2010196**
Fixes #2857 

#### Describe the changes you have made in this PR -
The CSS and component HTML was faulty I removed the circuit-card-footer class placed inside the **components.scss** and placed the example name and the tool tip inside the div with **circuit-card-name class** in the **examples.html.erb** file
### Screenshots of the changes (If any) -
[Changes upto resolution 1040 x 852](https://imgur.com/PYLOg5b)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tachyons** [comment]
Add screenshots of before and after for comparison

**Comment by Prakhargarg-2010196** [comment]
``

**Comment by pulkit-30** [comment]
Thanks @Prakhargarg-2010196,
I think you have pushed package-lock.json and yarn.lock files by mistake.

**Comment by Prakhargarg-2010196** [comment]
So can u help me what should i do to fix it i am currently new to opensource..

**Comment by pulkit-30** [comment]
yes, first reset to the previous commit(3 commits), then commit changes excluding these files and then force push to your downstream branch.

**Comment by Prakhargarg-2010196** [comment]
> yes, first reset to the previous commit(3 commits), then commit changes excluding these files and then force push to your downstream branch.

I tried but this will lead to deletion of files package.lock and yarn.lock which doen't seem to be right

**Comment by pulkit-30** [comment]
Fixed #2871

**Pull request closed without merging**
