### PR TITLE
Fixed rubocop errors and error with linter in gitpod

### PR DESCRIPTION
**Pull request by Ananthavijay**
#### Describe the changes you have made in this PR -

- Fixed error with rubocop performance and an error with rubocop linter in gitpod.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@tachyons Can I go ahead and fix all the codeclimate issues?

**Comment by Ananthavijay** [comment]
@tachyons What about the rubocop errors?

**Comment by tachyons** [comment]
Separate PR

**Comment by tachyons** [comment]
We can fix them progressively

**Comment by Ananthavijay** [comment]
Should I fix it in a separate PR or can I leave it?

**Pull request merged**
