### PR TITLE
Implement simple forum using simple_discussion gem

### PR DESCRIPTION
**Pull request by tachyons**
Implement simple discussion gem

Screenshot 2020-07-10 at 8 15 43 PM

### CODE REVIEW

**Comment by nitin10s** [comment]
What will be the entry point for this discussion forum?

**Comment by aayush-05** [comment]
> What should be the entry point for this discussion forum? Navbar Link?

It's in the footer currently.

**Comment by nitin10s** [comment]
No, I meant footer isn't really the right entry point, so where should we add the link. considering navbar already has way too many options.

**Comment by tachyons** [comment]
What exactly is the issue with having forum link in the footer ?

**Comment by nitin10s** [comment]
The forum should be considered a primary feature and thus should have a prominent entry point. Footer nav is for when your users reach the end, and instantly accessible navigation tool waiting to help them move freely around the website. In short, more of secondary navigation.

What we can do is put the forum link in the simulator navbar so that's it's highly visible to people using the simulator.

**Pull request merged**
