### PR TITLE
tooltip migration done

### PR DESCRIPTION
**Pull request by mohamedar97**
Fixes #
issue fixed please direct me if i have done anything wrong

### CODE REVIEW

**Comment by satu0king** [comment]
Why are there change to Gemfile and Gemfile.lock

**Comment by mohamedar97** [comment]
gem "pg", "~> 1.1.4"
This line was repeated twice in the gem file and i thought it could be a typo and removed it

As for the gem.lock i used bundler v 2.0 instead of 1.17

**Comment by satu0king** [comment]
We cannot merge if circleci build fail.s

**Comment by mohamedar97** [comment]
@satu0king can you please tell me how to fix it as i already have bundler v2.0.1 installed

**Comment by mohamedar97** [comment]
i appreciate any help you would give me this is my first ever contribution

**Comment by satu0king** [comment]
For now just not pushing the Gemfile and Gemfile.lock will work. I am not sure if we can have 2 different versions of bundler. @tachyons might know more.

**Comment by mohamedar97** [comment]
So should i create a new pr?

**Comment by tachyons** [comment]
Bundler version should not be an issue. Duplicate Pg line can be fixed in another PR. No need to keep unrelated changes in the PR. Also do not remove config/database.yml.example. it is a file we need.

**Comment by mohamedar97** [comment]
@tachyons okay database.example.yml is added. should i be doing anything else?

**Comment by tachyons** [comment]
You haven't pushed them yet

**Comment by mohamedar97** [comment]
i fixed them directly on the github repo

**Comment by mohamedar97** [comment]
you can see them in the changes section

**Comment by mohamedar97** [comment]
i have opened pr #304 as the repo this pr was cloning for is deleted so it cant see the changes. everything should be fine in the other pr

**Comment by mohamedar97** [comment]
i know i'm causing a bit of a hassle but bear with me please i'm still getting the hang of things

**Comment by tachyons** [comment]
But you deleted Gemfile.lock in that PR :-)

**Comment by mohamedar97** [comment]
Oh :( okay fixed
This is sad tho :)

**Pull request closed without merging**
