### PR TITLE
Revamp Comment section- New UI

### PR DESCRIPTION
**Pull request by SamriddhiMishra**
Screenshots of the changes (If any) -
1)
Screenshot (662)

2)
Screenshot (661)

### CODE REVIEW

**Comment by SamriddhiMishra** [comment]
Screenshot (667)

**Comment by SamriddhiMishra** [comment]
@nitin10s @tachyons Please review.

**Comment by SamriddhiMishra** [comment]
> Please attach screenshots for mobile and tablet view as well.

Screenshot (687)
Screenshot (686)

**Comment by tachyons** [comment]
Looks good, Can you also try updating commonator gem version to latest version as part of this PR? https://github.com/lml/commontator ?

**Comment by aayush-05** [comment]
@SamriddhiMishra are you working on this ?

**Comment by SamriddhiMishra** [comment]
@aayush-05  I am no more working on this.

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed

**Pull request closed without merging**
