### PR TITLE
feat: Profile page Improvement 

### LINKED ISSUE #4438: Feature Profile page improvement
### Is your feature request related to a problem? Please describe

Give them a section of adding social media links like github. 

Screenshot (247)

### Describe the solution you'd like

We can provide them with the option to add their social media profile to enhance the profile dashboard. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by Simer13**
Fixes #4438 

#### Describe the changes you have made in this PR -

I added the section on social media profiles (Instagram, Github, twitter, linkedin) to the profile page. 
I have made the required changes in the database to keep the information saved to the user's profile. 

### Screenshots of the changes (If any) -
Screenshot (248)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Simer13** [comment]
@tanmoysrt Hey any idea why is this one check failing? The changes I made in my localhost worked fine for me as mentioned in the issue and pr.

**Comment by tanmoysrt** [comment]
> @tanmoysrt Hey any idea why is this one check failing? The changes I made in my localhost worked fine for me as mentioned in the issue and pr.

Check the logs https://github.com/CircuitVerse/CircuitVerse/actions/runs/7346057602/job/20000198995

**Comment by Simer13** [comment]
@tanmoysrt I have made the required corrections in the commits already as stated there.

**Comment by tanmoysrt** [comment]
> @tanmoysrt I have made the required corrections in the commits already as stated there.

Check the logs many testcases has been failed. It maybe as you have added new fields and methods
```
NoMethodError:
2023-12-28T19:15:29.8399573Z  undefined method `instagram' for #<User id: nil, email: "tessa@brekke.info", name: "Jacquelyne Bednar", created_at: nil, updated_at: nil, provider: nil, uid: nil, admin: false, country: nil, educational_institute: nil, subscribed: true, locale: "en">
```

You need to fix and write new testcases for new changes as well.

**Pull request closed without merging**
