### PR TITLE
Home Page for CircuitVerse

### PR DESCRIPTION
**Pull request by ShreyaPrasad1209**
#### Describe the changes you have made in this PR -
Created a template for Home Page

### CODE REVIEW

**Comment by tachyons** [comment]
Can you please rebase, I made some changes in the branch

**Comment by ShreyaPrasad1209** [comment]
Why did you close the PR?

**Comment by tachyons** [comment]
Too many changes due to branch conflict, could not review

**Comment by tachyons** [comment]
Feel free to reopen once it is resolved

**Pull request closed without merging**
