### PR TITLE
Feature/subcircuit

### PR DESCRIPTION
**Pull request by abdullah-mohamed**
This PR is to reveal the work done during my GSoC 2019 project.
The project is concerned with adding more features to the `subcircuit` making it more useful and opening the opportunity for many more possibilities. 
This PR will be added to the blog post that will be shared with google.

### CODE REVIEW

**Comment by satu0king** [comment]
Excellent Work 🥇

**Comment by MrBartusek** [comment]
Subcircuit is already implemented, can be closed

**Comment by satu0king** [comment]
Do not close this PR, the work still needs to be merged.

**Comment by satu0king** [comment]
Finally merged via #1862!! @abdullah-mohamed

**Pull request closed without merging**
