### PR TITLE
Prevent Collapsing Tabsbar and New Look

### PR DESCRIPTION
**Pull request by krishanu-2001**
Fixes # 1287

#### Describe the changes you have made in this PR -
To tackle issue of collapsing tabsbar/ simulator: 
 * added new way of circuit's name display (with ellipsis ie, ...)
 * made max_display_size 7 , eg:
 ckt name: 1234567      ckt_name: 12345678
 tab_ame : 1234567      tab_name: 123456... which displays full name on 
                                             hovering

### Screenshots of the changes (If any) -
hutgif1
 
testing 2

hutgif2

### Alternatives
there's another ui possible:

hut1

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@krishanu-2001 This is an issue of merge conflict. Please update your branch with the master branch of CircuitVerse so that you can remove these conflicts. You can do that by either pulling it from upstream or you can do it manually in GitHub.

**Comment by krishanu-2001** [comment]
@Shivansh2407 , thanks , worked wonders

**Comment by krishanu-2001** [comment]
see -> https://github.com/CircuitVerse/CircuitVerse/pull/1290
#1290 for working PR.

**Comment by Shivansh2407** [comment]
@krishanu-2001 you could have removed the merge conflicts by updating the branch locally and then pushing the changes. Now that you have opened a new PR , then you should close this PR.

**Pull request closed without merging**
