### PR TITLE
registration-block alert texts i18n compatible

### LINKED ISSUE #4280: make registration-block alert texts i18n compatible
### Is your feature request related to a problem? Please describe

registration-block alert texts are not currently i18n compatible
Screenshot 2023-11-15 at 4 39 22 PM

### Describe the solution you'd like

We need to translate registration block alert texts into all available languages
ref PR - https://github.com/CircuitVerse/CircuitVerse/pull/4124

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

No

### PR DESCRIPTION
**Pull request by Malavi1**
Fixes #4280

### CODE REVIEW

**Comment by Malavi1** [comment]
@niladrix719 may I know where I went wrong it seems fine to me?

**Comment by niladrix719** [comment]
i think its some issue with the code climate

**Comment by Malavi1** [comment]
@tanmoysrt cloud you please review my PR!!

**Review by tanmoysrt — APPROVED** [review]
Looks good !

**Pull request merged**
