### PR TITLE
Added modal for confirmation of delete

### LINKED ISSUE #1329: A customize modal to confirm deletion of group on group page
**Describe the solution you'd like**
A customized modal in accordance with example page design to confirm deletion of group

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by harshgujrati**
Fixes #1329

### Screenshots of the changes (If any) -
Screenshot (248)

### CODE REVIEW

**Comment by harshgujrati** [comment]
@nitin10s please review

**Comment by aayush-05** [comment]
The modal looks a bit empty, maybe decrease its size a little. Or whatif we provide the modal-top section a green background and make the text color white. @harshgujrati

**Comment by harshgujrati** [comment]
Yes it will look great, i will update it @aayush-05

**Comment by harshgujrati** [comment]
If we will update modal here, we will have to update it in example page too for consistent style shall i update that too @nitin10s

**Pull request closed without merging**
