### PR TITLE
feat: integrated tagsinput for project tags

### LINKED ISSUE #2739: No profile dropdown on Group page
**Describe the bug**
Clicking on profile name on Group page does not trigger the dropdown

**To Reproduce**
1. Create a group
2. On the group page, click on your profile name on top right

**Expected behavior**
Must have a dropdown
Screenshot from 2021-12-25 12-04-49

### LINKED ISSUE #2798: feat: integrating tagsinput in Project Tag List
**Is your feature request related to a problem? Please describe.**
We have integration of tags input in some of textarea, integrating with project tag list will enhance UI.

**Describe the solution you'd like**
Integrate tags input using Stimulus

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by vedant-jain03**
Fixes #2798 

#### Describe the changes you have made in this PR -

- Added Bootstrap Tagsinput using stimulus in Project.

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/76901313/149915186-3ec26420-2cfb-42c7-80b7-2842101ee56a.mp4

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@tachyons 
I have imported bootstrap, jquery globally, and as a result dropdown is working fine for every page for using stimulus controller.
Kindly Review

**Comment by vedant-jain03** [comment]
@tachyons 
I tried for group page dropdown the problem is when we try to import 'bootstrap' in the controller, navbar bootstrap becomes inactive and as a result, the dropdown is not showing. I tried some hacks by overriding files but somewhat how another problem is arising. So I think the best we can do is once write function for dropdown in connect() so that other controllers + initial+ dropdown works fine.
Although it was my solution, if someone have something in their mind, it would be really helpful.

**Comment by vedant-jain03** [comment]
@tachyons Kindly review.

**Comment by tachyons** [comment]
we dropped bootstrap tags input

**Pull request closed without merging**
