### PR TITLE
adding some style to contribute page

### PR DESCRIPTION
**Pull request by mahmodHammad**
#### Describe the changes you have made in this PR -
#1096 
- animate hovering on buttons 
- adjust white spacing at phone screens 
-  putting box-shadow at some element  
- sinking effect on hovering over some elements 

##### **Before** changes it looked like this  on desktop screens : 
before pc

#### After changes on desktop screens : 
bef pc

**with animations : **
hoverContribute

##### Before on phone screens : 
before ph

### After changes on Phone screens : 
bef ph

### CODE REVIEW

**Comment by mahmodHammad** [comment]
@tachyons  @nitin10s  @satu0king 
review please :)

**Comment by aayush-05** [comment]
You can only fix the white spacing change for now. Rest UI is according to prototype and a hover effect is already present on the cards.

**Comment by mahmodHammad** [comment]
@nitin10s @aayush-05

what changes can i made to make it merge-able ?
what if i removed the hovering effect from unclickable divs ?

**Comment by mahmodHammad** [comment]
@aayush-05 
could you please explaing this to me 
 " Rest UI is according to prototype and a hover effect is already present on the cards."

**Pull request closed without merging**
