### PR TITLE
changed no dp default.img

### PR DESCRIPTION
**Pull request by abstrekt**
New PR for #1181
Describe the changes you have made in this PR -

*   changed the no dp default.jpg

##Screenshot After:
Firefox_Screenshot_2020-03-21T10-39-32 046Z

### CODE REVIEW

**Comment by abstrekt** [comment]
@nitin10s

**Comment by nitin10s** [comment]
Please attach screenshots here as well.

**Comment by abstrekt** [comment]
> 
> 
> Please attach screenshots here as well.

done.

**Comment by abstrekt** [comment]
this would cause no problem, the purpose of this PR is that the default no dp image was pixelated, & looked bad, this no dp is actually square, looks circular because of transparent edges, if the css on #1208 is set right, this should look the same merging both the PRs, maybe a conflict may arise, which can be fixed.

**Comment by abstrekt** [comment]
In short, this PR changes the default image when no dp is set, #1208 changes the DP shape to be circular @nitin10s

**Comment by abstrekt** [comment]
## screenshot of old default.jpg


Screenshot_2020-03-22-22-31-35-61~01

**Comment by abstrekt** [comment]
@nitin10s  it just changes:
image
to:
Default

**Comment by aayush-05** [comment]
We cannot set the image height to auto, the user can upload big size images which will try to take up complete space for its dimensions then.

**Comment by abstrekt** [comment]
No there is a width mention somewhere @aayush-05

**Comment by aayush-05** [comment]
Imagine a user uploads an image of 300*150 dimensions

**Comment by abstrekt** [comment]
> 
> 
> Imagine a user uploads an image of 300*150 dimensions

I made a rollback,  #1208 was addressing aspect ratio, this PR is intended only for the binary files.

**Comment by aayush-05** [comment]
@abstrekt can you add the code alongwith, just a little condition to use these binary files in case of no profile picture

**Comment by abstrekt** [comment]
> 
> 
> @abstrekt can you add the code alongwith, just a little condition to use these binary files in case of no profile picture

it is already there, since before!

**Comment by aayush-05** [comment]
Ah, got it. My bad!

**Comment by nitin10s** [comment]
@aayush-05

**Pull request merged**
