### PR TITLE
[GCI] Move user authorization methods to policy, with tests

### LINKED ISSUE #663: Move authorisation methods from User model
Move check edit_access, check_view_access, and check_direct view access to pundit authorization layer

### PR DESCRIPTION
**Pull request by junron**
Fixes #663 

#### Describe the changes you have made in this pr -
Move authorization methods from user model to project policy.
Includes tests to ensure no decrease in coverage.

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/6229590968631296/)

### CODE REVIEW

**Comment by junron** [comment]
@tachyons Please review. At least the files changed have 100% coverage.

**Comment by fluctix** [comment]
Can you also add tests to check of.user has edit açcess after deadline passed , in other words test related to assignment submission

**Comment by junron** [comment]
Excellent idea! I think that's possible.

**Comment by junron** [comment]
@tachyons I have implemented the tests @fluctix suggested.

**Comment by junron** [comment]
@tachyons What do you think

**Comment by junron** [comment]
@tachyons Coverage is now in the green!

**Comment by junron** [comment]
@tachyons Please review

**Pull request merged**
