### PR TITLE
Add watermark to downloaded circuit image

### PR DESCRIPTION
**Pull request by mohammedsafwat**
I have added a light grey watermark that's saying "Made with CircuitVerse" at the bottom of any circuit image that will be exported.

### CODE REVIEW

**Comment by mohammedsafwat** [comment]
@satu0king Thank you so much for pointing this out to me and explaining the issue in more details! I'll update the pull request again with my new changes.

**Comment by armudgal** [comment]
Hey @mohammedsafwat, do we have any update on this, thank you.

**Comment by armudgal** [comment]
@satu0king Safe to close this PR I guess.

**Comment by mohammedsafwat** [comment]
> Hey @mohammedsafwat, do we have any update on this, thank you.

@armudgal Very sorry for my late reply! I worked on some improvements but unfortunately, I didn't have the chance to review them and create a pull request. But for now, I guess it's safe to close this PR too.

**Pull request closed without merging**
