### PR TITLE
Add activity notification library

### LINKED ISSUE #243: Notification for users.
**Is your feature request related to a problem? Please describe.**
with commontator subscriptions, mentions, upvote, downvote, and groups it's important to make a system to notify the user about these inside the website.  

**Describe the solution you'd like**
 A notification system similar to GitHub would just be a perfect solution but we can start with just a basic notification option in navbar which can show us our notifications from notification table in which we can push whenever any group invite is sent or any comment mention is made.

**Describe alternatives you've considered**
I looked into [notifications](https://github.com/rails-engine/notifications) gem which seems a decent enough option I am looking for a better alternative though.
 
**Are you working on this? (Yes/No)**
If you guys think this is the right time to implement this feature I can start working on this.

### PR DESCRIPTION
**Pull request by junron**
Fixes #243 

#### Describe the changes you have made in this pr -

- [x] Added [activity notification](https://github.com/simukappu/activity_notification) library
- [x] Added notification for starring project
- [x] Added tests
- [x] Link to notifications page
- [x] Web push
- [ ] Icon for web push

### CODE REVIEW

**Comment by tachyons** [comment]
Thanks for this, We skipped this task from GCI because this is relatively hard task, If you are confident that you can do that, then we can add this task in GCI tasks list

**Comment by junron** [comment]
I think it is quite manageable for students. I'll be working on it even if it's not in GCI

**Comment by junron** [comment]
@tachyons For web push notifications, a PNG icon is required. However, there are many icons in the repo but none are PNG format. Could you direct me which one to use?

**Comment by tachyons** [comment]
Can you resest the target branch to stories/new_ux ? All ui changes should go there

**Comment by junron** [comment]
Ok so hopefully this comment won't be buried under mountains of spam.

I have implemented the activity notifications and web push notifications
Demonstration video:
output
[MP4 on google drive](https://drive.google.com/open?id=162zJd4RKtAcwKtOQe0SinsGtNZW5TaV2)

Users enable browser notifications by visiting the Notifications page and clicking enable. The browser will ask them for permission and if granted, generate encryption and authentication keys, as well as a cloud endpoint for sending notifications to the device, which are sent to the server and stored in the database. This process needs to be repeated for every device that the user wants to receive push notifications on. The user can then click the test button to send a test notification to itself.

The server also needs to identify itself to the browser's cloud push notification endpoint. It does this by generating a public/private key pair. You can do this by running `Webpush.generate_key` in the rails console:
```
$ rails console
Running via Spring preloader in process 8655
Loading development environment (Rails 6.0.1)
[1] pry(main)> Webpush.generate_key
=> #<Webpush::VapidKey:2ab51f32dbe8 :public_key=BAAS5N5HuL4ElT1hBU1ZdGfRrXq1Ja90gOR7IjwZXfSU4ZfogrIMVtnerHgsI2TLoidFPSH32_H89thI1l9Rdn4= :private_key=XPwmYJgtRybLJDWXNKIDVOdgXQzJzl0Uj29sw_52Bwo=>
```
These keys need to be exposed to the application by setting the following environment variables:
- `VAPID_PUBLIC_KEY`
- `VAPID_PRIVATE_KEY`

One final step is to add the icon for the push notifications. Currently, I did not specify an icon, so it defaults to the browser logo (in chrome at least). Please advise as to which image to use for the icon.

Ping @tachyons

**Comment by junron** [comment]
As for test coverage, I am working on a test for a controller, but I'll delay pushing it to avoid another avalanche of spam

**Comment by junron** [comment]
Yay all tests pass now!

**Comment by junron** [comment]
@tachyons Please review

**Pull request closed without merging**
