### PR TITLE
Touch compatibility UI (For smaller devices)

### PR DESCRIPTION
**Pull request by ZadeAbhishek**
This PR is for New UI designed For CircuitVerse website Small screen version
This PR is created on the top of my first PR which is touch compatibility in which touch functionality is ad to CV.

### Following things are changed for smaller screen
1.Circuit Element (Redesigned)
2.Properties panel (Redesigned)
3.Time Diagram (Redesigned)

### Following new things are added in this PR for smaller screen
1.Touch button menu 
2.Live button (Fit to screen, Undo, Delete)
3.Quick menu 
4.NavMenu for the small screen 
5.Portrait mode

## Before 
Screenshot_20210728-062910_Chrome
## After
1_rqvNcGdTxx5_zHLIOkv1Bg
1_bnZl3VS4KPA6wRyac4wLmw
1_W_P9nIB3H8A8CyYwyS40fA
1_DBZCYI-FkP_yZJcVNtajqg
NamvmenuAbhishekZade
## UI to lock portrait Mode
potraitlockAbhishekZade

### CODE REVIEW

**Review by nitin10s — CHANGES_REQUESTED** [review]
The menus have a lot of UI problems. 

1. 
image
should look exactly like 
image
In place of the "- (minimize icon)" at the top right, add a cross icon to close the menu.

2. Can you post screenshots to the other two menus so I can specifically point out what to fix.

3. The quick menu options - we'll need to completely redesign, I'll take that up and share the design.

4. The selected menu appears green which looks very bad, could you change it something following each theme, (for instance, in the current theme orange or bg color=orange,icon color=dark theme color might look better). Please schedule a call with me if you'd like to discuss the different color themes

5. The stroke size of each icon is too much, please reduce that, where did you download them from?

6. Is it possible to change the design of these icons?
image They look exactly the same as the main four icons on the right. Try bgcolor=darkgrey, icon color=white maybe.

7.  Remove the orange outline from the hamburger menu icon on the top right

8. Remove the extra padding below Main. It looks odd.
image

9. UI to lock portrait Mode. I'll design something for that as well.

**Review by abstrekt — CHANGES_REQUESTED** [review]
List of things to look for when testing on an actually mobile device:

- [ ]  **Zooming of canvas*****
    - This would be the most used thing when building/viewing circuits on a touch device, it is very important to get this right for release.
    - **Current behaviour:** When doing a pinch to zoom its very hard to tell where it's zooming from or where it is zooming to, user decides which point to zoom to in a large circuit by placing their fingers at the required point.
    - **Desired behaviour:** Pinch to zoom to occur from the point of fingers. Please refer how it works for similar such web apps. (eg. try [excalidraw.com](http://excalidraw.com) on mobile)

- [ ]  **Layout: Test your layout on a few actual devices, actual device will have the browser's app bar that will take up some part of the resolution - be cautious to consider it.**

    on browser dev view:

   
image


    on actual device:

image


- [ ]  **Panels:**
    - lost original layout/styles, please compare both the images, layouts between the range inputs, theme styles like border , background, width, etc are all lost
    - Make sure at-least consistent behaviour is among all the panels, dialogs, buttons — all elements in general
    - Doesn't matter if they are not except as the original version just make sure experience wise it fits common standard.
    - Check arrow is not pointing to the right option.

   image

image

- [ ]  **No elements shouldn't go out of viewport**
    - Even if the content inside are scrollable - make sure the wrapper element stays in the viewport and contents are scrollable within that wrapper.
    - 

  image

- [ ]  **Any toast, notifications, alerts should be aligned away from the center**

  image

- [ ]  **Everything should be accessible**
    - Notice the element tooltip, there's no point to have this if user can't read this.

 image

    - Check every options, features, menus, popovers, etc, of the application, here the button to apply the theme is inaccessible, similar problem in other sections as well.

image

    image

    - Make sure to provide proper layout to  everything that needs a responsive layout

- [ ]  **Inconsistent sizes -**
    - This menu in particular is way bigger than everything, and is actually non-standard,
    - please check consistency in regards to font sizes, icon sizes, layout, width, height, ratios,

image

Note: Please test out everything in the application in an actual device, test for functionality, accessibility, experience, layouts, corner cases, even if most of the UI is the same as the desktop version, that UI wasn't made having mobile devices in mind, thus many inconsistencies may occur, things may seem off, or broken, better to test everything well one at a time!

**Comment by abstrekt** [comment]
^ Gave one round of review, please let me know if you want to schedule a call @ZadeAbhishek , will check again after you look at these!

**Comment by ZadeAbhishek** [comment]
@abstrekt @nitin10s changes are done please give a review on this one 
following changes where made 
Screenshot_20210804-155408_Chrome
Screenshot_20210804-155415_Chrome
Screenshot_20210804-155421_Chrome
Screenshot_20210804-155428_Chrome
Screenshot_20210804-155435_Chrome
Screenshot_20210804-155457_Chrome
WhatsApp Image 2021-08-04 at 4 06 43 PM

https://user-images.githubusercontent.com/66520848/128167258-c78d0ee2-4748-45ae-981a-232832716833.mp4

**Review by nitin10s — CHANGES_REQUESTED** [review]
Check these images. Look out for the red arrows for errors

image
image
image

The navbar still needs a redesign, I am working on it.

**Review by nitin10s — CHANGES_REQUESTED** [review]
Potrait lock
Here is how the portrait lock should look

**Comment by ZadeAbhishek** [comment]
In the below video,  shows changes in animation that I have done 
Uploading Image from iOS.MP4…

**Review by nitin10s — APPROVED** [review]
Please update the screenshots everywhere

**Review by ShreyaPrasad1209 — APPROVED** [review]

**Comment by tachyons** [comment]
Please make static code analysers happy, you can skip once "Cognitive complexity" and "similar codes" issues

**Comment by ZadeAbhishek** [comment]
@tachyons on it

**Comment by tachyons** [comment]
This is now implemented, right?

**Pull request closed without merging**
