### PR TITLE
Update footer.scss

### LINKED ISSUE #3516: Copyright line align at the center
**Describe the bug**
The copyright line at the end of the webpage should be align at the center it is not looking so good

**To Reproduce**
1. Go to 'https://circuitverse.org/'
3. Scroll down to the end of the webpage
##ERROR
image

**Expected behavior**
The copyright line should be align at the center so it would be look better

**Screenshots**
circuitverse

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [e.g. chrome]

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by chiggshiggs**
Fixes #3516

### Screenshots of the changes (If any) - 

Screenshot from 2023-02-05 00-47-13

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
@chiggshiggs I find the initial design better, let's wait for @Prerna-0202

**Review by vedant-jain03 — CHANGES_REQUESTED** [review]
I find the initial design better, let's wait for @Prerna-0202

**Comment by Prerna-0202** [comment]
> I find the initial design better, let's wait for @Prerna-0202 

@vedant-jain03, There is already an earlier pr(#3520) for this issue. I think we should consider that one.

**Comment by vedant-jain03** [comment]
> > I find the initial design better, let's wait for @Prerna-0202
> 
> @vedant-jain03, There is already an earlier pr(#3520) for this issue. I think we should consider that one. And I also think that the initial design is better.

Yes, closing this...

**Pull request closed without merging**
