### PR TITLE
fix illustration issue in login and sigup

### LINKED ISSUE #1026: No illustration for mobile view in Login & Sign-Up [New UX]
**Describe the bug**
In the new_UX,
The mobile view of Login and Sign-Up should not have the illustration that is present in the Desktop View.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Login/Sign-Up on a mobile device

**Expected behaviour**
No illustration to be shown in the mobile view.

**Screenshots**
login

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by rishipurwar1**
Fixes #1026 

In mobile view, illustration and descriptive text doesn't show now

finallog
finalsign

### CODE REVIEW

**Comment by rishipurwar1** [comment]
please review my pr @aayush-05

**Comment by aayush-05** [comment]
I wonder why so many changes. I think it just requires you to add two bootstrap classes to the existing divs.

**Comment by rishipurwar1** [comment]
Please tell me what should I do right now to make it better? @aayush-05

**Comment by darkshredder** [comment]
Change div like the screenshot i m showing
Screenshot 2020-03-07 at 12 52 21 AM

Screenshot 2020-03-07 at 12 48 47 AM

**Pull request closed without merging**
