### PR TITLE
fix My Circuits page 

### LINKED ISSUE #1205: My circuits section is broken at phone screens
**Describe the bug**
My circuits section is broken at phone screens 

**To Reproduce**
1. Go to https://circuitverse.org/users/18462

**Screenshots**
image

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #1205

#### Describe the changes you have made in this PR -
* adding more white space 
- align items to center

### After:
profile after-ph5

### before:
image

### CODE REVIEW

**Comment by mahmodHammad** [comment]
YUP i i made an other PR to make it rounded else where #1208

https://github.com/CircuitVerse/CircuitVerse/pull/1207#issuecomment-599783819
@nitin10s

**Comment by mahmodHammad** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1207#pullrequestreview-376176691
 Ther's a problem at login on local sever so i'am not able to take screen shots at large screens 

#### It looked Like this 
- I only Changed the upper section on (RED) aligned to center and looks the same with more comfortable looking as i increased the white space little bit

image

**Comment by mahmodHammad** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1207#pullrequestreview-378895926
@nitin10s 
i am not able to log in on my machine to see this page , so i will fix it as soon as possible 
 , also if you could send a screen-shot with the broken parts i will appreciate that a lot

**Comment by nitin10s** [comment]
FireShot Capture 206 - nitin - Circuits_ - 3000-e4e22eb2-7fa0-47c8-a9a4-5729ff8d99e2 ws-ap01 gitpod io
Here you go.

**Comment by mahmodHammad** [comment]
@nitin10s  
OMG ! 
it didn't look like this while i was working on it 
so excuse me please for that , i will fix it as soon as possible 

## i think that it's somehow fixed now as this image below
image
### ,so  i will close it now  ,and please let me know if you liked that little modifications i did  ,because i will make a cleaner PR with this changes in UI if you approved

**Comment by mahmodHammad** [comment]
please inform me if you liked that changes in UI

**Pull request closed without merging**
