### PR TITLE
Finalise project details page

### PR DESCRIPTION
**Pull request by aayush-05**
**Screenshots**
**Own User Project**
1.
image
2.
image
3.
image
4.
image
5.
image
6.
image
7.
image
**Other User Project**
1.
image
2.
image
3.
image
**Non-Logged In User**
1.
image
Update:
image

### CODE REVIEW

**Comment by aayush-05** [comment]
@nitin10s please have a look

**Comment by aayush-05** [comment]
@nitin10s could you please check again. The bugs you specified (except the star icon) are the ones present in the current master branch. I resolved them already in the PR.

**Comment by nitin10s** [comment]
Yes I know they are in the current master branch. But they need to be resolved as well.

**Comment by nitin10s** [comment]
I checked your PR in gitpod and it doesn't show the changes (if you've made them). Will check again maybe.

**Comment by aayush-05** [comment]
Yes please, let me know if they don't show up

**Comment by nitin10s** [comment]
There seems to be a problem, when I open circuits from Recent/Featured, the new styles [Yellow Star Icons, Tag Design] doesn't seem to get applied.

**Comment by aayush-05** [comment]
It won't work with the Featured section since that actually reedirects to the main website. But should work with the recents one, please check once again with that. Else we can get a call and can get it reviewed then?

**Pull request merged**
