### PR TITLE
Fixes close cross removal on name change

### LINKED ISSUE #1300: close cross removes on changing circuit name
**Describe the bug**
when trying to change circuit name close cross dissapears

**To Reproduce**
1. Go to 'simulator'
2. Scroll down to 'circuits in properties > right pane'

**Expected behavior**
close cross should remain there and perform same function

**Screenshots**
ncuts1 1

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Version 80...

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by krishanu-2001**
Fixes #1300

Fixes issue causing close cross to remove on changing name of circuit
#### Describe the changes you have made in this PR -
fixed above bug by changing function changeCircuitName() in public/data.js
### Screenshots of the changes (If any) -
ncuts1 2

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by krishanu-2001** [comment]
Yes I would also like to hear your views on this here's screenshot to compare
ps1
ps2

**Comment by krishanu-2001** [comment]
sure

**Comment by Ananthavijay** [comment]
@krishanu-2001 Update the description to ````Fixes #<issue_no>````

**Comment by krishanu-2001** [comment]
done

**Comment by satu0king** [comment]
I believe this is Merged in another PR

**Pull request closed without merging**
