### PR TITLE
fixed Social Media links looks dull without hover effects in Login page

### LINKED ISSUE #1038: Social Media links looks dull without hover effects in Login page
**Is your feature request related to a problem? Please describe.**
Social Media links looks dull without hover effects in Login page

**Describe the solution you'd like**
Add hover effects to it

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by darkshredder**
Fixes #1038 Social Media links looks dull without hover effects in Login page

#### Describe the changes you have made in this PR -
Added Hover effect on social media links

### Screenshots of the changes (If any) -
ezgif com-video-to-gif (8)

### CODE REVIEW

**Comment by darkshredder** [comment]
@nitin10s @tachyons  @aayush-05

**Comment by darkshredder** [comment]
@nitin10s @tachyons  @aayush-05

**Comment by aayush-05** [comment]
I think these are unrelated changes @darkshredder 
image

**Comment by darkshredder** [comment]
@aayush-05  sorry I merged that by mistake
@tachyons  you can merge this now

**Pull request merged**
