### PR TITLE
Added deploy to heroku button in setup.md

### PR DESCRIPTION
**Pull request by Ananthavijay**
### Describe the changes you have made in this PR -
- Added deploy to Heroku button in setup.md

### Sample deployment - http://cvtestexample.herokuapp.com/

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@tachyons @satu0king Please review

**Comment by yash15601** [comment]
working  well @Ananthavijay 😄

**Comment by Ananthavijay** [comment]
So should I document the steps to generate secret and tell the user to add it in the app.json?

**Comment by Shivansh2407** [comment]
True @tachyons.@Ananthavijay you can take a look at this link for help. https://gist.github.com/derzorngottes/3b57edc1f996dddcab25

**Comment by Ananthavijay** [comment]
I have made some changes @tachyons Please review

**Comment by Ananthavijay** [comment]
Currently, Heroku runs CV on the production server, should I change it to run on development server? so that these secrets are not needed.

**Comment by tachyons** [comment]
No, it must be in production mode, but let the user to enter env instead of hardcoding them

**Comment by Ananthavijay** [comment]
@tachyons Please review

**Comment by Ananthavijay** [comment]
@tachyons Please review

**Comment by tachyons** [comment]
Amazing :tada:

**Pull request merged**
