### PR TITLE
Added db_consistency_checker gem

### PR DESCRIPTION
**Pull request by shyam1210**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/3703

#### Describe the changes you have made in this PR -

1. Added database_consistency gem in gem-file from source : https://github.com/djezzzl/database_consistency
2. Added `.database_consistency.yml` file with configurations for database checker.
3. Disabled all checks which are failing now, so that they can be taken up later and fixed.
4. Added a new workflow `database_checker` to Github actions for running the check on push, pull_request and workflow_dispatch

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tachyons** [comment]
Could you address the CI failures, it seems to be due to missing database.yml file

**Comment by shyam1210** [comment]
> Could you address the CI failures, it seems to be due to missing database.yml file

@tachyons Corrected

**Comment by tachyons** [comment]
Great 👍, I think we can disable the rules which are currently failing so that we can fix those incrementally in separate issues. 

Also WDYT about moving this into separate workflow ?

**Comment by shyam1210** [comment]
Moved to a different workflow. Disabled all check which are failing now. We can take them as separate fixes later.
cc: @tachyons

**Review by tachyons — APPROVED** [review]

**Pull request merged**
