### PR TITLE
Renamed Fork as Create Copy

### PR DESCRIPTION
**Pull request by nikitachauhan5499**
Fixes #

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by ryuk156** [comment]
@nikitachauhan5499 Before  you push your code make sure that you have created a branch of your main repo don't make changes in the main repo try to create a branch and then make changes now you can push your code

**Comment by nikitachauhan5499** [comment]
> @nikitachauhan5499 Before you push your code make sure that you have created a branch of your main repo don't make changes in the main repo try to create a branch and then make changes now you can push your code

Thankyou @ryuk156 :)

**Comment by satu0king** [comment]
Has this been discussed somewhere? We are using fork as its an accepted convention on several websites including github, Codepen etc

**Comment by satu0king** [comment]
Closing this PR because it is a subset of #2109. Thanks!

**Pull request closed without merging**
