### PR TITLE
fixes: #2860 Added tooltip for the social icons in footer

### LINKED ISSUE #2860: Tooltip in the footer for social icons
**Describe the bug**
In the footer when we hover on the social icons the tool-tip is not present there .

**To Reproduce**

1. Scroll down to footer
2. hover on the social icons'
3. See error

**Expected behavior**
To display tool-tips

**Screenshots**

Screenshot from 2022-01-30 01-20-04

**Are you working on this issue? (Yes/No)**
yes

### PR DESCRIPTION
**Pull request by aashimawadhwa**
Fixes #2860

#### Describe the changes you have made in this PR -
Added tooltip for the social icons in the footer.

### Screenshots of the changes (If any) -

ezgif com-gif-maker

### CODE REVIEW

**Comment by Palaksharma23** [comment]
@aashimawadhwa please fix the codeclimate issues.

**Comment by aashimawadhwa** [comment]
@prena-0202 @vedant-jain03 
can you please review the PR and approve the workflow .

**Comment by vedant-jain03** [comment]
@aashimawadhwa thankyou for raising a PR and sorry for replying late. It looks good to me.
Lets wait for @gr455 @tachyons reviews.

Keep contributing 🎉

**Review by Prerna-0202 — APPROVED** [review]
LGTM

**Comment by aashimawadhwa** [comment]
@vedant-jain03 @gr455 please review and merge it .

**Review by gr455 — APPROVED** [review]
Thanks for this!

**Pull request merged**
