### PR TITLE
Replaced window.location.href with anchor tags

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #https://circuitverse-team.slack.com/archives/CQ17325A5/p1584948288000800?thread_ts=1584948288.000800

#### Describe the changes you have made in this PR -
I have replaced window.location.href with a href tags.

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@satu0king Please Review and Merge 👍

**Comment by aayush-05** [comment]
@Shivansh2407 can you please fix the merge conflicts ?

**Comment by tachyons** [comment]
Can you check compatibility in both firefox and chrome

**Comment by Shivansh2407** [comment]
Sure @tachyons . I will check and let you know soon 👍

**Comment by Shivansh2407** [comment]
It is working fine for me @tachyons. Please let me know your views 👍

**Comment by nitin10s** [comment]
@aayush-05

**Comment by aayush-05** [comment]
We can maybe close this one. I have changed all the links in their respective PRs

**Pull request closed without merging**
