### PR TITLE
feat: integrating prettier

### LINKED ISSUE #1422: integrate prettier for improving code quality
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
To integrate prettier to improve code-quality
**Describe alternatives you've considered**

**Additional context**

**Are you working on this? (Yes/No)**
yes

### PR DESCRIPTION
**Pull request by himanshu010**
Fixes #1422 

#### Describe the changes you have made in this PR -
Integrate prettier and add code to ignore the non-important files
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by himanshu010** [comment]
working on ci

**Comment by himanshu010** [comment]
CI is green now.

**Comment by himanshu010** [comment]
@satu0king @tachyons @nitin10s
review this, please!

**Comment by satu0king** [comment]
@shubhankarsharma00  you will have to be doing this as part of refactoring

**Comment by tachyons** [comment]
Prettier and eslint can have conflicting rules of not properly configured. Also I don't see much value in applying prettier in existing code which will make merge conflict for every other PRs

**Comment by himanshu010** [comment]
But eslint is showing tons of error while fixing the code quality.

Screenshot (106)

**Comment by himanshu010** [comment]
How about changing the default formatter to prettier?
What are your views on this @satu0king @tachyons @nitin10s

**Pull request closed without merging**
