### PR TITLE
Issue no #817

### LINKED ISSUE #817: A custom context menu for the elements in side-bar.
**Is your feature request related to a problem? Please describe.**
Right now we display little info about the tool we hover on but I purpose an option to view more information about the tool from the context menu.   

**Describe the solution you'd like**
A custom context menu with an option of more info that redirects to the docs page.
 
**Are you working on this? (Yes/No)**
GCI

### PR DESCRIPTION
**Pull request by jha11aditya**
Fixes #817
A custom context menu for the elements in side-bar.
#### Describe the changes you have made in this pr -
I added a on click function to CircuitVerse tip button in properties menu,now when clicked it goes
to the specific help page in Circuitverse docs

### CODE REVIEW

**Comment by shubhankarsharma00** [comment]
@jha11aditya squash the commits and maybe show an :information_source:  icon in the tip so people know that additional info is available.

**Comment by thiefie** [comment]
1)It seems you are trying to merge from master. Though it's ok to have it as such , it might cause issues in the future.
Perhaps it would be better if you create a new branch.

2)Maybe you could make the title more descriptive & concise and instead you could link the issue in the issue description, like `Fixes #817 ` . 

3)Squash the commits

Apart from that everything is fine imo

**Comment by jha11aditya** [comment]
i created a new branch and created the pull request [ Added help #847 ] with better describing changes made .
I tried to squash commits but it didn't squash.

**Comment by jha11aditya** [comment]
Yes i squashed it in  pull request #847

**Comment by jha11aditya** [comment]
And i squashed it here also

**Comment by jha11aditya** [comment]
should i remove this pulls request as there are now 2 pull reqest [#843 & #847 ] for the same issue
as you told to make a different branch.

**Comment by jha11aditya** [comment]
created another  pull request #847 for this feature with separate branch.

**Pull request closed without merging**
