### PR TITLE
Clear Circuit Popup

### LINKED ISSUE #848: Clear circuit function should have popup asking if you're sure
The clear function clears the circuit without asking if you're sure. This way a misclick can almost be fatal to your progress.

**Additional context**
I have almost lost a whole computer circuit to this, so please add this. The only ways to recover the circuit are to luckily have a recent offline save or go to your circuits and reopen the project.

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #848 

#### Describe the changes you have made in this pr -
I have added a Popup , confirming which the clearproject() function will clear the project.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Please add screenshots in all your PR's @Shivansh2407

**Comment by Shivansh2407** [comment]
Cap1
Cap2
Cap3

These are the screenshots of the commits done.

**Comment by Shivansh2407** [comment]
@Ananthavijay Added the screenshots and also Changed the Text in the PopUp

**Comment by Shivansh2407** [comment]
Please review @satu0king.

**Comment by Shivansh2407** [comment]
@tachyons Please review this and merge 👍

**Comment by Shivansh2407** [comment]
@tachyons Please review this.

**Comment by Shivansh2407** [comment]
@tachyons Please review and merge 👍

**Comment by Shivansh2407** [comment]
@satu0king Please review 👍

**Comment by Shivansh2407** [comment]
@satu0king please review this PR and merge 👍🏻

**Comment by satu0king** [comment]
Sorry for the delay.

**Comment by Shivansh2407** [comment]
No problem 👍. Thank you @satu0king.

**Pull request merged**
