### PR TITLE
fix(container): notification container fixed

### LINKED ISSUE #4042: 🐞 Bug:notifications not properly fitted in container
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the notifications are not properly fitted inside the notification container

### Steps To Reproduce

1.go to notification section by clicking the bell
2.see your notification 

### Expected Behavior

properly fitting of notification inside the container

### Screenshots

.
.
.
Screenshot (279)

should be like this......
.
.
.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #4042

### Screenshots of the changes (If any) -

Screenshot (315)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@VaibhavUpreti done sir please have a look on the pr

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @vedant-jain03 @tachyons please review

**Review by tanmoysrt — APPROVED** [review]
Looks fine !

**Comment by harshsharma-11** [comment]
@vedant-jain03 @VaibhavUpreti please review

**Comment by niladrix719** [comment]
@harshsharma-11 why you closed this , are you not working on this anymore

**Comment by harshsharma-11** [comment]
as i delete my head repository so all pr's get closed due to this ,so i am no longer working on this

**Comment by harshsharma-11** [comment]
as i unknowly deleted the head repo so all pr's relative to this gets  automatically closed ,new pr is #4244

**Comment by niladrix719** [comment]
@harshsharma-11 you could have just restored the branch

**Comment by harshsharma-11** [comment]
> @harshsharma-11 you could have just restored the branch

how??????????

**Pull request closed without merging**
