### PR TITLE
[GCI] Add rake task for migrating to paperclip table records activestorage

### LINKED ISSUE #371: Migrate from PaperClip to Active Storage
**Is your feature request related to a problem? Please describe.**
Paperclip is [deprecated](https://thoughtbot.com/blog/closing-the-trombone)

**Describe the solution you'd like**
Follow this migration [guide](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md)

**Are you working on this? (Yes/No)**

No

### PR DESCRIPTION
**Pull request by junron**
Fixes #371 

#### Describe the changes you have made in this pr -
Added rake task to migrate information in paperclip generated tables to active storage.

#### Usage:
1. Merge #753 (this PR)
2. Run `rails db:migrate`
3. Run `rake activestorage:migrate`
4. Merge #730 
5. Run `bundle install` 
6. Run `rake activestorage:migratefiles`

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/6505098130227200/)

### CODE REVIEW

**Comment by satu0king** [comment]
We need this for AWS migration.

**Comment by satu0king** [comment]
@tachyons Can we use this PR directly?

**Comment by tachyons** [comment]
Not as standalone fix

**Comment by VaibhavUpreti** [comment]
Completed via https://github.com/CircuitVerse/CircuitVerse/issues/3764 & https://github.com/CircuitVerse/CircuitVerse/pull/3984

**Pull request closed without merging**
