### PR TITLE
Footer social icon hover#2149

### LINKED ISSUE #2149: Add hover effect to social icons
**Is your feature request related to a problem? Please describe.**
Add hover effect to social icons in footer section.

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Kartikay304**
Fixed #2149 

Added a bounce-out-on-hover effect on social  icons

Screenshot-
ezgif com-gif-maker (1)

### CODE REVIEW

**Comment by Kartikay304** [comment]
@ShreyaPrasad1209, can you please review my pull request?

**Review by ShreyaPrasad1209 — APPROVED** [review]

**Comment by gr455** [comment]
@ShreyaPrasad1209 If everything is good on this PR, can you merge it?

**Comment by Palaksharma23** [comment]
Is this pr merged ? 
Or can i start working on this project .

**Review by nitin10s — APPROVED** [review]
Looks good to me @ShreyaPrasad1209

**Pull request merged**
