### PR TITLE
User's Settings

### LINKED ISSUE #849: User settings/preferences
**Is your feature request related to a problem? Please describe.**
Circiutverse is a growing platform and lack of any way to customize its behaviour by users is starting to make problems. For an example implementation of new emails system or GDPR compliance are impossible due to lack of settings. 

**Describe the solution you'd like**
Create a new settings page on `/users/:id/settings` that will match new UX style
The page should contain settings divided into categories. In my opinion, hard-coding options and adding them to the database is a bad decision. I think options should be generated via a configuration file in JSON for example:
``` JSON
{
	"name" : "fork-button",
	"display_name" : "Hide fork button on project pages",
	"category:" : "Platform"
}
```
That implementation will make settings harder to implement but will benefit in the future. Settings page should be generated via this JSON file. At database, settings can be put into one array cell. The main values like `Username` `Email` `Password` etc. should be hard-coded cause they won't be changed at all. Also, all settings can should be represented as an object.

The settings should be accessible from the user's dropdown

image

**Example fields in configuration**

Account

* Username
* Download your information (GDPR)

Email

* Receive Emails (main checkbox)
* Receive Newstsleller emails (checkbox)
* Receive fork notification emails (always, only milestones, off)
* Receive star notification emails (always, only milestones, off)
* Recieve emails when your circuit is featured (checkbox)

Platform

* Might be used in the future

Security

* Change Password
* 2FA
* Sign out of all other sessions
* Delete account (GDPR)

**Describe alternatives you've considered**
There are no other possible implementations at all

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by MrBartusek**
Fixes #849

## Describe the changes you have made in this PR
That's quite a huge one, the backend is handled via [typed store](https://github.com/byroot/activerecord-typedstore) gem:
```ruby
# user.rb
typed_store :settings, coder: JSON do |s|
  s.boolean :hide_external_navbar_links, default: false, null: false
end
```
and frontend is handled via `settings.json`
```json
{
    "categories":
    [
        {
            "name": "Platform",
            "description": "Configure overall behavior of the platform"
        },
       ...
    ],
    "settings":
    [
        {
            "category" : "Platform",
            "name" : "Hide external navbar link",
            "description": "Hide <code>Learn</code> and <code>Documentation</code> links.",
            "action":
            {
                "type": "boolean",
                "name" : "hide_external_navbar_links",
                "refreshPage": true
            }
        },
		... 
    ]
}

```
The JSON can handle 2 option types, `button` and `boolean` with the ability to expand. Additionally, settings can use `refreshPage` to refresh the page after changing option and `hidden` to hide option on production. 

> Why would you refresh the page when it is a form?

You may ask, well, that is not. Every setting is updates lively without the need to refresh the page.  Of course, if setting change look of the site that is a good idea to refresh it anyway.

## Screenshots
image

image

ezgif-6-54fc4426da65

## Other changed things
**Added `/501` page for pages that are not implemented currently**

image

**Fixed naming in errors tests** 

tests in `spec/controllers/errors_controller_spec.rb` was badly named https://github.com/CircuitVerse/CircuitVerse/commit/49d1c18610344dd619ebc0bd3223616a1612cb02

## Merging this will open a couple of another issues
* Move `edit profile` intro `settings` (needed to discuss)
* Add functionality to `delete the account` button in settings (currently hidden)
* Add functionality to `download information` button in settings (currently hidden)
* Style settings page (currently it is more of a prototype)

### CODE REVIEW

**Comment by MrBartusek** [comment]
@tachyons please review

**Comment by shubhankarsharma00** [comment]
@MrBartusek I will be refactoring the simulator codebase and updating it to integrate with webpacker. Can we put the default listeners on hold? It will probably be wrapped in 2 months.

**Comment by MrBartusek** [comment]
@shubhankarsharma00 yeah, no problem

**Comment by nitin10s** [comment]
The new navbar will be having a Getting Started dropdown which will hold the Learn and Documentation. Why is "Hide external navbar link" option needed?

**Comment by MrBartusek** [comment]
> The new navbar will be having a Getting Started dropdown which will hold the Learn and Documentation. Why is "Hide external navbar link" option needed?

Didn't know that, that is more a concept, will fix later.

**Comment by nitin10s** [comment]
Yeah, No worries.

**Comment by MrBartusek** [comment]
@nitin10s I don't feel much like thinking about other things to put in settings currently, maybe just merge this for now and I'll just add to issue about adding more settings note that this option need to be removed.

**Comment by nitin10s** [comment]
Can you just remove this option "Hide External Nav Links" please? We'll see what more personalisation we could offer. Option to unsubscribe from the mails can be a good addition.

**Comment by MrBartusek** [comment]
@nitin10s system test depends on it, shall i delete it and add note about it to new issue?

**Comment by MrBartusek** [comment]
@nitin10s I just now thought that it might be a good idea to hide settings till it will be fully working to don't push semi-working features to production. We can just merge it and I will open a couple of new issues about adding more settings to this page etc. For now, I kept this settings just for demonstration because I cannot think about any other setting that will be as good as that to properly test it.

**Comment by nitin10s** [comment]
That would be most ideal, yes. Cool.

**Comment by MrBartusek** [comment]
I didn't mention that but i committed it already :)

**Comment by nitin10s** [comment]
Yeah I saw, @tachyons

**Comment by tachyons** [comment]
Can you please rebase with latest master ?

**Comment by MrBartusek** [comment]
There are still a couple of things to do and fix but, I don't think I want to do it anymore, sorry!
If anyone would want to continue work from there, then go ahead.

**Pull request closed without merging**
