### PR TITLE
Finalise groups page

### PR DESCRIPTION
**Pull request by aayush-05**
1.
image
2.
image
3.
image
4.
image
5.
image

Update:
image

Note: Work done on top of #1461

### CODE REVIEW

**Comment by aayush-05** [comment]
@nitin10s @tachyons please have a look at this

**Comment by aayush-05** [comment]
@nitin10s done, please have a look

**Comment by aayush-05** [comment]
@tachyons merging this one first will break the page. The work is done on top of another PR which itself is on top of another PR. So we have to merge them in order; since the base one have styles required by PRs on top of it

**Comment by tachyons** [comment]
You were supposed to update target branch when having two maintain order of merging, since you targeted this PR to master, I thought changes are already confirmed

**Comment by aayush-05** [comment]
I cannot create branches on the original repo; so the base branch of this PR is actually another PR to this repo but a branch to my fork. Creating a PR targeted to that branch on my fork will make it a PR for my forked repo, not this one. So, I pushed it as a PR targeted to master but on top of another PR. Shall I create PR not ready to merge targeted to any other branch from the existing ones but master?

**Comment by aayush-05** [comment]
@tachyons can we revert this one. Please let me know if I am missing something for settting up the target branch?

**Pull request merged**
