### PR TITLE
added-missing-color-variable

### LINKED ISSUE #1709: Night Sky Theme Not working Properly
**Describe the bug**
The Night Sky Theme in the Tools section on selecting works well, but on refresh it fades all the options on the Navbar.

**To Reproduce**
1. Go to 'beta.circuitverse.org'
2. Click on 'simulator'
3. Apply Night Sky theme and refresh

**Expected behavior**
The Navbar options should remain as it is like in the other themes.

**Screenshots**
Default Theme
image

Night Sky Theme
image

On refreshing the Page
image

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by AkashChetia**
Fixes #1709 

#### Describe the changes you have made in this PR -
Prior to this fix some theme variable was missing due to which night sky theme was not working properly. So, I added that missing variable.

### Screenshots of the changes (If any) -
issue#1709

### CODE REVIEW

**Review by Shivansh2407 — APPROVED** [review]
Working Well @AkashChetia . Keep Contributing 🎉

**Comment by AkashChetia** [comment]
> Working Well @AkashChetia . Keep Contributing 🎉

Thank you such! 
My first FOSS contribution.
Will continue to contribute to the circuitverse.

**Comment by Shivansh2407** [comment]
> > Working Well @AkashChetia . Keep Contributing 🎉
> 
> Thank you so much!
> My first FOSS contribution.
> Will continue to contribute to the circuitverse.

That is really great ! Thank you for contributing to CircuitVerse. Happy Coding 👍

**Comment by Shivansh2407** [comment]
@satu0king Please review the changes and merge accordingly 👍

**Comment by abstrekt** [comment]
@AkashChetia  Nice work,
We're actually planning to reduce the number of color variables & I see that the ```--text-navbar``` variable is consistent throughout all the themes, I mean it's white for all the themes so It'll be better it is removed, can you make the change on this PR?
what you'd have to do is remove the ```--text-navbar``` from all the themes inside the ```themes.js``` file, then from the ```color_themes.scss``` change the rules that were using this variable to just #fff

**Comment by AkashChetia** [comment]
> @AkashChetia Nice work,
> We're actually planning to reduce the number of color variables & I see that the `--text-navbar` variable is consistent throughout all the themes, I mean it's white for all the themes so It'll be better it is removed, can you make the change on this PR?
> what you'd have to do is remove the `--text-navbar` from all the themes inside the `themes.js` file, then from the `color_themes.scss` change the rules that were using this variable to just #fff

@abstrekt sure!

**Pull request closed without merging**
