### PR TITLE
Back Button Works Correctly

### LINKED ISSUE #641: Back button should bring back to the same page.
**Describe the bug**

The back button at <a href="https://circuitverse.org/users/13353/projects/39261">Projects</a> page redirects to the <a href="https://circuitverse.org/users/13353">Users</a> page whereas it should bring back the user to the same page where they came from.

**To Reproduce**
1. Go to 'https://circuitverse.org/users/13353/projects/39261'
2. Click on 'Back'
3. See error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**

The link for the author's name already takes the user to the author's profile page, so need for the back button to take there. If possible, an option of view more can be added, saying something like, view more from this author.

**Are you working on this issue? (Yes/No)**
No. For GCI 2019.

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #641 

#### Describe the changes you have made in this pr -
Back button works

### CODE REVIEW

**Comment by tachyons** [comment]
Remove unrelated unchanges

**Comment by NumberC** [comment]
@tachyons How can I do that without undoing the Fork Synching?

**Comment by tachyons** [comment]
git checkout master <file to undo>

**Comment by NumberC** [comment]
@tachyons I did `git checkout master` and reverted the earliest ccommit "These are files for 'Add 'eye' feature on password' in Google Code In". I don't think it did anything

**Comment by NumberC** [comment]
Nevermind, I reverted the revert. Would doing something like `git rebase --onto HEAD^^ HEAD BackBtn` and then adding my change be better?

**Comment by tachyons** [comment]
git checkout master public/img/eye.PNG

Something like this

**Comment by NumberC** [comment]
Sorry, but for clarification, do I go to the master branch in my own forked repo and delete the eye.PNG file?

**Comment by tachyons** [comment]
git checkout master
git fetch upstream
git reset --hard upstream/master
git checkout BackBtn
git checkout master public
git commit -a -m "commit message"

Now squash commits

**Comment by NumberC** [comment]
I'm confused. I followed the steps and squashed the commits. Why doesn't it work anymore?

**Comment by tachyons** [comment]
May be something went wrong while squashing, since this is just a single page change, easy way to make changes again if your not fluent in git

**Pull request closed without merging**
