### PR TITLE
fixed Same name of Group and same name of Assignments should not be their

### PR DESCRIPTION
**Pull request by ryuk156**
Fixes  https://github.com/CircuitVerse/CircuitVerse/issues/1051

#### Describe the changes you have made in this PR -
Added uniqueness to the Group name and Assignments name 
### Screenshots of the changes (If any) -
A group name "meet123" already their:
image

Creating group of same name "meet123" :
image

Assignment of name "yash123":
image

Creating same name of Assignment i.e "yash123"
image

Case Sensitivity check :
image

image

### CODE REVIEW

**Comment by yash15601** [comment]
@tachyons  @Ananthavijay  @nitin10s Review please

**Comment by yash15601** [comment]
@Shivansh2407  actually i am  fixing that i m going through some error will commit changes in few min

**Comment by yash15601** [comment]
@Shivansh2407  Done  @tachyons  Review please

**Comment by Shivansh2407** [comment]
Please add updated screenshots @yash15601 👍

**Comment by satu0king** [comment]
This will make it unique across all assignments and all groups, so 2 groups cannot have the same assignment "assignment 1". This is highly undesirable. Also setting `uniqueness: { case_sensitive: false }` is a very bad idea, this will essentially make a select query on the name every time we save, a better way is to add an index. Read this - https://www.leighhalliday.com/requiring-uniqueness-in-rails

**Comment by yash15601** [comment]
@satu0king will fix this soon

**Comment by yash15601** [comment]
@tachyons  your views on this

**Comment by yash15601** [comment]
@tachyons  i have removed the same names in assignments because it was creating problem in creating Assignment in differnt group but i have fixed the same name issue in groups please Review it will fix for Assignment soon and make pr soon

**Comment by yash15601** [comment]
@tachyons  Review

**Comment by yash15601** [comment]
@satu0king @tachyons   I tryed using adding index in Assignments page but how can i handle the exception i tryed a lot nothing is working can ypu give me suggestion what can i do 
Screenshot:
image
image

**Pull request closed without merging**
