### PR TITLE
Help

### LINKED ISSUE #1390: Help for components
**Is your feature request related to a problem? Please describe.**
I want to make f1 key open the documentation of the selected components
for example:
- if the user selected a 7-segment displayer component and clicked on the f1 key, we will open [seven-segment-display](https://docs.circuitverse.org/#/outputs?id=seven-segment-display) section at the **documentation** on a **separate tab**, to give him many details about that component.

**Are you working on this? (Yes/No)**
YES

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #1390 

#### Describe the changes you have made in this PR -
making a costume shortcut for opening the documentation of the selected element for more info
- if the user did not select an element we will open the documentation page 
- else we will open that element part at the documentation.
##### There is a better implementation that than this -> instead of writing a JSON of help links, we can actually name the IDs at the documentation with the same names of the components, which is another story .if this was available we would easily access the links with much less code like this
`const type = simulationArea.lastSelected.objectType;`
` window.open(`https://docs.circuitverse.org/#/${type}`, '_blank');`
 , so this implementation is for now

### Screenshots of the changes (If any) -
helper

### CODE REVIEW

**Comment by Ananthavijay** [comment]
Can u try implementing this by using `helplink` of the element selected instead of declaring it separately? Refer: https://github.com/CircuitVerse/CircuitVerse/pull/847

**Comment by mahmodHammad** [comment]
> Can u try implementing this by using `helplink` of the element selected instead of declaring it separately? Refer: #847
That's cool idea
But I think now all components has this help link, correct me If I am wrong

**Comment by mahmodHammad** [comment]
There is a better implementation if rewriting a json of doc links, by changing the IDs at the doc with components name

**Comment by mahmodHammad** [comment]
@Ananthavijay  it's a good idea but unfortunately helplink is available for only 18 component of 52 component 
image

**Comment by Ananthavijay** [comment]
@mahmodHammad Check https://github.com/CircuitVerse/CircuitVerse/pull/1319

**Comment by mahmodHammad** [comment]
> @mahmodHammad Check #1319

oww that's many efforts.👍

**Comment by mahmodHammad** [comment]
let's wait till we do this https://github.com/CircuitVerse/CircuitVerse/issues/1393#issuecomment-612475898 
or #1319 got merged

**Comment by shubhankarsharma00** [comment]
@satu0king We can close this as #1319  got merged

**Comment by satu0king** [comment]
@mahmodHammad imagine you are double clicking something because your circuit isn't working in frustration and it opens a new page instead! xD

**Comment by abstrekt** [comment]
This PR was for a different feat request, not for the issue solved by #1319 
this PR actually aims to open docs for selected element on a new tab on keypress 'f1'
@satu0king  @shubhankarsharma00

**Comment by shubhankarsharma00** [comment]
@abstrekt correct. I guess I misunderstood it.

**Comment by shubhankarsharma00** [comment]
> @mahmodHammad imagine you are double clicking something because your circuit isn't working in frustration and it opens a new page instead! xD

It's actually F1 key.

**Comment by satu0king** [comment]
Ah my bad, I thought it was double click. However, please refactor your code to use what @Ananthavijay suggested, his PR got merged. 

Thank You

**Comment by mahmodHammad** [comment]
@satu0king  thanks for reviewing, but unfortunately i am extremely busy this couple of months, please merge it for now, and it could easily got refactored during GSOC project 2 "refactoring simulator code"

**Comment by satu0king** [comment]
Merged via #1743

**Pull request closed without merging**
