### PR TITLE
Fixed Stars Display

### LINKED ISSUE #1091: Stars Not Working Properly
**Describe the bug**
Whenever I star any of my circuit then it gets starred. Now when I get to my circuits page and then from there navigate to that particular circuit again a the glowing star is not shown but it remains in my favourites . 

**To Reproduce**
1. Go to 'New UI (Gitpod or Recent repo clone)'
2. Click on 'My circuits'
3. Star any circuit

**Expected behavior**
Stars must glow when the user returns back to page after starring the project

**Screenshots**
issue8

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes I would like to work on this .

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1091 

#### Describe the changes you have made in this PR -
I have fixed the stars in display. Now they remain whenever we refresh the page or switch between pages.
I will be converting the Inline CSS to the respective External CSS .

### Screenshots of the changes (If any) -
patch35

### CODE REVIEW

**Comment by Shivansh2407** [comment]
Capture
@nitin10s Is this fine ? Please let me know so that I can push the changes.

**Comment by nitin10s** [comment]
Oh sorry, I meant white filled would be the best since the bg is green.

**Comment by Shivansh2407** [comment]
@nitin10s and @tachyons Please reveiw 👍

**Comment by nitin10s** [comment]
Please update the screenshots.

**Comment by Shivansh2407** [comment]
Updated Screenshots :
When User has not given stars yet : 
Capture

When The user has starred the project : 
Capture

Please review and merge @nitin10s and @tachyons 👍

**Comment by Shivansh2407** [comment]
@tachyons please review this PR :+1:

**Pull request merged**
