### PR TITLE
Added Upvote and Downvote ToolTip

### LINKED ISSUE #576: Add tooltip in the upvote and downvote buttons.
**Is your feature request related to a problem? Please describe.**
Adding a tooltip in the upvote and downvote will make the UI/UX better.
Screenshot from 2019-11-08 19-03-12

**Describe the solution you'd like**
Add tooltip property to the buttons.

**Are you working on this? (Yes/No)**
For GCI

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #576

#### Describe the changes you have made in this pr -
I have added the Tooltip to the Upvote and Downvote Image according to the issue Mentioned.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
I don't think there is a need for tooltip for Upvote and Downvote because it is very common and used commonly in all the websites

**Comment by Shivansh2407** [comment]
Yes I agree but I fixed it as the issue was mentioned and by the way it just adds a general feature to the website. Do let me know your views @Ananthavijay , @tachyons and @satu0king 👍

**Comment by Shivansh2407** [comment]
@nitin10s and @Amansingla97 Please review and merge

**Comment by nitin10s** [comment]
As @Ananthavijay said, the options are pretty common and don't require any tooltip, this issue was made for GCI students and contributors to understand the codebase. So doesn't need to be merged

**Comment by aayush-05** [comment]
@tachyons @nitin10s are we planning to integrate this, or shall it be closed?

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed; added with new UI

**Pull request closed without merging**
