### PR TITLE
Fixed Min and Max Width Of Simulator Panel

### LINKED ISSUE #1229: Simulator Circuit Elements Panel Not Working Properly
**Describe the bug**
Whenever the user Drags the Left panel present in simulator , then on dragging to the leftmost part or the rightmost part the panel cannot be reverted back and hence the user must reload . 

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'simulator'
3. Drag the 'Left Panel of The simulator where elements are present'

**Expected behavior**
There must be a min width and max width defined for the Panel.

**Screenshots**
Issue12

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1229 

#### Describe the changes you have made in this PR -
I have fixed the simulator panel min and max width . So now the panel works properly . Also I have moved the inline CSS to External CSS in Simulator.scss.
Without Min and Max Width , the elements in the Panel gets distorted . 

### Screenshots of the changes (If any) -
patch-36

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@satu0king Please Review 👍

**Comment by Shivansh2407** [comment]
I will be fixing the issues soon 👍 .

**Comment by satu0king** [comment]
Cool, also can you set the width such that 3 elements can fit in by default.

**Comment by satu0king** [comment]
@Shivansh2407 please confirm that you can see 3 elements in a row by default like below. If not please raise a new PR. 
image

**Comment by Shivansh2407** [comment]
Opening a PR @satu0king 👍

**Pull request merged**
