### PR TITLE
deselect multiple elements with a single click

### LINKED ISSUE #1316: Deselecting elements in Simulator
**Describe the bug**
Currently, to deselect the selected elements on the simulator, we have to double click on a clear space.

**To Reproduce**
1. Go to Simulator
2. Select one or more elements
3. Double click somewhere else to deselect

**Expected behaviour**
As used in Windows and everywhere as far as I remember, a single click should deselect the element.

**Screenshots**
FireShot Capture 216 - CircuitVerse - Digital Circuit Simulator online - circuitverse org

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #1316

#### Describe the changes you have made in this PR -
deselect multiple elements with a single click instead of dbCLick.

https://user-images.githubusercontent.com/41790090/77852309-49058b80-71de-11ea-8855-9e8556e25170.gif

### CODE REVIEW

**Comment by mahmodHammad** [comment]
@nitin10s  @tachyons  @satu0king  
could you please check this

**Comment by mahmodHammad** [comment]
@nitin10s @tachyons @satu0king
could you please check this

**Comment by mahmodHammad** [comment]
@satu0king  @tachyons  @nitin10s 
review , please!

**Comment by abstrekt** [comment]
@satu0king

**Comment by satu0king** [comment]
Similar PR merged

**Comment by satu0king** [comment]
Neat!

**Pull request merged**
