### PR TITLE
Fixed issues with footer

### LINKED ISSUE #2520: Sticky footer problem in 404 error page
**Describe the bug**
The footer is not in a fixed position (footer is not sticky)

**To Reproduce**
<h2>Steps to reproduce the behavior:</h2>

1. Go to 'any invalid page'

2. Eg: https://circuitverse.org/sasdsada

3. Except root page all pages have the similar type of issue.

4. Then change screen zoom

5. See error

**Expected behavior**
<h3>Footer should be sticky.</h3>

<hr>

<h2>Screenshots</h2>
<br><br>

sticky footer

footeerrr

**Device Information [optional]:**
 - OS: Win 11 Dev Build
 - Browser Edge 
 - Version 94.0.992.38 (Official build) (64-bit)

**Are you working on this issue? (Yes/No)**
No, @ShreyaPrasad1209  Can you could label this issue as "good first issue."

### PR DESCRIPTION
**Pull request by Kartikay304**
Fixes #2520 

#### Describe the changes you have made in this PR -

1. fixed issues with footer

### Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/40604582/136583154-08eb728d-0644-42c0-8b3b-e2792b53c3f9.mp4

@nitin10s @tachyons  @pavanjoshi914, Please take a look at my PR

### CODE REVIEW

**Review by gr455 — CHANGES_REQUESTED** [review]
In mobile view, the lower part of the footer is white (should also be gray), also the scrollbar disappears

Screenshot from 2021-11-13 21-53-46

**Comment by Kartikay304** [comment]
> In mobile view, the lower part of the footer is white (should also be gray), also the scrollbar disappears
> 
> Screenshot from 2021-11-13 21-53-46

I have fixed the change of color of the footer in mobile view, and about the scrollbar, it remains invisible in mobile view unless the user touches the screen for navigation.

**Comment by nitin10s** [comment]
If you read my comment on the issue, we don't need this change. The previous behaviour was correct. Whatsay @pavanjoshi914?

**Review by nitin10s — COMMENTED** [review]
If you read my comment on the issue, we don't need this change. The previous behavior was correct. Whatsay @pavanjoshi914?

**Comment by pavanjoshi914** [comment]
> If you read my comment on the issue, we don't need this change. The previous behavior was correct. Whatsay @pavanjoshi914?

Yeah! @tachyons closed this already

**Pull request closed without merging**
