### PR TITLE
Add subcircuit name on hover in preview mode

### LINKED ISSUE #116: Show subcircuit type on previewMode
When the users clicks/hovers on a subcircuit in preview mode, the subcircuit type should be displayed.

### PR DESCRIPTION
**Pull request by ankitkataria**
Fixes #116 

#### Describe the changes you have made in this pr -

On hovering over a subcircuit, a small div with the subciruit name is shown at the bottom right. 

### Screenshots of the changes (If any) -
image

PS. the screen shot doesn't capture the mouse that was hovering over the element. 

Edit: Updated screenshot after minor fix.

### CODE REVIEW

**Comment by satu0king** [comment]
Can have the message show "Subcircuit: <name> " ?

**Comment by ankitkataria** [comment]
Done. :heavy_check_mark:

**Comment by ankitkataria** [comment]
@satu0king Is this one good to go?

**Comment by satu0king** [comment]
Thanks! We might have an issue with the positioning when the watermark issue gets resolved. Will inform you to check this again.

**Pull request merged**
