### PR TITLE
feat(youtube): added youtube in footer

### LINKED ISSUE #4047: Feature :youtube link of circuitVerse
### Is your feature request related to a problem? Please describe

youtube link of circuitVerse
like here in image below
Screenshot (282)

### Describe the solution you'd like

there can be CircuitVerse youtube link as well in the footer along with linkedin,instagram .It will be better for users as youtube has some tutorial also where user can take help and brush up their concepts 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #4047 

#### Describe the changes you have made in this PR -
youtube added to footer

### Screenshots of the changes (If any) -
Screenshot (285)

updated>>>>>>>>>>>
>
>

Screenshot (290)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@tachyons please review the pr

**Comment by VaibhavUpreti** [comment]
Current logo is quite different, you need to use the latest logo according to their guidelines.
https://developers.google.com/youtube/terms/branding-guidelines

**Comment by harshsharma-11** [comment]
@VaibhavUpreti can you check now
Screenshot (286)

**Comment by harshsharma-11** [comment]
@tachyons @VaibhavUpreti done as suggested please review the changes

**Review by Arnabdaz — CHANGES_REQUESTED** [review]
The icon seems too large 109kb can you changed to a scaled down version or an svg with the same design ?

**Comment by harshsharma-11** [comment]
@Arnabdaz done...... please review

**Comment by Arnabdaz** [comment]
> @Arnabdaz done...... please review

update the screenshot in pr description

**Comment by harshsharma-11** [comment]
@tachyons please review

**Review by tachyons — APPROVED** [review]

**Pull request merged**
