### PR TITLE
New UI/UX

### PR DESCRIPTION
**Pull request by vishnu-v-v**
#### Describe the changes you have made in this pr -
Add a new layout
Use it in the application controller as default layout.
Add a new header and footer components.
Split the existing header and footer to the newly added ones.

### CODE REVIEW

**Comment by tachyons** [comment]
I updated new_ux branch, please update with changes accordingly,

Use npm for third party js dependencies
Use scss over css
Use bootstrap scss vars to override styles

**Comment by tachyons** [comment]
There seems some conflicts, please resolve so that I can merge

**Comment by tachyons** [comment]
replace img tag with image_tag, otherwise link will broken in production environment

**Comment by vishnu-v-v** [comment]
@tachyons Can you please check this PR now. Hope everything is good to go!

**Pull request merged**
