### PR TITLE
Miscellaneous changes

### PR DESCRIPTION
**Pull request by tachyons**
* Support both mysql and pg in Gemfile
* Remove tests folder
* Update bundled gems
* Circle CI configuration

### CODE REVIEW

**Comment by satu0king** [comment]
I think this is good. I am not very familiar with CI tools, @vik-y can you pitch in?

**Comment by tachyons** [comment]
@satu0king Can you please enable circleci for this repo, Only admins can do that

**Comment by satu0king** [comment]
> @satu0king Can you please enable circleci for this repo, Only admins can do that

Sure, what do I need to do for that?

**Comment by tachyons** [comment]
I've already sent access request few days back. Can you please check your mail and approve

**Comment by satu0king** [comment]
> I've already sent access request few days back. Can you please check your mail and approve. https://github.com/settings/connections/applications/78a2ba87f071c28e65bb

Oh sorry, I missed this mail. I approved it now, can you check?

**Comment by tachyons** [comment]
screenshot 2019-03-06 at 6 14 34 pm
You need to enable this repo here https://circleci.com/add-projects/gh/CircuitVerse

**Comment by satu0king** [comment]
It is telling to create this file `.circleci/config.yml` 

sample config.yml
```
# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
```

**Pull request merged**
