### PR TITLE
Fixes projects page overlapping

### LINKED ISSUE #1106: Overlapping content on User Projects page
**Describe the bug**
The dialog for showing no projects/circuits and the favourites button are overlapping on mobile displays.

**Screenshots**
image

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Nitish145**
Fixes #1106 

#### Describe the changes you have made in this PR -
- Use responsive flexbox to position items in div.

## BEFORE
Screenshot from 2020-03-10 17-53-31
Screenshot from 2020-03-10 18-57-23

## AFTER
Screenshot from 2020-03-12 18-26-07
Screenshot from 2020-03-12 18-25-57

### CODE REVIEW

**Comment by Nitish145** [comment]
@nitin10s @tachyons @aayush-05 reviews please :)

**Comment by yash15601** [comment]
@Nitish145 good work

**Comment by Nitish145** [comment]
Will do shortly 🙂

**Comment by nitin10s** [comment]
Update the screenshots, please.

**Comment by Nitish145** [comment]
Will update sorry for the delay..

**Comment by aayush-05** [comment]
We can also change the link colour for "here" to green, it goes with the overall theme.

**Comment by Nitish145** [comment]
Sure

**Comment by Nitish145** [comment]
@nitin10s @aayush-05 screenshots updated. Reviews please :)

**Comment by Nitish145** [comment]
@nitin10s is there something else that needs to be addressed here ?

**Pull request merged**
