### PR TITLE
Added custom dropdown in the search panel

### LINKED ISSUE #1865: UI Improvement: Improve dropdown menu of search
**Description**
The drop down menu lacks the theme of the website theme because of its default drop down icon. I am looking forward to change this default icon so that it matches the website theme. I am also looking forward to add cursor: pointer to the search icon so that it looks clickable.

**Screenshot**
image

**Are you working on this issue?(Yes, No)**
Yes!

### PR DESCRIPTION
**Pull request by dipanshparmar**
Fixes #1865 

#### Describe the changes you have made in this PR -
1. Added class name and cursor: pointer to the search icon so that it looks clickable.
2. Added custom drop-down menu styles so that it looks the same in all the different browsers.

### Screenshots of the changes (If any) -
**Chrome (Before)**
image
**Chrome (After)**
image
___
**Firefox (Before)**
image
**Firefox (After)**
image

### CODE REVIEW

**Comment by satu0king** [comment]
@dipanshparmar you branched from new_UI and created the PR to master branch. What you should be doing is branch from master branch and create a PR to master branch. Thanks! 

Will close this PR for now

**Comment by dipanshparmar** [comment]
> @dipanshparmar you branched from new_UI and created the PR to master branch. What you should be doing is branch from master branch and create a PR to master branch. Thanks!
> 
> Will close this PR for now

@satu0king do you want me to merge all the changes to master and then make a pull request direct to master from my master branch?

**Comment by satu0king** [comment]
@dipanshparmar I suggest re creating the whole PR from scratch.

**Comment by dipanshparmar** [comment]
Yeah @satu0king, I'm looking forward to do the same but can you please guide me that which branches should I use for my PR. I mean which branch should I choose at my side to make the changes and to which branch should I push the changes to CircuitVerse side? It is not mentioned in contributing.md so I'm little confused.

**Comment by satu0king** [comment]
Do this, 
1. Make sure your master branch is upto date with CircuitVerse master
2. Create a new branch from your branch all it fix/custom-dropdown
3. Make your change in fix/custom-dropdown and commit
4. Send a PR!

😄

**Comment by dipanshparmar** [comment]
> Do this,
> 
>     1. Make sure your master branch is upto date with CircuitVerse master
> 
>     2. Create a new branch from your branch and call it fix/custom-dropdown
> 
>     3. Make your change in fix/custom-dropdown and commit
> 
>     4. Send a PR to our master branch from fix/custom-dropdown!
> 
> 
> smile

Thanks :smile:, it is clear now.

**Pull request closed without merging**
