### PR TITLE
Customize error pages and redirect to 404 when not_found

### LINKED ISSUE #1340: Missing 404 Page when user not found
**Is your feature request related to a problem? Please describe.**
When a user who does not exist is called for, it returns a plain page, which is not apt. 

**Describe the solution you'd like**
A conventional 404 page which matches the site's UI scheme should be added

**Describe alternatives you've considered**
or redirect to the homepage if we don't wasn't a 404 page

**Additional context**
None

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by harshgujrati**
Fixes #1340

### Screenshots of the changes (If any) -
Screenshot (250)
Screenshot (251)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshgujrati** [comment]
@nitin10s please review

**Comment by nitin10s** [comment]
Wait I'll redesign the page.

**Comment by harshgujrati** [comment]
It is not working in local environment @Shivansh2407

**Comment by Ananthavijay** [comment]
@harshgujrati To test it in a development environment, in `config/environments/development.rb`, make this `config.consider_all_requests_local` = `false`

**Pull request merged**
