### PR TITLE
Added Login with GitHub feature

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/658
[GCI TASK](https://codein.withgoogle.com/dashboard/task-instances/4869612357812224/)

#### Describe the changes you have made in this pr -
- Added Login with github feature.
- Added some clarifications to the "Adding environment variables" section in readme.

### Working :
CircuitVerse-Online-Digital-Logic-Circuit-Simulator

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@sal2701 Please have a look

**Comment by MrBartusek** [comment]
I think GitHub logo on button is too big

**Comment by Ananthavijay** [comment]
Github icon has the same size as others..

**Comment by MrBartusek** [comment]
Maybe it is but github icon is more massive So it looks bigger

**Comment by Ananthavijay** [comment]
Oh kk i will change it asap

**Comment by Ananthavijay** [comment]
@tachyons can there be a task for documentation on " How to use login with feature in development " ?

**Pull request merged**
