### PR TITLE
Final searchbar

### LINKED ISSUE #809: Add search bar in simulator
As a new user of CircuitVerse, I don't know in which categories all components are so it will be helpful to add a small search bar

**Additional context**
image
something like this but make it look as a search bar
image

_This issue is a part of my [Usability Test](https://drive.google.com/open?id=1igwLx2tc1dAU_75qY2F4u7ZnHf2crcp-)_
**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by NumberC**
Fixes #809

### Screenshots of the changes (If any) -
https://github.com/CircuitVerse/CircuitVerse/pull/836

### CODE REVIEW

**Comment by NumberC** [comment]
@shubhankarsharma00 Do you know why this might be happening? On slack, the response was to just fix the merge conflicts. The odd thing is that the files with merge conflicts don't have `<<<<<<<HEAD` or `>>>>>>>>>>BranchName`

**Comment by shubhankarsharma00** [comment]
@NumberC are you making your branches from latest updated main repo (https://github.com/CircuitVerse/CircuitVerse) ?

**Comment by NumberC** [comment]
I am making

**Comment by NumberC** [comment]
Them from the master branch of my locally forced repo. I'm assuming I should sync my branch with the master from the main repo

**Comment by shubhankarsharma00** [comment]
Yes sync it with this repo.

**Comment by NumberC** [comment]
@shubhankarsharma00 I synced it, but nothing has changed. When I try to do `git push` or `git status`, it tells me that everything is up-to-date.

**Comment by JoshHeng** [comment]
@NumberC Set the CircuitVerse repo as an upstream remote and then fetch. Then merge upstream master into your fork and resolve conflicts. Hound issues should also be fixed

**Comment by NumberC** [comment]
I think I already did that

**Comment by shubhankarsharma00** [comment]
@NumberC this branch you have made is not from upstream but from your main repo(origin) therefore some other changes that were present in your local repo have been transferred to this repo. Set the CircuitVerse repo as an upstream remote and then fetch. Make a new branch from upstream (not from the origin) this branch should have head coinciding with main circuitverse repo. Commit all the changes and then publish a PR. This should work 100%.

**Comment by NumberC** [comment]
@shubhankarsharma00 Thank you so much! It worked!

**Comment by shubhankarsharma00** [comment]
@NumberC still a couple of stray files but I'm glad there are no longer 147 changed files :laughing:  .

**Comment by NumberC** [comment]
@shubhankarsharma00 I was wondering if I could get this merged?

**Comment by NumberC** [comment]
@nitin10s Go to #836 . That was my previous PR, but I was experimenting with Git and this is the PR now. #836 has a photo provided.

**Comment by abstrekt** [comment]
is it a filter search? @NumberC

**Pull request closed without merging**
