### PR TITLE
Bug Fixes for Smaller Screens

### LINKED ISSUE #1945: Bugs
**Describe the bug**
1.) The "TIMING DIAGRAM" is overlapping to one more template in the screen sizes 1143px or less
2.) The toggling on of the navigation bar at screen sizes less than 991px, the contents of the navigation bar are hidden

**To Reproduce**
1. Go to 'https://beta.circuitverse.org/'
2. Click on 'simulator'
3. Reduce the screen size using chrome dev tools

**Expected behavior**
The contents of navbar after toggling on of the navbar should be seen clearly
No two templates should overlap each other

**Screenshots**
1.) 
download (4)
2.)
download (3)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser :  Chrome

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by shivamkushwah0**
Fixes #1945 

#### Describe the changes you have made in this PR -
1.) The overlapping of "TIMING DIAGRAM" with other panel is prevented on smaller screens.
2.) Made navbar visible for screens lesser than 991px.
3) The "SignIn" button and <Project Name> was diminished for screen sizes lesser than 991px, now it is visible.
4.)One panel was included in the nav so it was toggling off with navbar on smaller screens, it is prevented in it.  

### Screenshots of the changes (If any) -
1.) 
chrome-capture (2)
2.)
download (5)
3.)
download (6)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
1>solve hound issues 
2>sign in button was hidden intentionally for smaller views @satu0king  if it should to be visible or not?
3>why commited yarn.lock file ?

**Comment by shivamkushwah0** [comment]
@pavanjoshi914 
1.) the hound issues are some unnecessary white spaces. These are difficult to remove but still if there is necessity to remove them then i can try.
2.)Sign in button (and "Project Name") is necessary on all screens so i will suggest not to remove it @satu0king @pavanjoshi914 , but still if it isn't needed then i will change it as it was previously built.
3.)I am really sorry for this one, i didn't mean to do it. The problem is in the versions of dependencies i am working with (as i mentioned earlier), some of these are different than the one used, I don't know how to revert back to the version used, any help will be of much use here.

**Comment by pavanjoshi914** [comment]
> @pavanjoshi914
> 1.) the hound issues are some unnecessary white spaces. These are difficult to remove but still if there is necessity to remove them then i can try.
> 2.)Sign in button (and "Project Name") is necessary on all screens so i will suggest not to remove it @satu0king @pavanjoshi914 , but still if it isn't needed then i will change it as it was previously built.
> 3.)I am really sorry for this one, i didn't mean to do it. The problem is in the versions of dependencies i am working with (as i mentioned earlier), some of these are different than the one used, I don't know how to revert back to the version used, any help will be of much use here.

hound helps to make our code more cleaner please try to resolve them....
If your local setup work fine you dont have to worry about  same version dependencies  just make sure you dont commit it while making commits

**Comment by shivamkushwah0** [comment]
> > @pavanjoshi914
> > 1.) the hound issues are some unnecessary white spaces. These are difficult to remove but still if there is necessity to remove them then i can try.
> > 2.)Sign in button (and "Project Name") is necessary on all screens so i will suggest not to remove it @satu0king @pavanjoshi914 , but still if it isn't needed then i will change it as it was previously built.
> > 3.)I am really sorry for this one, i didn't mean to do it. The problem is in the versions of dependencies i am working with (as i mentioned earlier), some of these are different than the one used, I don't know how to revert back to the version used, any help will be of much use here.
> 
> hound helps to make our code more cleaner please try to resolve them....
> If your local setup work fine you dont have to worry about same version dependencies just make sure you dont commit it while making commits

ok i am on it.....trying to resolve the hound issues.
So what should I do with the yarn.lock file , i can make a new PR with different branch......should i do it??
and what about the "SIGN IN" and "Project Name" , can we keep it??

**Comment by shivamkushwah0** [comment]
solved all the hound issues
i am not able to do anything of yarn.lock file, please help me to revert back to previous yarn.lock file, i am relatively new to git

**Comment by dipanshparmar** [comment]
@shivamkushwah0 you can use the command **git log** to see your previous commits. After using this command you will be presented with your previous commits and their SHA-1 checksums. Then spot the SHA-1 checksum of the commit where you committed the yarn.lock file, and then check out its previous commit by using **git checkout SHA-1 checksum (the previous SHA-1 then the yarn.lock file committed SHA-1)**. Then open the yarn.lock file, copy its contents and then come back to the latest commit you are working on and paste all the contents of that file to the updated yarn.lock file and it should go back to the normal state. Then commit that yarn.lock file and push it, and all the dependencies should come to default now.

**Note**: if **git log** is not showing all the previous commits you need, then you can also use **git reflog**.

**Comment by dipanshparmar** [comment]
> solved all the hound issues
> i am not able to do anything of yarn.lock file, please help me to revert back to previous yarn.lock file, i am relatively new to git
> @pavanjoshi914

@shivamkushwah0 you can use the command git log to see your previous commits. After using this command you will be presented with your previous commits and their SHA-1 checksums. Then spot the SHA-1 checksum of the commit where you committed the yarn.lock file, and then check out its previous commit by using git checkout SHA-1 checksum (the previous SHA-1 then the yarn.lock file committed SHA-1). Then open the yarn.lock file, copy its contents and then come back to the latest commit you are working on and paste all the contents of that file to the updated yarn.lock file and it should go back to the normal state. Then commit that yarn.lock file and push it, and all the dependencies should come to default now.

Note: if git log is not showing all the previous commits you need, then you can also use git reflog.

**Comment by shivamkushwah0** [comment]
> > solved all the hound issues
> > i am not able to do anything of yarn.lock file, please help me to revert back to previous yarn.lock file, i am relatively new to git
> > @pavanjoshi914
> 
> @shivamkushwah0 you can use the command git log to see your previous commits. After using this command you will be presented with your previous commits and their SHA-1 checksums. Then spot the SHA-1 checksum of the commit where you committed the yarn.lock file, and then check out its previous commit by using git checkout _SHA-1 checksum_ _(the previous SHA-1 then the yarn.lock file committed SHA-1)_. Then open the yarn.lock file, copy its contents and then come back to the latest commit you are working on and paste all the contents of that file to the updated yarn.lock file and it should go back to the normal state. Then commit that yarn.lock file and push it, and all the dependencies should come to default now.
> 
> **Note**: if **git log** is not showing all the previous commits you need, then you can also use **git reflog**.

thanks a lot sir.....

**Comment by shivamkushwah0** [comment]
@pavanjoshi914 have a look now.....there are no such issues in yarn.lock file now , and please let me know if the SignIn button and Project Name are to be shown on the screen or not.

**Comment by pavanjoshi914** [comment]
> @pavanjoshi914 have a look now.....there are no such issues in yarn.lock file now , and please let me know if the SignIn button and Project Name are to be shown on the screen or not.
I meant to say why you are  introducing yarn.lock file in commits? we dont commit yarn.lock file in simple words please remove it!!!

**Comment by shivamkushwah0** [comment]
> > @pavanjoshi914 have a look now.....there are no such issues in yarn.lock file now , and please let me know if the SignIn button and Project Name are to be shown on the screen or not.
> > I meant to say why you are  introducing yarn.lock file in commits? we dont commit yarn.lock file in simple words please remove it!!!

yep i removed that file from commit

**Comment by shivamkushwah0** [comment]
@satu0king please review the PR , I cannot proceed to next issue until this PR is resolved....!!

**Pull request closed without merging**
