### PR TITLE
trumbowyg improvements

### LINKED ISSUE #1837: WYSIWYG Text Editor - Improvements
**Is your feature request related to a problem? Please describe.**

Current Editor
image

We are using https://alex-d.github.io/Trumbowyg/

However, the editor in the main website is having more features 
image

Specific features I would like to see
* HTML Code Preview
* More Text Size options
* Super Script and SubScript
* Full Screen View

Plugins also have more features which we can consider
1. Embed Video
2. Upload Image -> IMGUR
3. Color Text
image

Maybe we are using an older version of the text editor or we have to enable the features, not sure. 

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by pavanjoshi914**
Fixes #1837 
implemented all features mentioned in #1837 

#### Describe the changes you have made in this PR -
1>enabling all the features present in core trumbowyg editor
2>implementing specific features desired by author:: 
     HTML Code Preview 
     More Text Size options
     Super Script and SubScript
     Full Screen View
     Embed Video  (through pasteembed plugin)
     Upload Image -> IMGUR
     Color Text (through colours plugin)

3>mirgrating styles required for colors plugin in editor.scss

### Screenshots of the changes (If any) -
Before::

Screenshot from 2020-10-29 14-36-41

After::
Screenshot from 2020-10-29 14-40-19
trumbowyg
Screenshot from 2020-10-29 14-28-19

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
@satu0king

**Comment by tachyons** [comment]
Add before and screenshots

**Comment by pavanjoshi914** [comment]
> Add before and screenshots

sorry for the  inconvinience...added now! plz have a check on this..

**Comment by satu0king** [comment]
Good Job :D

**Pull request merged**
