### PR TITLE
[GCI] Refactor simulator styles and scripts

### LINKED ISSUE #824: Simulator Code Problems
**Describe the bug**
Currently the simulator page page uses the application layout which contains lots of changes which the simulator page does not require. There are also style issues in the simulator in the master branch

**Solution**
- Create base stylesheet for simulator layout
- Create base javascript for simulator layout
- Fix style overriding issues in master branch

**Other Information**
Created as a GCI task by @Abhiram-vv, @vishnu-v-v, @tachyons & Alan Joseph

### PR DESCRIPTION
**Pull request by junron**
Fixes #824 

#### Describe the changes you have made in this pr -
Removed include of application styles and scripts in simulator.html.erb
Added simulator.scss and simulator.js
Added bootstrap and jquery dependency to these files
Fixed styling of bootstrap toolbar.

### Screenshots of the changes (If any) -
ui-comp
Comparison of UI in this PR (left) and original UI (right)

Please have a look @tachyons @alanjsph

### CODE REVIEW

**Comment by junron** [comment]
@tachyons Please review

**Comment by junron** [comment]
@tachyons Please have a look

**Comment by tachyons** [comment]
Include screenshot from live website as well for comparison, also ensure that style is loading properly after bootstrap version was upgraded

**Comment by junron** [comment]
image
@tachyons New bootstrap problems fixed, screenshot attached above
You can try it at https://demo.circuitverse.chatbox2.ml/simulator

**Comment by satu0king** [comment]
Merging this for now. Please check #825 for future improvements.

**Comment by shubhankarsharma00** [comment]
@satu0king this PR makes dropdown menu options like save, clear and many others unfunctional. Is this still under progress or should we look to fix it in a new issue?

**Comment by satu0king** [comment]
You are right, the PR removed css class `logixButton`

**Comment by tachyons** [comment]
Need an urgent fix this

**Comment by Ananthavijay** [comment]
@tachyons it is [here](https://github.com/CircuitVerse/CircuitVerse/pull/986) by @shubhankarsharma00

**Pull request merged**
