### PR TITLE
Initiate code-linting with rubocop and eslint

### LINKED ISSUE #129: Add code linter
As the code base grows large, a code linter like rubocop - https://github.com/rubocop-hq/rubocop will make it very easy to keep a hold of overall code quality by imposing strict checks. 

Once added, the entire code-base will have to linted. Most of errors will get fixed by `rubocop -a`

### PR DESCRIPTION
**Pull request by ankitkataria**
Fixes #129 

#### Describe the changes you have made in this pr -

- Added `rubocop` and `.rubocop.yml`
- Added eslint for js code
- Added codeclimate config and tested [here](https://codeclimate.com/github/ankitkataria/CircuitVerse)

Todo - 
- [x] add eslint for linting js code
- ~fix existing linting errors in code~ 

According to the current rules, there are 476 offenses out of which 441 offenses are automatically fixed by `rubocop -a`, rest of those errors are mostly related to line and method lenths and will have to be fixed manually. 
For the js code there are a whopping 46k offenses out of which 40k offenses can be autofixed

### CODE REVIEW

**Comment by ankitkataria** [comment]
@tachyons @satu0king In this pr, i've added `rubocop` and `eslint`. I've been testing these changes on https://github.com/ankitkataria/CircuitVerse/tree/code-lint-test
I added a codeclimate config file and set up the this branch on codeclimate [here](https://codeclimate.com/github/ankitkataria/CircuitVerse). Further, I installed codeclimate's github plugin to lint code on pull requests. 
The work flow for linting looks something like this - 
- A user can make a PR. For eg - https://github.com/ankitkataria/CircuitVerse/pull/2
- Code climates analysis will be shown against the pr, similar to the following screen shot.
image
- Contributor will navigate to codeclimate in case of errors -https://codeclimate.com/github/ankitkataria/CircuitVerse/pull/2
- Errors can be filtered for the `New` ones. They'll have to be fixed.

**Comment by tachyons** [comment]
Looks good so far :+1:

**Comment by tachyons** [comment]
@satu0king you need to enable code climate integration for this repo

**Comment by tachyons** [comment]
Can we get this setup ready as early as possible, So that I don't have to manually review all the style issues. cc @satu0king @arkokoley

**Comment by ankitkataria** [comment]
@satu0king You'll have to add this repo to codeclimate and then install the github plugin from repo settings. 
Reference - https://docs.codeclimate.com/docs/repository-settings
Now that the CI is also setup we can look into setting up the test coverage report on codeclimate once this is merged.

**Comment by armudgal** [comment]
@tachyons @satu0king Wanna integrate CodeClimate with CircleCI (will be needing it in tests anyway) later on or right now.

**Comment by tachyons** [comment]
Why? We can have them as separate integration, right ?

**Comment by tachyons** [comment]
Add https://github.com/rubocop-hq/rubocop-rspec as well

**Comment by armudgal** [comment]
@tachyons. True, but integrating so that we have one CI and use CodeClimate to give a better report on test and coverage would make more sense, what do you think?

**Comment by armudgal** [comment]
Once the conflicts are resolved we can move forward with merging it. Before that @satu0king  @tachyons can you setup our repository on CodeClimate.

**Comment by tachyons** [comment]
I don't have access to do that, For test coverage, we already have integration to https://coveralls.io/ in the CI. Just enabling coverall for this repo will show the test coverage

**Comment by ankitkataria** [comment]
@tachyons I've added rubocop-rspec.

**Comment by satu0king** [comment]
@tachyons , I have made you admin of the repo, You should be  having access to do anything.

**Pull request merged**
