### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by sakshi1499**
Fixes #

#### Describe the changes you have made in this pr -
This is in reference with the issue #478

### CODE REVIEW

**Comment by tachyons** [comment]
I would like to see more detailed explanation about how to use gitpod to contribute to Circuitverse including screenshots in the wiki and link to that from Readme file

**Comment by sakshi1499** [comment]
Okay, will do that. Wiki as in, in CircuitVerse Docs? Or in the readme itself?
@tachyons

**Comment by ankitkataria** [comment]
@sakshi1499 wiki on Github. Find it [here](https://github.com/CircuitVerse/CircuitVerse/wiki).

**Comment by sakshi1499** [comment]
Okay thankyou. I am working on it :)

**Comment by sakshi1499** [comment]
I have made the wiki, I don't know how to push it to your wiki. Please review it and tell me how can I add it to your wiki?
https://github.com/sakshi1499/CircuitVerse/wiki/Using-Gitpod-to-develop-CircuitVerse

**Comment by sakshi1499** [comment]
Now what has to be done? Once you'll add it to wiki, I'll change the readme and make a pull request of the same.

**Comment by tachyons** [comment]
@sakshi1499 looks great so far, Can you add it here https://github.com/CircuitVerse/CircuitVerse/wiki/Development-on-Gitpod/_edit ?

Also can you add steps for opening a pull request from gitpod?

**Comment by sakshi1499** [comment]
noper

I don't have the permission. If you want I can add about pull requests in another file also.

**Comment by tachyons** [comment]
@sakshi1499 Fixed that, Can you try again ?

**Comment by sakshi1499** [comment]
https://github.com/CircuitVerse/CircuitVerse/wiki/Development-on-Gitpod
Done!
Should I add the pull requests one in this folder only or make a new file? I think if we have to add the link in the readme, pull requests one should be in different file. What do you suggest?

**Comment by sakshi1499** [comment]
https://github.com/sakshi1499/CircuitVerse/wiki/Pull-Requests-using-Gitpod
Please review it . If its fine, I'll make changes in readme and make a pull request.

**Comment by tachyons** [comment]
LGTM @satu0king please have a look

**Pull request merged**
