### PR TITLE
added horizontal padding to the 'render circuit image' button

### PR DESCRIPTION
**Pull request by dipanshparmar**
#### Describe the changes you have made in this PR -
Added horizontal padding

### Screenshots of the changes (If any) -
**Before**
image

**After**
image

### CODE REVIEW

**Review by vedant-jain03 — CHANGES_REQUESTED** [review]
Why commit these file?
app/javascript/src/sass/color_theme.css
app/javascript/src/sass/color_theme.css.map

**Comment by dipanshparmar** [comment]
> Why commit these files? app/javascript/src/sass/color_theme.css app/javascript/src/sass/color_theme.css.map
> 
> You should only commit this one : simulator/src/css/main.stylesheet.css

My bad! fixed.

**Comment by vedant-jain03** [comment]
> > Why commit these files? app/javascript/src/sass/color_theme.css app/javascript/src/sass/color_theme.css.map
> > You should only commit this one : simulator/src/css/main.stylesheet.css
> 
> My bad! fixed.

All right @dipanshparmar , Good work
LGTM @tachyons

**Review by vedant-jain03 — APPROVED** [review]

**Comment by dipanshparmar** [comment]
@tachyons, @nitin10s Can you please have a look?

**Pull request closed without merging**
