### PR TITLE
Fix Project Title Alignment

### LINKED ISSUE #1028: Simulator project title is not align properly
When simulator page is open in mobile, the project title doesn't align properly

1. Go to the simulator in the mobile phone and click on navbar button
2. See error
Expected behavior
it should be aligned in the center

Are you working on this issue? 
Yes

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1028 

#### Describe the changes you have made in this PR -
I have added Media Query for the Project name and also removed the `pull right` style from the sign in option to fix the issue .
Additionally I have added favicon to the simulator page.

### Screenshots of the changes (If any) -
patch25

### CODE REVIEW

**Comment by Shivansh2407** [comment]
Please review @tachyons and @nitin10s 👍

**Comment by Shivansh2407** [comment]
@nitin10s review please 👍

**Comment by Shivansh2407** [comment]
@satu0king Please review 👍

**Comment by Shivansh2407** [comment]
@nitin10s Please review this 👍

**Comment by Shivansh2407** [comment]
@nitin10s Please review this 👍

**Comment by Shivansh2407** [comment]
Sure @nitin10s . I will update the PR with the requested changes soon 👍🏻.

**Comment by nitin10s** [comment]
@Shivansh2407

**Comment by aayush-05** [comment]
@Shivansh2407 are you working on this ?

**Comment by Shivansh2407** [comment]
I will update this PR soon @aayush-05.

**Comment by Shivansh2407** [comment]
Updated Screenshots :
Capture
Capture1
Please review @nitin10s  👍

**Comment by Shivansh2407** [comment]
@nitin10s please review 👍

**Comment by abstrekt** [comment]
is it necessary? as the simulator is not available for smaller screens? @nitin10s

**Comment by Shivansh2407** [comment]
This can come into action when resizing (zoom in and out) of webpage will be done.

**Comment by nitin10s** [comment]
I kind of agree with Shivansh, @abstrekt is this PR valid regarding the new design of simulator?

**Comment by abstrekt** [comment]
oh right, sorry my bad

**Comment by satu0king** [comment]
@Shivansh2407  please check this PR and close/fix as required

**Pull request closed without merging**
