### PR TITLE
fix-Added border-radius-to-all-boxes

### LINKED ISSUE #4560: No border radius is given for boxes (many for search)🐞 Bug
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No border radius is given for boxes (many for search) .This is quite a bad user experience practise
Screenshot 2024-01-10 164719

### Steps To Reproduce

1. Go to home page
2. click on search button

### Expected Behavior

for better user experience there should be some border radius

### Screenshots

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by priyanshagra**
Fixes #4560 

#### Describe the changes you have made in this PR -
-Added border-radius-to-all-boxes

### Screenshots of the changes (If any) -
Screenshot 2024-01-29 022137

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by priyanshagra** [comment]
Screenshot 2024-02-04 182800
Screenshot 2024-02-02 041202
added border ra

**Comment by priyanshagra** [comment]
@tachyons @tanmoysrt please check

**Comment by priyanshagra** [comment]
Screenshot 2024-02-05 163329
Screenshot 2024-02-05 163310
added border radius

**Comment by priyanshagra** [comment]
@nitin10s @tanmoysrt @tachyons please review this

**Review by nitin10s — APPROVED** [review]
LGTM

**Review by tachyons — CHANGES_REQUESTED** [review]
Remove inline styles and use CSS

**Comment by tachyons** [comment]
You can use bootstrap utilities to simplify the changes https://getbootstrap.com/docs/4.0/utilities/borders/

**Comment by priyanshagra** [comment]
@tachyons @tanmoysrt please check changes are done as removed inline css and styles in respective files

**Pull request merged**
