### PR TITLE
[GCI] Added WSL installation instructions to README.md

### PR DESCRIPTION
**Pull request by nrs1729**
#### Describe the changes you have made in this pr:
Added how to install WSL on Windows 10 and then setup Ruby on Ubuntu in WSL to the README. Issue #521

### CODE REVIEW

**Comment by eKuG** [comment]
could have added more info and some screenshots of your own screen

**Comment by nrs1729** [comment]
I added a few screenshots for installing WSL and some small clarifications where I thought the instructions could be unclear.

**Comment by eKuG** [comment]
More work needed. Show step by step, how you installed RVM on windows via WSL. If possible, make a video for the setup of Circuitverse on windows(Just the computer screen)

**Comment by nrs1729** [comment]
I added a screen recording of the setup using the instructions in the README.

**Comment by tachyons** [comment]
Closing as we moved documentation from Readme. Thanks for the great work

**Pull request closed without merging**
