### PR TITLE
Close fullscreen using ESC button

### PR DESCRIPTION
**Pull request by ahmedibrahim404**
This PR is part of issue https://github.com/CircuitVerse/CircuitVerse/issues/2959

New feature to close fullscreen mode using ESC button

#### Describe the changes you have made in this PR -
- Implemented function to exit fullscreen mode
- Integrated this function with Exit full mode button
- Added Listener to listen for ESC key whenever clicked to close fullscreen mode

### CODE REVIEW

**Comment by gr455** [comment]
@ahmedibrahim404 This looks great, thanks so much. Can you also add the timing diagram and testbench to dissapear in fullscreen mode (and hence reappear when exitted).
I know this is a part of the issue but it'll be good to have.

**Comment by ahmedibrahim404** [comment]
@gr455 
Sure I will do this

**Comment by ahmedibrahim404** [comment]
last

This is how it looks now, @gr455

**Comment by gr455** [comment]
Great thanks!!

**Pull request merged**
