### PR TITLE
Added js to highlight any matches for the search term in the results

### LINKED ISSUE #561: custom search(HIGH LIGHTED)
**Is your feature request related to a problem? Please describe.**
whenever we do search in search field we get result like if we search "unique" we get some result
and if we search "nothing will get same search result output we will confused why it so.but because in first case it giving output because its title is named "unique" but in the second time when we search "nothing" it gave the same result because there is 'nothing ' word found in same passed named or titled 'unique'

**Describe the solution you'd like**
whenever search result gives output it should be HIGHLIGHTED so we can understand why this comes in output
 
somewhat like this

Screenshot (65)

Screenshot (67)

**Are you working on this? (Yes/No)**
NO, THIS IS FOR GCI STUDENTS

### PR DESCRIPTION
**Pull request by JoshHeng**
Fixes #561 

#### Describe the changes you have made in this pr -
Added javascript and css to highlight searches

### Screenshots of the changes (If any) -
firefox_UroYFjMr8s

### CODE REVIEW

**Comment by tachyons** [comment]
Good work, But I would prefer to see it working without js https://github.com/sunspot/sunspot/wiki/Working-with-search#keyword-highlighting, you can find one approach of highlighting from backend here

**Comment by satu0king** [comment]
@nitin10s , is this still relevant for our new UI?

**Comment by satu0king** [comment]
@nitin10s , is this still relevant for our new UI?

**Comment by nitin10s** [comment]
Yes, could be used. We need to revamp this page as well. I'll come up with the fix for the search bar.

**Comment by nitin10s** [comment]
@aayush-05

**Comment by JoshHeng** [comment]
Hi, sorry for the inactivity.
Are you taking care of this or should I update my PR?

**Comment by aayush-05** [comment]
Revamping this page currently, so I am not sure if you would be able to continue on this. Maybe put this on a hold for now, and we can discuss after I revamp this page. Whatsay ?

**Comment by JoshHeng** [comment]
> 
> 
> Revamping this page currently, so I am not sure if you would be able to continue on this. Maybe put this on a hold for now, and we can discuss after I revamp this page. Whatsay ?

Yeah, sure. Tag me if you need anything

**Pull request merged**
