### PR TITLE
[GCI] Fix restricted elements bug

### LINKED ISSUE #649: Updating Restricted Elements doesn't work.
**Describe the bug**
When you make an Assignment and then try to change restricted elements of that assignment it does nothing.
**To Reproduce**
1. Go to 'circuitverse.org'
2. Make a group
3. Add an Assignment with no restricted element 
4. Edit the restricted elements.

**Expected behavior**
Should change the restricted elements.

**Additional context**
The error seems to be this line 
https://github.com/CircuitVerse/CircuitVerse/blob/2898a70401ae1d7521a9e8c51347ec9710a74bdf/app/controllers/assignments_controller.rb#L153
removing this makes it work fine

**Are you working on this issue? (Yes/No)**
GCI Problem

### PR DESCRIPTION
**Pull request by junron**
Fixes #649 

#### Describe the changes you have made in this pr -
Removed extra parameter restriction line in assignments controller. This bug was much easier to fix than expected.

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/4823977961193472/)

### CODE REVIEW

**Comment by junron** [comment]
The decrease in coverage is due to the removal of a line that was tested.

**Comment by junron** [comment]
@shubhankarsharma00 Please review

**Comment by shubhankarsharma00** [comment]
Nice work

**Comment by tachyons** [comment]
Thanks

**Pull request merged**
