### PR TITLE
Allow blank issues

### PR DESCRIPTION
**Pull request by MrBartusek**
I think limiting possible issues to only two categories is a quite bad idea. I want to add an issue that is more like issue regarding code base and it doesn't fit a `bug` or `feature request`.

### CODE REVIEW

**Comment by MrBartusek** [comment]
@nitin10s please review

**Comment by nitin10s** [comment]
We can make a new category for such issues to organize them better, what do you suggest be the category name?

**Comment by MrBartusek** [comment]
@nitin10s i don't think so, there is no reason to create category for only one issue

**Comment by nitin10s** [comment]
I meant for all the issues that people might have regarding the codebase.

**Comment by MrBartusek** [comment]
@nitin10s Well, for that kind of issue you can create `Codebase` template but that would be very unpopular so there is not much sense in it

**Pull request merged**
