### PR TITLE
feat: update simple_discussion

### PR DESCRIPTION
**Pull request by Waishnav**
This PR updates the `simple_discussion` gem.

### CODE REVIEW

**Comment by tachyons** [comment]
@Waishnav could you add screenshot from forum page to make sure that delete button is now present ?

**Comment by Waishnav** [comment]
@tachyons  After checking out locally it's working as intended.
image

**Comment by tachyons** [comment]
@Waishnav CI is failing due to steep issue, could you check that. It is unrelated to this PR ?

**Comment by Waishnav** [comment]
> @Waishnav CI is failing due to steep issue, could you check that. It is unrelated to this PR ?

yup it is unrelated to this PR. `steep` is not even updated in Gemfile.lock

**Comment by tachyons** [comment]
We need to get it resolved to merge this PR

**Comment by Waishnav** [comment]
@tachyons found similar issue with `steep` issue and it is marked as `bug` by maintainers of steep

Please have a quick look into this issue https://github.com/soutaro/steep/issues/401, let me know if I have wrong understanding of this CI failure.

**Comment by tanmoysrt** [comment]
Sometimes, due to issue in rbs or missing method in rbs, steep can raise error.

For that, we need to update the **Steepfile** and update the `steep` gem version at-least to 1.5.3 (currently 1.4.0)

```
# frozen_string_literal: true

steep_diagnostic = Steep::Diagnostic

target :app do
  signature "sig"
  configure_code_diagnostics(steep_diagnostic::Ruby.lenient)
  configure_code_diagnostics do |hash|
    hash[steep_diagnostic::Ruby::NoMethod] = :information
  end
end
```

Context - https://github.com/CircuitVerse/CircuitVerse/pull/3955#issuecomment-1691529171

_If I found the issue comment of the creator, I will attach the link here._

**Pull request merged**
