### PR TITLE
New rich text editor#830

### LINKED ISSUE #830: WYSIWYG broken and might look nicer
**Describe the bug**
- Dropdowns not working `index.js:22 Uncaught TypeError: Bootstrap's dropdowns require Popper.js (https://popper.js.org/)`
- The scrollbars on the WYSIWYG editor should only be shown if needed
- The blue colour in the WYSIWYG editor should be changed to something that follows the overall colours of the website. It looks a bit out of place

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by MrBartusek**
Fixes #830 

####  I completely removed old [mindmup/bootstrap-wysiwyg](https://github.com/mindmup/bootstrap-wysiwyg)
Because this fork and original editor are not supported

#### Implemented new [Trumbowyg -  lightweight WYSIWYG editor](https://alex-d.github.io/Trumbowyg/)
That one is implemented using `yarn` not hard-coded, I made custom styling to match platform theme
Using editor in forms is very easy 
``` ruby
# in place where it should be rendered
<%= render :partial => 'editor/index', :locals => {:content => @mail.content} %>
```
``` js
// in place where form is submitted
$("#trumbowyg-editor").cleanHtml()
```

### Before:
image

### After:
image
image

### CODE REVIEW

**Comment by tachyons** [comment]
Can you check the contents created in old editor is editable in new editor without any changes ?

**Comment by MrBartusek** [comment]
@tachyons I can confirm it is working. the only problem is "cut text" tool when used on old editor the new editor is working but text cuts cannot be edited but can be deleted when the affected line is empty. I can't check what about some of the tools cause old editor is broken but I'm am pretty sure they will work

**Comment by tachyons** [comment]
This is breaking button backgrounds across cv as 

```
button:not(.trumbowyg-disable):hover,
button:not(.trumbowyg-disable):focus,
button.trumbowyg-active {
  background-color: inherit !important;
  outline: none;
}
```

Is applicable to every other divs,

**Comment by aayush-05** [comment]
> This is breaking button backgrounds across cv as
> 
> ```
> button:not(.trumbowyg-disable):hover,
> button:not(.trumbowyg-disable):focus,
> button.trumbowyg-active {
>   background-color: inherit !important;
>   outline: none;
> }
> ```
> 
> Is applicable to every other divs,

I noticed that too, will be removing the !important tag in the new pr, I don't think it will cause any problem for the text editor.

**Comment by tachyons** [comment]
Made a hotfix here, https://github.com/CircuitVerse/CircuitVerse/commit/889095c29b5bb6229ec9db489ae9faa630287437 Need proper fix as well

**Comment by MrBartusek** [comment]
@tachyons that is working perfectly fine after this hotfix, no need for further fixes, thanks!

**Pull request merged**
