### PR TITLE
fix(ui): social media icons alignment

### LINKED ISSUE #2712: Centering the social icons in the footer
**Describe the bug**
Misalignment of icons: There is a non-uniform margin and padding on the icons.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to 'footer'
4. See the icons

**Screenshots**

Before: 
original
After: 
edited

**Are you working on this issue? (Yes/No)**
 Yes, I will create a PR if the issue is appproved.

### PR DESCRIPTION
**Pull request by theslowdeveloper**
Fixes #2712 

#### Describe the changes you have made in this PR -
Before:
image
padding-top and margin-left property on the social-media-icons restricts it from being aligned.

After:
image
removed padding-top and margin-left property on the social-media-icons, added some margin to the container to align it, and lastly added padding to give some spacing to elements.

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by theslowdeveloper** [comment]
@vedant-jain03 @tanmoysrt can you please review this ?

**Review by tanmoysrt — CHANGES_REQUESTED** [review]
looks fine but needs a little bit more spacing between the icons.

**Comment by theslowdeveloper** [comment]
image
how about this @tanmoysrt I also decreased size of the icons a little bit with some extra spacing

**Comment by tanmoysrt** [comment]
> image how about this @tanmoysrt I also decreased size of the icons a little bit with some extra spacing (didn't commit yet)

This looks fine !

**Review by vedant-jain03 — CHANGES_REQUESTED** [review]
Let's remove border from this!

**Comment by theslowdeveloper** [comment]
> Let's remove border from this!

Done 
Screenshot from 2023-10-15 15-23-24

**Review by vedant-jain03 — APPROVED** [review]

**Comment by vedant-jain03** [comment]
@theslowdeveloper Can you remove the last commit I request for border, that is fixed under #4181

**Comment by theslowdeveloper** [comment]
> @theslowdeveloper Can you remove the last commit I request for border, that is fixed under #4181

Done

**Pull request merged**
