### PR TITLE
Loader redesign proposal-implementation- For issue #468

### LINKED ISSUE #468: Loader redesign proposal
**Is your feature request related to a problem? Please describe.**
Currently, the loader is a blue diamond folding animation. For better impact, we may replace it with a new loader. Would look great if opposite arms of links in the circuitverse logo light up alternatively.

**Describe the solution you'd like**
The new proposed loader might build up on top of the [circuitverse logo](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/favicon.ico) 

**Describe alternatives you've considered**

**Additional context**
loadercc
Intended for GCI'19.

**Are you working on this? (Yes/No)**
No.

### PR DESCRIPTION
**Pull request by mohit-003**
Fixes #468 
#### Describe the changes you have made in this pr -
New loader is designed with circuit-verse logo.
 For [GCI task](https://codein.withgoogle.com/dashboard/task-instances/4578182083117056/).
### Screenshots of the changes (If any) -

WhatsApp-Video-2019-12-23-at-10 49 54-PM-_2_

### CODE REVIEW

**Comment by mohit-003** [comment]
@Parikshit-Hooda  @nitin10s Please review my task.

**Comment by Parikshit-Hooda** [comment]
@mohit-003 Please attach a screenshot of your implementation here. Also, have you tested the responsiveness of the loader and other possible functionality breaks? Please attach a gif of the same as well(showing the responsiveness), if possible.

**Comment by mohit-003** [comment]
@Parikshit-Hooda Done!

**Comment by mohit-003** [comment]
Yes it is responsive as i gave all properties in percentages and it should work properly as fadein() and fadeout() has been used.

**Comment by mohit-003** [comment]
@Parikshit-Hooda should I make any other changes to it?

**Pull request closed without merging**
