### PR TITLE
stepper preview bug fixed

### LINKED ISSUE #96: Stepper does not work in Preview/Embed mode
Steppers do not seem to be responding to keyboard events in the preview window, even thou they appear selected when you click on them.

Repro:
- Navigate to a project that uses steppers, ex: https://circuitverse.org/users/1935/projects/5524
- In the preview pane, click one of the steppers (in this case, one of the two squares inside the pixel art box)
  - Stepper becomes yellow, indicating it is selected.
- Press up/down

Expected:
- For steppers to change value, as it happens in design mode.

Actual:
- No response from stepper.

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #96 

#### Describe the changes you have made in this pr -
added keydown2 and keydown3 eventListeners in embedListener.js 

### Screenshots of the changes (If any) -
screenshot from 2019-03-03 17-06-43

screenshot from 2019-03-03 17-11-17

### CODE REVIEW

**Comment by shubhankarsharma00** [comment]
@tachyons and @satu0king can you review this pr I'm not sure if I should have added keyDown3.

**Comment by armudgal** [comment]
Hi @shubhankarsharma00 , before working on any PR please make sure that you claim the issue as it might lead to duplicate PRs. Thanks

**Comment by shubhankarsharma00** [comment]
okay sure, btw what about the KeyDown3 does it need to be in preview mode?

**Comment by satu0king** [comment]
@shubhankarsharma00 Right now keydown3 is only used in the rectangle element, so no, it is not needed.

**Comment by shubhankarsharma00** [comment]
Okay I'll remove it. Does the rest of PR seem alright?

**Comment by shubhankarsharma00** [comment]
I am closing this pull request because of too many duplicate commits.

**Pull request closed without merging**
