### PR TITLE
User dashboard#2227

### PR DESCRIPTION
**Pull request by ankit80570**
Fixes #
#2227 
#### Describe the changes you have made in this PR -
Added Seach Icon for user dashboard
### Screenshots of the changes (If any) -
Search Icon

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by ankit80570** [comment]
@ShreyaPrasad1209  Can you check if this is good for merge?

**Comment by nitin10s** [comment]
The colour of the search icon should be the same as that of Search Circuits text and ideally should appear just before the placeholder text

**Comment by ankit80570** [comment]
> The colour of the search icon should be the same as that of Search Circuits text and ideally should appear just before the placeholder text
Any more changes?
image

**Comment by nitin10s** [comment]
Looks good to me 👍

**Comment by ankit80570** [comment]
> Looks good to me 👍

Gif for different screen sizes:
Search Icon

**Review by ShreyaPrasad1209 — APPROVED** [review]
Awesome work @ankit80570 🎉 I’ll merge this now

**Comment by ankit80570** [comment]
> Awesome work @ankit80570 🎉 I’ll merge this now

Thank you so much! 😄

**Pull request merged**
