### PR TITLE
Changed Fork to Create Copy for author

### LINKED ISSUE #1774: Fork Own Circuit Bug
**Describe the bug**
While saving the circuit, we get to see the Project Description, along with the Launch Simulator, Fork and Star Button, But Fork must only be implemented for other users forking our project or vice-versa. Currently Fork button is shown for my very own project in the Project description page and the View Modal in the Dashboard. 

**To Reproduce**
1. Go to 'circuitverse.org or beta.circuitverse.org'
2. Create a Circuit -> Save It
3. Go to Project Description

**Expected behavior**
Fork button should be renamed as "Create Copy" for own circuits both in the project description and the view modal.

**Screenshots**
image
image

**Device Information [optional]:**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by surbhigoel191**
Fixes #1774 

#### Describe the changes you have made in this PR -
Renamed Fork button to Create Copy if the signed in user is author of the circuit.

### Screenshots of the changes (If any) -
image

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by nitin10s** [comment]
Why the change?

**Comment by surbhigoel191** [comment]
> Why do we need the change?
Umm.. because it's asked in the issue to do so?
Have I misunderstand anything?

**Comment by surbhigoel191** [comment]
> Why do we need the change?

Umm.. because it's asked in the issue to do so?

**Comment by shreenanda-8** [comment]
May I know why merging is blocked?

**Comment by surbhigoel191** [comment]
> May I know why merging is blocked?

Because it's not approved yet and only the authorised users can merge after reviewing.

**Comment by satu0king** [comment]
I think this issue is okay to merge. It shows create copy for the current user's projects and fork for others. The main issue is that it shows forked later, but I think that's okay. 

@Shivansh2407 if you approve, we can merge.

**Review by Shivansh2407 — APPROVED** [review]
Great work @surbhigoel191 🎉 Looks good to me! This PR can be merged @satu0king .

**Comment by tachyons** [comment]
Thanks for the contribution, this is already implemented from another PR

**Pull request closed without merging**
