### PR TITLE
Update _footer.html.erb

### LINKED ISSUE #528: Unwanted div at the bottom of the page
**Describe the bug**
There is an empty space from the pagination links which is not required and actually looking bad in the mobile view of the website. That extra space is due to an empty *div* of a height of 250 pixels. That div ( of class name *container* ) is not required as it is not looking good in the Mobile view. 
 
**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to the end of the website
3. See the extra space which is not required.

**Expected behavior**
The unwanted div should either be removed and its display should be set to none in the Mobile view of the website.

**Screenshots**
Screenshot from 2019-11-05 21-49-18

**Desktop:**
 - OS: Ubuntu
 - Browser: Google Chrome
 - Version 77.0.3865.120 

**Are you working on this issue? (Yes/No)** No, this issue is for GCI students.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #528 Unwanted div at the bottom of the page 

#### Describe the changes you have made in this pr -
I have removed an unwanted div in the footer . I think so it is fine to remove it completely or else we could also decrease its height. 
Please let me know your views.

- [X] All Checks Passed.

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@Shivansh2407 this is not a issue. The div was left for the footer. This is being done on this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/846)

**Comment by tachyons** [comment]
@Abhiram-vv @vishnu-v-v Added by you ?

**Comment by Abhiram-vv** [comment]
@tachyons  this div was previously there to manage the footer position. and I believe we can't remove it for now, because if we remove it then in the other page's the footer will overlap the content in some cases.

**Comment by tachyons** [comment]
So what us a

**Comment by nitin10s** [comment]
@tachyons Why did you reopen?

**Comment by tachyons** [comment]
I don't remember :D. Closing

**Pull request closed without merging**
