### PR TITLE
Fix image loading issue 

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes https://circuitverse-team.slack.com/archives/CJTJJ6XN0/p1583742965185900

#### Describe the changes you have made in this PR -
I have tried to add `image_tag` instead of `img src` and also have removed assets from image source.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@tachyons I have made the changes. Please let me know if I have left any file here. Please review this 👍

**Comment by darkshredder** [comment]
assignment details page also needs to be fixed

**Comment by Shivansh2407** [comment]
> @Shivansh2407 assignment details page also needs to be fixed

It is fixed. See on Gitpod . Screenshot below :
Capture

**Comment by darkshredder** [comment]
okay cool

**Pull request merged**
