### PR TITLE
Update dependencies of yarn tests

### LINKED ISSUE #3507: yarn tests for simulator are failing
**Describe the bug**
yarn tests are failing due to canvas node modules

**To Reproduce**
1. Go to Terminal.'
2. Run 'yarn run test'
3.  See the error

**Expected behavior**
The Canvas node module needs to update for passing all the tests.

**Screenshots**
Screenshot (1031)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser: Brave, Chrome

**Additional context**

**Are you working on this issue? 
  (Yes)

### PR DESCRIPTION
**Pull request by Prerna-0202**
Fixes #3507 

#### Describe the changes you have made in this PR -
I have updated the required dependencies of yarn as suggested in #3507 

### Screenshots of the changes (If any) -

Screenshot (1032)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by pulkit-30** [comment]
Thanks @Prerna-0202,

can you also fix these warnings by running `npx browserslist@latest --update-db`.

Screenshot 2023-01-22 at 1 07 54 PM

**Comment by pulkit-30** [comment]
few more changes:
- to speed up tests we can limit `maxWorkers` in [jest.config.js](https://github.com/CircuitVerse/CircuitVerse/blob/master/jest.config.js) file to 50%.
- in Gitpod, when we run tests by cmd `yarn run test`, then it run all tests available in root folder(backend tests + simulator tests), this can be fixed by updating `testMatch` path in [jest.config.js](https://github.com/CircuitVerse/CircuitVerse/blob/master/jest.config.js) file to `**/simulator/spec/**/*.spec.js`.

**Comment by Prerna-0202** [comment]
Done @pulkit-30

**Review by pulkit-30 — APPROVED** [review]
Great 🎉

**Comment by tachyons** [comment]
It seems that we are not running those tests in CI, could you please add them?

**Comment by Prerna-0202** [comment]
> It seems that we are not running those tests in CI, could you please add them?

@tachyons  Do you mean github actions/workflows?

**Comment by tachyons** [comment]
Yes

**Comment by Prerna-0202** [comment]
> It seems that we are not running those tests in CI, could you please add them?

@tachyons They are running for any change in the simulator/ directory only. I have checked it here 'https://github.com/Prerna-0202/CircuitVerse/pull/200'
Let me know If I am doing anything wrong.

**Comment by tachyons** [comment]
> > It seems that we are not running those tests in CI, could you please add them?
> 
> @tachyons They are running for any change in the simulator/ directory only. I have checked it here '[Prerna-0202#200](https://github.com/Prerna-0202/CircuitVerse/pull/200)' Let me know If I am doing anything wrong.

Does `yarn run test` run on CI?

**Review by tachyons — APPROVED** [review]

**Pull request merged**
