### PR TITLE
Added linters to gitpod via vscode extensions

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/990

#### Describe the changes you have made in this PR -
- Added linters to gitpod via vscode extensions
Linters added:
- ESlint
- Ruby rubocop
- scss-lint
- Ruby
- Solograph

### Screenshots of the changes (If any) -
- Screenshot of the Extensions tab in gitpod:
Screenshot (13)

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@tachyons Please review

**Comment by tachyons** [comment]
Can you add https://marketplace.visualstudio.com/items?itemName=castwide.solargraph as well ?

**Comment by tachyons** [comment]
And https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

**Comment by Ananthavijay** [comment]
All done @tachyons !

**Pull request merged**
