### PR TITLE
Better Project Edit Page

### LINKED ISSUE #509: Bootstrap missing in edit project
**Is your feature request related to a problem? Please describe.**
Bootstrap missing in update
update
 project in simulator.

**Describe the solution you'd like**
The above button should have bootstrap.

**Additional context**
Screenshot has been attached.

### LINKED ISSUE #712: Make the project information editing page look nicer
The project information editing page doesn't look very well styled and like it was rushed
firefox_2dp4nIVvgc

**Describe the solution you'd like**
- The 'Update Project' button should have a bootstrap class,
- There should be less of a space between the 'Description' label and WYSIWYG editor
- The scrollbars on the WYSIWYG editor should only be shown if needed
- There should be more padding in the top two input fields
- The blue colour in the WYSIWYG editor should be changed to something that follows the overall colours of the website. It looks a bit out of place

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by MrBartusek**
Fixes #712 (not fixed WYSIWYG but splited to another issue #830)
Fixes #509

#### Describe the changes you have made in this pr -

- JavaScript cleanup
- Added bootstrap classes to elements
- Clarifications

### Screenshots of the changes (If any) -
Note: On current master, this page looks different cause #829 (but that doesn't mean this pr is blocked)

before:
image

after:
image

### CODE REVIEW

**Comment by nitin10s** [comment]
Looks pretty good

**Comment by aayush-05** [comment]
@MrBartusek the dropdowns and the "cut text" button isn't working. Please check

**Comment by MrBartusek** [comment]
@aayush-05 i moved editor issues to #830

**Comment by tachyons** [comment]
Please resolve merge conflicts

**Comment by MrBartusek** [comment]
@tachyons done

**Comment by tachyons** [comment]
Awesome

**Pull request merged**
