### PR TITLE
favicon added

### LINKED ISSUE #125: CircuitVerse Favicon Logo
We have a decent CircuitVerse logo but we do not have a good square logo which can be used as favicon or for places we need a shorter form of the logo. 

Not sure what is needed. I am thinking similar to the current Favicon logo would do.

### PR DESCRIPTION
**Pull request by sarthak77**
Fixes #125

### CODE REVIEW

**Comment by agarwalrounak** [comment]
Hi @sarthak77! The format for Fixes # is `Fixes #n` where n is the issue number. This way the issue automatically closes when the pull request is merged.

**Comment by sarthak77** [comment]
> Hi @sarthak77! The format for Fixes # is `Fixes #n` where n is the issue number. This way the issue automatically closes when the pull request is merged.

Oh sorry!

**Comment by satu0king** [comment]
Did you design this favicon? @sarthak77

**Comment by sarthak77** [comment]
Just a reference from there.
That’s why named samplefavicon.ico
Are you looking for something like that?

**Comment by Parikshit-Hooda** [comment]
I think that the favicon should be made on similar principles as the big brands, like a couple of letter which can uniquely identify the tab. For example, Facebook, LinkedIn.

**Comment by sarthak77** [comment]
OK.
Will do that

**Comment by sarthak77** [comment]
img-4971

Sir is this prototype somewhat like what you are thinking?

**Comment by Parikshit-Hooda** [comment]
If we put this as a favicon, do you think it would distinguishingly identify CircuitVerse?

**Comment by shubhankarsharma00** [comment]
I think the favicon should be simple yet unique like the github octocat.

**Comment by sarthak77** [comment]
img-4971

Sir is this prototype somewhat like what you are thinking?

> If we put this as a favicon, do you think it would distinguishingly identify CircuitVerse?

Yeah, I guess it would be as the letters C and V would be more thick and would stand apart

**Comment by sarthak77** [comment]
> I think the favicon should be simple yet unique like the github octocat.

Sir but Parikshit sir had intended to use letters in the favicon like facebook linkedin etc do

**Comment by sarthak77** [comment]
> > I think the favicon should be simple yet unique like the github octocat.
> 
> Sir but Parikshit sir had intended to use letters in the favicon like facebook linkedin etc do

Any updates on this would be helpful.

**Comment by satu0king** [comment]
@sarthak77, Others and I have tried making smaller logo versions and favicons with "CV" as the design. However it doesn't look very good and when it is scaled down to the favicon size, it is downright ugly.

Your current design looks good, can we remove the part highlighted in red? 
image

I am quite happy with the current logo, It is elegant, simple and circuitlike. Even when scaled down to favicon size, the details are visible. The major problem is it was not designed for CircuitVerse and was copied from another website, this was in the initial stages of the project and was fine. However, as we are establishing as an opensource community, we should have our own logo void of any copyright issues. 
image

I did an image search and found the source: 
https://www.pinclipart.com/pindetail/oRxoRo_circuit-icon-clipart/
One option is to find the designer and request licensing, another option is to have a similar logo designed by contributors.

**Comment by sarthak77** [comment]
Yeah I can remove it and improve upon so it does not look bad on down scaling
Thanks for the feedback

**Comment by sarthak77** [comment]
img-4988
Sir its a rough prototype
Can you confirm it so that I start on it with appropriate tools

**Comment by armudgal** [comment]
@sarthak77 don't address anyone as Sir, the new design looks good.

@satu0king I don't think we will be in any trouble cause both the designs are derives using the PCB circuits, most of the org working on electronics tend to have a similar design either with a complex schematic or PCB structure. Still I would like to know your thoughts.

**Comment by sarthak77** [comment]
@armudgal can you review the pr

**Comment by armudgal** [comment]
@sarthak77 Hi, I am waiting for @satu0king approval on this.

**Comment by armudgal** [comment]
Further conversation to be carried out on #203

**Pull request closed without merging**
