### PR TITLE
Bump Omniauth fix

### LINKED ISSUE #2218: Bump omniauth version
Omniauth need to be upgraded to 2.x to fix a vulnerability. But this requires some code changes. Refer #2207

### PR DESCRIPTION
**Pull request by pavanjoshi914**
Fixes #2218 #2207 

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
4 days ago devise 4.8.0 was released with major fixes to enable omniauth 2.x.
It is working fine locally but appveyor is failing.
@tachyons?

**Comment by pavanjoshi914** [comment]
@tachyons why this was reverted ?

**Comment by tachyons** [comment]
Because this broke oauth login in production and people started complaining
about it. We made a mistake of not  properly testing this before merging
this

**Comment by tachyons** [comment]
Were you able to sign in with google on development environment ?

**Comment by pavanjoshi914** [comment]
I only done a check for this error   ```You are using an old OmniAuth version, please ensure you have 1.0.0.pr2 version or later installed```
Anyways I will check further and update you with it.

**Pull request merged**
