### PR TITLE
Fixed broken checkboxes in "add assignment"

### LINKED ISSUE #2466: Broken checkboxes
**Describe the bug**
Checkboxes are greyed in the browser

**To Reproduce**
1. Go to "My Groups"
2. Create a "New Group"
3. Add an "Assignment"
4. Scroll down  and check on 'Enable elements restriction'
5. See error

**Expected behavior**
login (1)

**Screenshots**
error

**Device Information [optional]:**
 - OS: Windows 10
 - Browser Chrome
 - Version  92.0.4515.159 

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Kartikay304**
Fixed #2466 

#### Describe the changes you have made in this PR -
Added styles for checkboxes in the assignment.scss

### Screenshots of the changes (If any) -
Before -
error

After -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by nitin10s — APPROVED** [review]
LGTM, @tachyons please merge. Also, we have checkboxes at left and text at right everywhere but the login screen. We'll need to change it there as well. [ofcourse a separate issue]

**Comment by Kartikay304** [comment]
> LGTM, @tachyons please merge. Also, we have checkboxes at left and text at right everywhere but the login screen. We'll need to change it there as well. [ofcourse a separate issue]

Should I raise a separate issue for the position of remember-me check box on login screen.

**Comment by Kartikay304** [comment]
> > Can you post the screenshot from firefox as well ?
> 
> Sure,
> 
> firefox

@tachyons

**Comment by tachyons** [comment]
Need to check if original design was intentional

**Review by nitin10s — APPROVED** [review]
This looks good to me, the previous design wasn't intentional, I designed it this way but it wasn't properly developed. @tachyons please check and merge.

**Pull request merged**
