### PR TITLE
Feature: Date Created and Date Modified in project show page

### PR DESCRIPTION
**Pull request by raffayatiq**
Fixes #
A fix to this issue: #2047 
Original PR: #2052 

#### Describe the changes you have made in this PR -
I have added Date Created and Date Modified functionality in Project show page, according to relative and absolute time in the way Github does it.
About the code I added to en.yml: time_ago_in_words() (as well as the similar function distance_of_time_in_words) returns the time as "about x hour" or "less than x minutes" etc. I wanted to cut out these words like "about" and "less than" in order to display time exactly the way Github does. Since time_ago_in_words() and similar "time ago" functions use localization keys, I have overridden them in en.yml to display the time exactly the way Github displays it, in an i18n-safe way.

### Screenshots of the changes (If any) -
Screenshot from 2021-03-17 19-41-46

Screenshot from 2021-03-17 20-06-22

Screenshot from 2021-03-17 19-58-11
Screenshot from 2021-03-17 20-04-43

I have also added functionality to show the complete time stamp when you hover over the date:
Screenshot from 2021-03-17 19-58-24
It is in UTC +00:00 timezone because Rails stores time in the database in this timezone. I can make it show the time stamp in the user's own timezone but there are multiple ways to implement it. If it needs to be done, here is how I think we can show it in the user's timezone:

1) At the backend, we can store users' timezone in the users table when they sign up. Users can change this timezone any time.
2) At the frontend, we can use JavaScript to detect the timezone of a user and change it. I've searched about this and this seems to be the preferred way, although it might be a little complex.

If it needs to be done, I can get started on this. Although, the timezone is only shown when a user hovers over the Date Created and Date Modified time.

### CODE REVIEW

**Review by satu0king — CHANGES_REQUESTED** [review]
Looks neat!
But I think it is better to use

Created: 
Updated: 

Instead of 
Date Created: and
Last Modified

CC @Shivansh2407

**Comment by raffayatiq** [comment]
> Looks neat!
> But I think it is better to use
> 
> Created:
> Updated:
> 
> Instead of
> Date Created: and
> Last Modified
> 
> CC @Shivansh2407

Yes that does look better. But there is just one thing:
image
What about the extra space before the colon? For example there is an extra space before the label's colon i.e. "Author : " and "Project access type : ". Should I get rid of the space? So that the labels become "Author: user1" and "Project Access Type: Public". Personally I think we should and also capitalize the 2nd label.

**Comment by nitin10s** [comment]
Yes, please get rid of the extra space in other fields, and 2nd label seems fine, we need not capitalize each word.

**Review by Shivansh2407 — APPROVED** [review]
Great Work @raffayatiq 🎉 Looks good to me @satu0king 👍

**Comment by raffayatiq** [comment]
@Shivansh2407 Thank you! :slightly_smiling_face:

**Pull request merged**
