### PR TITLE
added bootsrap '.text-center' class to tos & pp para

### PR DESCRIPTION
**Pull request by abstrekt**
No issues was created

#### Describe the changes you have made in this PR -
text centered the terms of service & privacy policy
### Screenshots of the changes (If any) -
about

### CODE REVIEW

**Comment by aayush-05** [comment]
Please refer to the prototype pinned on the #ux channel on slack. This isn't a required change.

**Comment by abstrekt** [comment]
> Please refer to the prototype pinned on the #ux channel on slack. This isn't a required change.

I actually did referred to the prototype,  I had left a comment there about it,  thought the page would look better with these two centred.
Still I shall close this PR if the change is really not required.
@nitin10s

**Comment by tachyons** [comment]
Can you add screenshot for before and after

**Comment by abstrekt** [comment]
# screenshot before 
Screenshot_2020-03-05-11-06-16-72~01

**Comment by tachyons** [comment]
This looks better as everything else in this page is center aligned

**Comment by tachyons** [comment]
Thanks for the clarification, we can review this later

**Pull request merged**
