### PR TITLE
Added buttons instead of png images

### LINKED ISSUE #258: Improve buttons for third party log in
**Is your feature request related to a problem? Please describe.**
Currently, we have a png image of a login button for google and facebook and a link which leads us to the OAuth page.

google_signin

**Describe the solution you'd like**
It will be much better if we can use actual buttons instead of png images.

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by creyente1897**
Fixes #258 

#### Describe the changes you have made in this pr -
I have added buttons for the third party login instead of png buttons for third-party login.
### Screenshots of the changes (If any) -
Peek 2019-03-16 15-56

### CODE REVIEW

**Comment by monsij** [comment]
Shouldn't both be made `Sign In` or `Log In` ? @creyente1897

**Comment by creyente1897** [comment]
@monsij Yes you are right but currently the buttons are in the links view which is a common view for both registration and login as well.That is why buttons for both the view are same.
@satu0king Should I include the buttons in both the pages seperately or not.

**Comment by satu0king** [comment]
@creyente1897, In both pages, let it be `Log In with Google` and `Log In with Facebook`. I agree with @monsij that it should be uniform. Even if the user is visiting the website for the first time, login with Google/Facebook should work automatically.

**Comment by satu0king** [comment]
Resolve the conflict and we are good to merge.

**Comment by creyente1897** [comment]
I guess I pushed all the pulled changes I am sorry for that.
I will make another pr for only the included changes

**Pull request closed without merging**
