### PR TITLE
Add more delimiters to email splitting for collaborators and groups

### LINKED ISSUE #92: Allow emails to be separated by space/commas - collaborations/group invitations

### PR DESCRIPTION
**Pull request by ankitkataria**
Fixes #92

### CODE REVIEW

**Comment by satu0king** [comment]
Does this split newline also? That is if emails are given separately on newlines ?

**Comment by ankitkataria** [comment]
@satu0king, Yes this will also handle emails input in different lines. 
`\s` will split the emails around any whitespace character i.e `\r \n \t \f \v`

**Comment by satu0king** [comment]
Thanks! 

> Yes this will also handle emails input in different lines.
`\s` will split the emails around any whitespace character i.e `\r \n \t \f \v`

Could you update the form to say that it can be separated by newline too?

**Comment by ankitkataria** [comment]
Sure! Will make a PR asap.

**Pull request merged**
