### PR TITLE
Fixes redirect to simulator after logging in from simulator 

### LINKED ISSUE #1383: Problems with Login in Simulator
****Describe** the bug**
As of now, when the user is on Simulator and clicks for Login, the user gets redirected to the homepage.

**Expected behavior**
He/She should be redirected to the simulator screen itself.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1383 

#### Describe the changes you have made in this PR -
I have fixed the issue and now the user is redirected to the simulator screen whenever the user logs in through simulator .
This will also help the user to redirect to the page wherever he was , just before signing in.
### Screenshots of the changes (If any) -
Patch44

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@nitin10s @tachyons @satu0king Please review this 👍

**Comment by Shivansh2407** [comment]
@nitin10s @tachyons @satu0king please review this 👍

**Comment by Shivansh2407** [comment]
The Code Climate Issues are fixed @nitin10s 👍

**Comment by abstrekt** [comment]
Mergeable, @tachyons  @satu0king @tachyons

**Comment by tachyons** [comment]
Can you add tests for this behaviour ?

**Comment by Shivansh2407** [comment]
> Can you add tests for this behaviour ?

I will look into it and let you know 👍

**Comment by nitin10s** [comment]
@Shivansh2407 are you working on this?

**Comment by Shivansh2407** [comment]
@shubhankarsharma00 is going to take up the tests part and open up a new PR for the same @nitin10s 👍

**Comment by shubhankarsharma00** [comment]
Isn't aayush setting something similar up? Correct me if I am wrong but This is probably gonna be redundant if we have modals for sign in.

**Comment by satu0king** [comment]
@aayush-05 can you check this PR and see if we can merge this.

**Review by aayush-05 — APPROVED** [review]
Works fine @satu0king. A redirection test can be added

**Pull request merged**
