### PR TITLE
Added Date Created and Date Modified below project description

### PR DESCRIPTION
**Pull request by raffayatiq**
Fixes #
A fix to this issue: https://github.com/CircuitVerse/CircuitVerse/issues/2047
#### Describe the changes you have made in this PR -
I have added Date Created and Date Modified below the project description so that users can see when a project was made and when it was last modified.
### Screenshots of the changes (If any) -
image

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by nitin10s — APPROVED** [review]

**Comment by satu0king** [comment]
@raffayatiq this is good but I am thinking, is it was smarter at showing the time of creation/updated. For example, this is what github does. 

For many days difference, it shows this 
image

For a few days 
image

image

For very less time, it shows 
image

So the point is just having date + time, is not helpful. Having it relative for short time difference is helpful. And having it absolute for short time difference is helpful. And if its >= 1 day, no need to show the time, the date/number of days will suffice. 

CC: @Shivansh2407 , please add your views.

**Comment by nitin10s** [comment]
@satu0king, wouldn't this affect professors grading the students' assignments if we show date in this way? I am not sure.

**Comment by Shivansh2407** [comment]
True @satu0king we can show the relative time instead of the complete Timestamp . Also @nitin10s from the professor's perspective, we can do it again as Github does, by showing the complete timestamp on hovering for reference and just the relative time below project description. I think this should not create any issue. Please let me know your views on this !

image

**Comment by nitin10s** [comment]
Strange thing, before you mentioned it, I didn't even know we could hover on it to view the complete timestamp 😱

**Comment by raffayatiq** [comment]
@satu0king @Shivansh2407, these are all great ideas! I just had one question, when should I make the time absolute? Can you give me a limit? For example, I can make the time relative for when day < 7 e.g.. "12 hours ago", "6 days ago" etc. But when the day >= 7, I will show the absolute time e.g. Feb 25, 2021.

**Comment by Shivansh2407** [comment]
@raffayatiq for showing the absolute time, we can set day >=14, I guess that would be great. Let me know your views on this @satu0king

**Comment by satu0king** [comment]
> @raffayatiq for showing the absolute time, we can set day >=14, I guess that would be great. Let me know your views on this @satu0king

Completely agree with this. @nitin10s , profs don't care about when the assignment was done as it will be done before the deadline.

**Comment by raffayatiq** [comment]
@satu0king Got it. I will get started on this.

**Comment by tachyons** [comment]
Something like [this](https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words) ?

**Comment by tachyons** [comment]
Also have look at [this](https://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-distance_of_time_in_words)

**Comment by satu0king** [comment]
@raffayatiq I believe u raised a new PR to replace this one? Feel free to close this PR then.

**Pull request closed without merging**
