### PR TITLE
Add Recent Circuits

### LINKED ISSUE #1058: Recent circuits not being shown in Homepage
**Describe the bug**
Recent circuits not being shown in Homepage

**To Reproduce**
1. Start the server
2. Scroll down 
3. See error

**Expected behavior**
Recent circuits should be shown in Homepage

**Screenshots**
image

**Desktop (please complete the following information):**
 - Environment: Gitpod
 - Browser: chrome

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1058 

#### Describe the changes you have made in this PR -
I have added the recent circuits section to the Homepage.

### Screenshots of the changes (If any) -
Capture

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@tachyons and @nitin10s review 👍

**Comment by nitin10s** [comment]
Let's put this feature request on hold for some time.

**Comment by nitin10s** [comment]
@Shivansh2407 Are you working on this?

**Comment by Shivansh2407** [comment]
Yes @nitin10s I have completed the work .Sorry for the delay. I will push the changes soon👍

**Comment by Shivansh2407** [comment]
Yes @nitin10s I have completed the work .Sorry for the delay. I will push the changes soon👍

**Comment by Shivansh2407** [comment]
@nitin10s Pagination is added . Please review and merge 👍

**Comment by Shivansh2407** [comment]
Recent_Circuits
Updated the Screenshot. Please review @nitin10s

**Comment by Shivansh2407** [comment]
I have closed the div tags. Please review and merge @nitin10s 👍

**Comment by Shivansh2407** [comment]
Please Review @nitin10s 👍 .It is now fixed .

**Comment by nitin10s** [comment]
I still can't see page numbers.

**Comment by Shivansh2407** [comment]
@nitin10s please review 👍

**Pull request merged**
