### PR TITLE
added checkbox styling & changes assignment checkbox menu to toggle

### LINKED ISSUE #1167: Checkboxes Not Styled
**Problem**
The checkboxes in new UI don't have any styling. Needs to be done at all pages. 

**Are your working on the issue**
No

### PR DESCRIPTION
**Pull request by abstrekt**
Fixes #1167

#### Describe the changes you have made in this PR -
added styling to the checkbox to sign in & edit page
### Screenshots of the changes (If any) -

CircuitVerse - Digital Circuit Simulator

Firefox_Screenshot_2020-03-20T12-18-13 714Z

### CODE REVIEW

**Comment by abstrekt** [comment]
new PR for #1259 ,
It is mergeable I believe
@nitin10s could you please review it once again?

**Comment by abstrekt** [comment]
I have done this for sign in page & edit page, if I have missed any page please do let me know. @nitin10s

**Comment by nitin10s** [comment]
It's in make assignment page as well. Why do you need to specifically make changes for each checkbox, can't we have define a global style for all the checkboxes at once?

**Comment by abstrekt** [comment]
It's a bit tricky to style a checkbox that much or I guess not possible rather than to just scale it up, so I hid the actually checkbox & made a custom checkbox with ```::after``` pseudo class of the hidden checkbox to match the theme.
I tried having a global style for all the checkbox but code climate don't allow to use ```input[type=checkbox]``` selector in sass stylesheet but still, the checkbox styling is global you can say one need to change the styling of the sass file & it will change all the checkboxes, the
only changes that are required to be done are add the classes,
while the margins & padding on the different checkboxes of different pages are not uniform, things looked odd after I styled it.
@nitin10s

**Comment by nitin10s** [comment]
There is one in the Make Assignment page.

**Comment by abstrekt** [comment]
> 
> 
> There is one in the Make Assignment page.

on it!

**Comment by abstrekt** [comment]
should we leave these checkboxes the way they are?
Firefox_Screenshot_2020-03-24T09-11-27 985Z
@nitin10s

**Comment by nitin10s** [comment]
Yes, leave these

**Comment by abstrekt** [comment]
@nitin10s 
will this work?
Firefox_Screenshot_2020-03-24T10-28-34 800Z
Firefox_Screenshot_2020-03-24T10-29-33 085Z

**Comment by abstrekt** [comment]
```Failure/Error: check "restrict-elements"

Selenium::WebDriver::Error::ElementClickInterceptedError:
  element click intercepted: Element <input type="checkbox" name="restrict-elements" id="restrict-elements" value="1" class="check-box"> is not clickable at point (164, 750). Other element would receive the click: <label for="restrict-elements" class="checkmark">...</label>
    (Session info: chrome=80.0.3987.149)



#0 0x55dd71ea7d29 <unknown>
./spec/system/assignment_spec.rb:86:in `fill_assignments'
./spec/system/assignment_spec.rb:54:in `block (3 levels) in <top (required)>'```

what does ```is not clickable at point (164, 750).``` means?

**Comment by nitin10s** [comment]
@tachyons

**Comment by tachyons** [comment]
Means item is not active, you can add a binding.pry to debug

**Comment by abstrekt** [comment]
@tachyons @nitin10s 
checkboxes can only be styled by hiding the original checkbox & replacing with a custom one, worked fine in other places with ```f.check_box``` , but in this page hiding the original ```check_box_tag``` fails these checks,  idk what to do,

**Comment by abstrekt** [comment]
wow, test passed! we might have a solution, hold on.

**Comment by abstrekt** [comment]
@nitin10s @tachyons 
Changed the checkbox to toggle & working fine.
screen-capture (8)

**Comment by abstrekt** [comment]
@nitin10s 
added unified class to add to any checkbox, added the class to all checkboxes I guess

**Comment by aayush-05** [comment]
Good work @abstrekt ; although this has been implemented now in the new UI. So this one can be closed @tachyons @nitin10s

**Pull request closed without merging**
