### PR TITLE
Fix incomplete circuit draw on combinational analysis

### LINKED ISSUE #1651: Combinational Analysis tool fails due to an independent output
**Describe the bug**
If the Combinational Analysis tool is asked to create a circuit where one or more of the outputs are not dependent on an input, it outputs nothing or a partial circuit.

**To Reproduce**
I encountered this behavior trying to generate the circuit for a 7-segment decoder, but limited to the states 0-3.  The issue is that the b segment in this case is "degenerate" per Issue #659 - the output is not dependent on the input.  Yes, we could expect the user to notice that, but it is also possible that someone just learning Digital Logic would be confused as to why a 7-segment decoder would work if configured for 0-7 or 0-F, but fail when configured for 0-3.

Steps to reproduce the behavior: (simple case)
1. Go to Tools > Combinational Analysis
2. set the input to "i", and output to "o", and click Next
3. configure the output as shown
```
 i | o
---+---
 0 | 1 
 1 | 1 
```

Steps to reproduce the behavior: (actual case)
1. Go to Tools > Combinational Analysis
2. set the inputs to "i, j", and outputs to "a,b,c,d,e,f,g", put a check for the decimal column, click Next
3. configure the outputs as shown
```
dec | i | j | a | b | c | d | e | f | g
----+---+---+---+---+---+---+---+---+---
  0 | 0 | 0 | 1 | 1 | 1 | 1 | 1 | 1 | 0
  1 | 0 | 1 | 0 | 1 | 1 | 0 | 0 | 0 | 0
  2 | 1 | 0 | 1 | 1 | 0 | 1 | 1 | 0 | 1
  3 | 1 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 1
```
4. click Next

**Expected behavior**
I expect that the Combinational Analysis tool will generate a valid circuit for the dependent outputs even in the presence of independent outputs, and warn the user of the presence of any independent outputs.

I am not working on the issue.

### PR DESCRIPTION
**Pull request by gr455**
Fixes #1651

#### Describe the changes you have made in this PR -
combinationalAnalysis.js: Added a patch to handle cases where output is independent of input(all DONT CAREs).
Added comments describing the working of the draw function.

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by satu0king** [comment]
Thank you for this contribution, however we are actually in the process of migration, so merging this PR would be difficult. Could you send a PR to new_UI branch instead?

**Comment by gr455** [comment]
> Thank you for this contribution, however we are actually in the process of migration, so merging this PR would be difficult. Could you send a PR to new_UI branch instead?

Sure

**Comment by satu0king** [comment]
@gr455 , the code in new_UI branch is in public/src folder instead of public/js

**Comment by gr455** [comment]
> @gr455 , the code in new_UI branch is in public/src folder instead of public/js

Should I close this PR in favour of the new one then?

**Comment by satu0king** [comment]
> > @gr455 , the code in new_UI branch is in public/src folder instead of public/js
> 
> Should I close this PR in favour of the new one then?

yes

**Comment by gr455** [comment]
Moved to #1678

**Pull request closed without merging**
