### PR TITLE
Integrate Undercoverci

### LINKED ISSUE #3816: Integrate Undercover CI
Integrate Undercover CI to check untested code of commit

### PR DESCRIPTION
**Pull request by tanmoysrt**
Fixes #3816 

#### Describe the changes you have made in this PR -
- Enable Simplecov to generate results in *.lcov
- Integrate undercover CI to workflow to report issues

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tachyons** [comment]
Undercover CI is expensive, we need to use this tool without their saas product

**Comment by tanmoysrt** [comment]
> Undercover CI is expensive, we need to use this tool without their saas product


> Undercover CI is expensive, we need to use this tool without their saas product

**Comment by tanmoysrt** [comment]
> Undercover CI is expensive, we need to use this tool without their saas product

Removed Undercover CI and used https://github.com/aki77/undercover-checkstyle with reviewdog to provide PR Review

Currently, it's working fine to detect issues & have set the level to `warning`

But it says it can't get a github_token to review, So I can't verify whether it's working. Will it resolve after merging only?
image

**Comment by tanmoysrt** [comment]
Verified this by running in a seperate fork 
You can check it here: https://github.com/KampusVire/CircuitVerse/pull/2#discussion_r1237582074

**Comment by tanmoysrt** [comment]
> Undercover CI is expensive, we need to use this tool without their saas product

Replaced Undercover CI with [undercover-checkstyle](https://github.com/aki77/undercover-checkstyle) with reviewdog.
This working fine I think.
I have tried out here in a fork https://github.com/KampusVire/CircuitVerse/pull/6 , it will raise an error in workflow on finding any issue as well as will comment the issues of PR

**Comment by tachyons** [comment]
Great job

**Pull request merged**
