### PR TITLE
Fix footer links

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/975

#### Describe the changes you have made in this pr -
- Changed absolute urls to relative urls
- Made some links to open in another tab

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@tachyons Please review

**Comment by Ananthavijay** [comment]
Should these links be made to open in a new tab?
- IIITB
- Digital Ocean
- Istudio
- Zense

**Comment by tachyons** [comment]
Yes

**Comment by Ananthavijay** [comment]
All done @tachyons

**Pull request merged**
