### PR TITLE
fix:timing diagram panel width overflow

### PR DESCRIPTION
**Pull request by NamitBhutani**
Fixes #

#### Describe the changes you have made in this PR -
Edited plotArea.js to limit maximum width of the panel based on current position and screen width.
### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by NamitBhutani** [comment]
could you please review this @tanmoysrt

**Comment by tanmoysrt** [comment]
> could you please review this @tanmoysrt

Simulator PR's will be reviewed by @Prerna-0202 @Arnabdaz

**Comment by Arnabdaz** [comment]
can you link the issue i think it was already fixed

**Comment by NamitBhutani** [comment]
> can you link the issue i think it was already fixed

https://github.com/CircuitVerse/CircuitVerse/issues/4420 This was the issue!

**Pull request closed without merging**
