### PR TITLE
[GCI] Migrate carrierwave and paperclip to activestorage

### LINKED ISSUE #371: Migrate from PaperClip to Active Storage
**Is your feature request related to a problem? Please describe.**
Paperclip is [deprecated](https://thoughtbot.com/blog/closing-the-trombone)

**Describe the solution you'd like**
Follow this migration [guide](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md)

**Are you working on this? (Yes/No)**

No

### PR DESCRIPTION
**Pull request by junron**
Fixes #371

#### Describe the changes you have made in this pr -
Switch from carrierwave/paperclip to ActiveStorage.
Added view helper to render default images.
Coverage increased. 😊

[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/6505098130227200/)

### CODE REVIEW

**Comment by junron** [comment]
Please have a look @tachyons @tonyvince

**Comment by junron** [comment]
@tachyons I think we can ignore the hound violations, I didn't change any `.erb` files

**Comment by junron** [comment]
@tachyons @tonyvince Plesse review

**Comment by junron** [comment]
So this mechanism should run on startup or be run manually?

**Comment by tachyons** [comment]
To be run manually, you can find one approach in the link provided with task description

**Comment by junron** [comment]
I'll put it in a rake file

**Comment by junron** [comment]
It seems we would need CarrierWave and ActiveStorage to both be present for the migration. Is my understanding correct?

**Comment by junron** [comment]
@tachyons Can I have some help?

**Comment by junron** [comment]
Also the profile picture update doesn't seem to be working on the master branch

**Comment by junron** [comment]
@tachyons I'll be away for the next week, so I cannot submit this task until I come back. Maybe it is better some one else take this up instead?

**Comment by tachyons** [comment]
You already made good progress on this, may be we can make migrating existing files to new task

**Comment by junron** [comment]
@tachyons The problem is I can't access my account because I forgot to bring my 2FA device, so I can't submit the task

**Comment by junron** [comment]
@tachyons Is it possible to extend the task deadline to 22nd December, I'll be back by then

**Comment by junron** [comment]
@tachyons  Is it possible to extend?

**Comment by tachyons** [comment]
Done

**Comment by junron** [comment]
Ok so I ran the migrations from https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md, and it ran without errors, but the active_storage_attachments table is still blank. 

@tachyons?

**Comment by junron** [comment]
The solution involves 2 PRs, and the order they are merged is very important.
The migration involves 2 parts:
1. Migrating table data
2. Moving the files

The first part requires both activestorage and paperclip to be installed at the same time, as it involves methods from both packages. Paperclip is removed in the second part, therefore performing the second part before the first part causes an error.

This is how the migration should be performed:

1. Merge #753 
2. Run `rails db:migrate`
3. Run `rake activestorage:migrate`
4. Merge #730 (this PR)
5. Run `bundle install` 
6. Run `rake activestorage:migratefiles`

**Comment by junron** [comment]
@tachyons Please review

**Comment by tachyons** [comment]
Please resolve conflicts

**Comment by junron** [comment]
Ok

**Comment by junron** [comment]
Note that #753 should be merged first

**Pull request closed without merging**
