### PR TITLE
Adds Check for group mentor in entered emails for new group member

### LINKED ISSUE #1191: Mentor should not be able to add himself as a member of the same group
**Describe the bug**
The mentor should not be able to add himself as a student of the same group

**To Reproduce**
1. Go to circuitverse.org
2. Create a Group
3. Click Add members
4. Add the email with which you have created the group

**Screenshots**
Screenshot (54)_LI

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by Nitish145**
Fixes #1191 

#### Describe the changes you have made in this PR -
Added a check for equality of *mentor_id* and *group_id* while adding members..

### CODE REVIEW

**Comment by Nitish145** [comment]
@Ananthavijay What do u suggest should be done if grp mentor tries to add himself as grp member ?

**Comment by Ananthavijay** [comment]
idk, may be an error?

**Comment by Nitish145** [comment]
> idk, may be an error?

How abt adding *Also, group Mentor cannot be added to group members* in the email utils notice..
@Ananthavijay @nitin10s ?

**Comment by Nitish145** [comment]
Screenshot from 2020-03-16 11-00-27

**Comment by Ananthavijay** [comment]
something like "Mentor cannot be added as a member of the same group"? And also add tests

**Comment by Nitish145** [comment]
@tachyons @Ananthavijay @nitin10s how do i tackle cognitive complexity issue ?

**Comment by Nitish145** [comment]
@tachyons @nitin10s reviews please :)

**Comment by yash15601** [comment]
@Nitish145  i think these is because your code is difficult to test

**Comment by yash15601** [comment]
@Nitish145  I don't  about your code but try using methods m sure will reduce the complexity

**Comment by satu0king** [comment]
Not sure if this check is necessary but yes it can lead to confusion and yes while the backend allows mentors to be a member, the UI doesn't support it.

**Comment by Nitish145** [comment]
Should i then fix the complexity issue or not ?

I think i will shortly and some appropriate tag to this PR will do..

**Pull request closed without merging**
