### PR TITLE
Changed no dp default

### LINKED ISSUE #1167: Checkboxes Not Styled
**Problem**
The checkboxes in new UI don't have any styling. Needs to be done at all pages. 

**Are your working on the issue**
No

### PR DESCRIPTION
**Pull request by abstrekt**
temporary Fix 
#1167 

#### Describe the changes you have made in this PR -
* maybe just a temporary fix to issue #1167, about the checkbox
* changed the no dp default.jpg 
### Screenshots of the changes (If any) -
display

### CODE REVIEW

**Comment by abstrekt** [comment]
Sorry about these old commits, I don't know how to rebase these
@nitin10s

**Comment by yash15601** [comment]
@abstrekt  looks great  @nitin10s  review

**Comment by abstrekt** [comment]
I'm not sure what's causing the conflict @nitin10s  is it because that default.jpg is actually default.png, I just renamed it to .jpg?

**Comment by nitin10s** [comment]
@tachyons

**Comment by satu0king** [comment]
The conflict is there because master has also modified the images and so have you. No not the file names. You can resolve this by syncing your branch with base master. 
`git pull https://github.com/CircuitVerse/CircuitVerse.git master`

**Comment by abstrekt** [comment]
Merge conflicts has now been resolved.
btw merging this will create another small bug in the comment section, I'm not sure where to resolve that in the erb file just need to mention a width styling, I will create the issue, someone familiar with rails will hopefully fix it.

**Comment by abstrekt** [comment]
created new PR for this #1266

**Pull request closed without merging**
