### PR TITLE
Improved installation instructions

### PR DESCRIPTION
**Pull request by falguniraina**
A minor change in docs to make it easy to copy one file to another. Thanks!

### CODE REVIEW

**Comment by falguniraina** [comment]
> cp command is not available for windows

Actually this is my first pr so could you please suggest me the changes i am supposed to make for this to get merged!!

**Comment by Ananthavijay** [comment]
I think this change is not required or add a line saying that ````If you are not a windows user this command can be used````

**Comment by tachyons** [comment]
We support multiple operating systems. 'cp' command is only available in Unix like oses like Linux and Mac OSx. So having cp command can potentially confuse windows users. You can rephrase the paragraph to avoid that confusion

**Comment by aayush-05** [comment]
@falguniraina are you still working on this ?

**Comment by aayush-05** [comment]
@nitin10s can we close this one; inactive since a long time?

**Pull request closed without merging**
