### PR TITLE
readme of install bundler

### PR DESCRIPTION
**Pull request by sgpritam**
Fixes #  issue #619 Readme of `install Bundler`

#### Describe the changes you have made in this pr -
Create a `Bundler.md` file

### CODE REVIEW

**Comment by tachyons** [comment]
It is just a matter of adding gem install bundler, not copy lasting whole bundler doc here

**Comment by sgpritam** [comment]
Merging is blocked

**Comment by sgpritam** [comment]
a

**Comment by Ananthavijay** [comment]
@tachyons this can also be closed

**Pull request closed without merging**
