### PR TITLE
Line breaks not saved in descriptions fixed#2394

### LINKED ISSUE #2394: Breaks are not saved in descriptions
**Describe the bug**
Breaks are deleted from descriptions

**To Reproduce**
Enter a break into a description (either by shift + enter, or by adding <br> into the markup)
Save the description
Observe how the break is gone

**Expected behaviour**
The breaks are saved since they help format descriptions

**Device Information [optional]:**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Retroactively affects old descriptions as well

**Are you working on this issue? No**

### PR DESCRIPTION
**Pull request by rachit3006**
Fixes #2394
#### Describe the changes you have made in this PR -
The line breaks are now saved and are displayed in the descriptions of projects and assignments. Added the br tag while sanitizing description in assignments_controller.rb and projects_controller.rb.
### Screenshots of the changes (If any) -

editing

description

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by vedant-jain03 — APPROVED** [review]

**Review by Kartikay304 — APPROVED** [review]

**Comment by rachit3006** [comment]
@Kartikay304 or @vedant-jain03 I think this pull request can be merged. If there is something I need to update please inform me.

**Comment by tachyons** [comment]
Can you add a test for this?

**Comment by rachit3006** [comment]
@tachyons can you check if the test is valid?

**Comment by rachit3006** [comment]
can anyone check if the test is valid?

**Review by tachyons — APPROVED** [review]
LGTM, can be merged after fixing codeclimate issues

**Comment by rachit3006** [comment]
I have fixed the code climate issues. @tachyons can you please review them and update me if any more changes are needed?

**Comment by tachyons** [comment]
Great, thanks 👍

**Comment by rachit3006** [comment]
Thanks for all the help and guidance!

**Pull request merged**
