### PR TITLE
Fixed Alignment issue

### LINKED ISSUE #1291: Alignment Issue of Title in Mobile View
**Describe the bug**
alignment issue in magin of Title of Project in mobile view.

**To Reproduce**
1. Go to 'Simuator in Mobile view'
2. Click on 'Hamburger button'
3. See error

**Screenshots**
RvsyS6O - Imgur

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser - Chrome

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Sj1218305**
Fixes #1291

#### Describe the changes you have made in this PR -
Fixed Alignment Issue of Project Title in mobile View
### Screenshots of the changes (If any) -
Before : 
RvsyS6O - Imgur
After:
D12IVgz - Imgur

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Sj1218305** [comment]
@nitin10s @aayush-05 please review it

**Comment by aayush-05** [comment]
We are most probably disabling simulator on mobile displays, so I don't know if this is necessary.

**Comment by aayush-05** [comment]
Similar to #1035

**Comment by nitin10s** [comment]
Being revamped as a part of GSoC'20

**Pull request closed without merging**
