### PR TITLE
feat: fixed notification text overlapping

### LINKED ISSUE #3333: Overlapping Notification and unread notification green circle
**Describe the bug**
Overlapping Notification and unread notification green circle

**To Reproduce**
1. Go to 'Notifications modal'

**Expected behavior**
The text should not overlap with the unread notification circle.

**Screenshots**
Screenshot 2022-11-01 at 5 51 39 PM

**Device Information [optional]:**
 - Browser [e.g. chrome, safari] : All web browsers ... css issue

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
Fixes #3333 

#### Describe the changes you have made in this PR -
Minor changes in CSS 

### Screenshots of the changes (If any) -
Before fix

Fixed screen
Screenshot 2022-11-01 at 5 54 21 PM

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
cc @nitin10s

**Comment by vedant-jain03** [comment]
Screenshot from 2022-11-07 10-43-12

I tested it with the long name!

**Comment by VaibhavUpreti** [comment]
> Screenshot from 2022-11-07 10-43-12
> 
> I tested it with the long name!
> 
> I am thinking of adding the unseen span at the beginning of the message It will look something like this: Screenshot from 2022-11-07 10-51-30
> 
> WDYT @VaibhavUpreti @tachyons @nitin10s

I think it looks great 👍. This new approach looks good, I like it.

**Comment by vedant-jain03** [comment]
@VaibhavUpreti Could you add the suggested UI in #UX in the slack channel?

**Comment by VaibhavUpreti** [comment]
Screenshot 2022-11-15 at 1 47 47 AM
@vedant-jain03 made final changes after suggestions, kindly approve.

**Comment by VaibhavUpreti** [comment]
@nitin10s pls review

**Comment by vedant-jain03** [comment]
@VaibhavUpreti I have added a commit, try it out!

**Comment by VaibhavUpreti** [comment]
> @VaibhavUpreti I have added a commit, try it out!
Screenshot 2022-11-16 at 11 54 10 PM
This solves our problem 👍

**Comment by vedant-jain03** [comment]
@VaibhavUpreti Could you please work on checks, this PR is ready to merge then!

**Comment by VaibhavUpreti** [comment]
@vedant-jain03 had to write some extra CSS as the notification modal and page were inconsistent ... here is the view after fix.
Screenshot 2022-11-17 at 7 26 21 PM

Screenshot 2022-11-17 at 7 27 10 PM

**Pull request merged**
