### PR TITLE
added SVG logos

### LINKED ISSUE #125: CircuitVerse Favicon Logo
We have a decent CircuitVerse logo but we do not have a good square logo which can be used as favicon or for places we need a shorter form of the logo. 

Not sure what is needed. I am thinking similar to the current Favicon logo would do.

### PR DESCRIPTION
**Pull request by pradnyasd**
Fixes #125

#### Describe the changes you have made in this pr -
I have created SVG logos and added it in app/assets/images/SVGs.

### CODE REVIEW

**Comment by fpintos** [comment]
Out of curiosity, where are these icons referenced?

**Comment by pradnyasd** [comment]
> Out of curiosity, where are these icons referenced?

Not particular but surfed many sites and referred many logos to finally build these ones.

**Comment by armudgal** [comment]
Approved from my side.
@satu0king, @tachyons, @Parikshit-Hooda If you guys give a go ahead then we can go forward with merging it and using it.

**Comment by Parikshit-Hooda** [comment]
Green light from my end.

**Comment by fpintos** [comment]
> > Out of curiosity, where are these icons referenced?
> 
> Not particular but surfed many sites and referred many logos to finally build these ones.

I'm asking where are we going to use them. :-)

**Comment by Parikshit-Hooda** [comment]
@fpintos  the icons would be used as favicon.

**Comment by pradnyasd** [comment]
> > > Out of curiosity, where are these icons referenced?
> > 
> > 
> > Not particular but surfed many sites and referred many logos to finally build these ones.
> 
> I'm asking where are we going to use them. :-)

Ohh! I am sorry, these are the Favicons.

**Comment by pradnyasd** [comment]
@fpintos Thankyou for merging the pull request :-)
@armudgal @Parikshit-Hooda @tachyons @satu0king  : It was really a very good experience working on this issues. Got to learn many new things.  :-)

**Pull request merged**
