### PR TITLE
-a quick search bar

### PR DESCRIPTION
**Pull request by abstrekt**
Fixes #

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by abstrekt** [comment]
> 
> 
> Add a search icon in the placeholder, add border-radius in :focus select aswell.

I tried using unicode, placeholder text isn't supporting it, & :focus select of?

**Comment by nitin10s** [comment]
image
This is what I meant (see the rectangular focus on selected)

Maybe try fontawesome? Unicode might not work due to the font-family. Also, I read this weird workaround, might work for us:
image

**Comment by abstrekt** [comment]
> 
> 
> image
> This is what I meant (see the rectangular focus on selected)
> 
> Maybe try fontawesome? Unicode might not work due to the font-family. Also, I read this weird workaround, might work for us:
> image

I see this is a div, but placeholder is an attribute of the input in the html

**Comment by abstrekt** [comment]
image

**Comment by nitin10s** [comment]
Na, doesn't look good at all

**Comment by abstrekt** [comment]
yes,  ik i haven't really commited this

**Comment by abstrekt** [comment]
This feature is already included in #1585, closing it

**Pull request closed without merging**
