### PR TITLE
Added func. to trigger capsAlert & modified related pages

### LINKED ISSUE #1946: Improving password input fields
**Is your feature request related to a problem? Please describe.**
Currently password input field in Signup and Log-in form, only supports for the toggling option to look for the input. It would be better if we put capslock alert functionality, to alert for 'capsLock ON ' while inputting the password without having to toggle and look for whether the caps is on or not.

**Additional context**
Current workings:
Issue1final

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by AkashChetia**
Fixes #1946 

#### Describe the changes you have made in this PR -
Added function to trigger caps-Lock on state on key-press and modified its related Dom pages to act on the 
function logic. 

### Before:
Issue1final

### After:
Resolve1

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by satu0king** [comment]
Not sure if this is needed ... @Shivansh2407 @aayush-05

**Comment by aayush-05** [comment]
I personally don't find it useful/essential. This might be useful if we have a field which allow only smallcase characters. But since passwords can even be all caps; this feels like unnecessary screaming.

**Comment by Shivansh2407** [comment]
I also don't consider this feature to be too useful. The reason is because we currently have Toggle Password Visibility Feature that allows us to view the password onclick. So if the user is in confusion, whether they typed in Caps On or Off, they may check it using that.

**Comment by AkashChetia** [comment]
@satu0king @aayush-05 @Shivansh2407  true! ....will try to contribute fruitful things. Sorry for this.

**Comment by aayush-05** [comment]
> @satu0king @aayush-05 @Shivansh2407 true! ....will try to contribute fruitful things. Sorry for this.

It's all good. Every contribution is equally valuable; just that every feature additiion isn't essential to the user. Try picking up something from the already opened issues.

**Pull request closed without merging**
