### PR TITLE
feat(palystore): playstore for circuitverse

### LINKED ISSUE #4088: Feature :playstore link in footer
### Is your feature request related to a problem? Please describe

playstore link in footer  would help user so thay came to know that they can use circuitverse also as app

### Describe the solution you'd like

playstore  link in footer
Screenshot (292)

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Are you working on this?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #4088 

#### Describe the changes you have made in this PR -
playstore link to circuitevrse is added to footer

### Screenshots of the changes (If any) -
Screenshot (294)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @tachyons plaese check

**Comment by vedant-jain03** [comment]
@harshsharma-11 kindly fix the conflicts

**Comment by harshsharma-11** [comment]
@vedant-jain03 please check the pr

**Review by VaibhavUpreti — CHANGES_REQUESTED** [review]
brok

CSS is broken, for the top layer as well.

**Pull request closed without merging**
