### PR TITLE
Changed CSS for dropdown menus in properties

### LINKED ISSUE #1403: [UX] Change color for dropdown text in Properties in simulator interface
**Describe the bug**
The dropdown text for Label Direction and Direction in simulator interface is black hence it's not clearly visible.

**To Reproduce**
1. Go to [simulator](https://circuitverse.org/simulator)
2. Add any element in the simulator.
3. The properties for the element would be visible in the left sidebar.
4. The text for Label Direction and Direction would not be clearly visible.

**Screenshots**

image

**Additional context**
The text color could be changed to white

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by KaustubhDamania**
Fixes #1403 

#### Describe the changes you have made in this PR -
Changed CSS for objectPropertyAttribute class

### Screenshots of the changes (If any) -

**Before:**

image

**After:**

image

### CODE REVIEW

**Comment by KaustubhDamania** [comment]
@nitin10s can you review this please?

**Comment by KaustubhDamania** [comment]
@nitin10s I would also like to increase padding for the CircuitVerse Help button since it is quite close to the above fields, please let me know if I should make changes in this PR or create a new PR for the same?

**Comment by nitin10s** [comment]
Separate PR

**Comment by nitin10s** [comment]
We will be revamping the design so closing this.

**Comment by KaustubhDamania** [comment]
@nitin10s I had made this PR almost a month ago, is there any reason why this wasn't merged then since it was just a minor change? 

> @satu0king please merge.

Cause you had previously approved my change.

**Pull request closed without merging**
