### PR TITLE
Examples Page 

### PR DESCRIPTION
**Pull request by harshgujrati**
Fixes #

### Screenshots of the changes (If any) -

Screenshot (112)
Screenshot (114)
Screenshot (115)
Screenshot

### CODE REVIEW

**Comment by aayush-05** [comment]
Hey!
Please don't add any custom styling to bootstrap predefined classes, add your own custom additional classes with appropraite names and then add styling to them. Also, see the new about page, you will be able to use much of styles from there and it would help in maintaining the uniformity among pages.

**Comment by harshgujrati** [comment]
Okay @nitin10s  @aayush-05 i will make the required change.

**Comment by nitin10s** [comment]
What do the top users' section display?

**Comment by harshgujrati** [comment]
@nitin10s  At present the top users button is not linked to any page.

**Comment by aayush-05** [comment]
Hey @harshgujrati 
I can see a lot of unrelated changes in this pr, please remove them and try working on separate branches for each pr you make. Also can you write more descriptive commit messages, it helps while reviewing.

**Comment by nitin10s** [comment]
@harshgujrati Please ensure that all checks are successful.

**Comment by aayush-05** [comment]
Remove the Gemfile.lock from this pr, don't remove the existing styles from the stylesheet (just add your own under New UI) and use 2 space indentation everywhere.
Please first pull from the master and then push these changes back

**Comment by aayush-05** [comment]
-Remove unrelated files
-Fix the conflicting files
-Set a max-width property to the grid-cell
@harshgujrati please make these changes

**Comment by harshgujrati** [comment]
@tachyons please review it

**Comment by Ananthavijay** [comment]
I think there should be only 2 indentations in .scss files

**Comment by aayush-05** [comment]
-Fix conflicting files
-Use 2 space indentation
-Don't remove any code from the stylesheets, add your own in other custom classes
Also, please remove a lot of unrelated changes, it would easier to review it then @harshgujrati

**Comment by nitin10s** [comment]
Can you please open a new PR for this?

**Comment by aayush-05** [comment]
Please close this one @tachyons @harshgujrati

**Pull request closed without merging**
