### PR TITLE
fix(EditButton): alignment,fixed alignment of edit button in Dashboad

### PR DESCRIPTION
**Pull request by YashGupt29**
issue#4105
Screenshot from 2023-10-07 10-13-22

Description:

Summary:

I have fixed the alignment issue of the "Edit" button in the user dashboard by adjusting its margin from 5px to 0px. This change ensures that the "Edit" button is properly aligned with the surrounding elements.

Changes Made:

Changed the margin of the "Edit" button from 5px to 0px in the user dashboard CSS.

Fixes #
Screenshot from 2023-10-07 10-26-35

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Review by niladrix719 — APPROVED** [review]

**Comment by niladrix719** [comment]
issue no. should be #4105

**Comment by YashGupt29** [comment]
edited the issue number thank you

**Comment by YashGupt29** [comment]
@vedant-jain03  
please review

**Review by tanmoysrt — APPROVED** [review]

**Comment by tanmoysrt** [comment]
cc @vedant-jain03

**Review by vedant-jain03 — APPROVED** [review]

**Comment by tanmoysrt** [comment]
@vedant-jain03 as per the hacktoberfest event rule, I guess we need to add `hacktoberfest-accepted` label also to the PRs

**Pull request merged**
