### PR TITLE
Adds generic Back button to _form partials with dynamic redirect_url

### LINKED ISSUE #1362: Back button redirect_url is not dynamic
**Describe the bug**
Back button at places shows unexpected behaviour because back button's redirect_url is not dynamic.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Click on My Favourites.
3. Go to project show page
4. Click on back and see error.

**Expected behavior**
Back button should redirect to the previous page.

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Nitish145**
Fixes #1362 

#### Describe the changes you have made in this PR -
- Used `:back` as redirect_url to each Back button.

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by Nitish145** [comment]
@nitin10s please check !!

**Comment by aayush-05** [comment]
Looks good to be merged @tachyons

**Comment by nitin10s** [comment]
@aayush-05

**Comment by aayush-05** [comment]
Collaboration files have been removed; since they were exposing dB endpoints. @Nitish145 maybe you can fix the merge conflicts and then we can merge

**Comment by Nitish145** [comment]
Sure!! Will give it a try.. @aayush-05

**Comment by aayush-05** [comment]
@Nitish145 working on this?

**Comment by Nitish145** [comment]
Will give this a try once the new UI is in place, whatsay? @aayush-05

**Comment by satu0king** [comment]
@Nitish145 can we revisit this now?

**Comment by Nitish145** [comment]
@satu0king will do

**Comment by Nitish145** [comment]
@satu0king rebased the branch & got to know, the dynamic *back* feature was already in place with the new UI, on pushing after rebasing the PR was automatically closed since no changes were left..

**Pull request closed without merging**
