### PR TITLE
New UI Homepage

### PR DESCRIPTION
**Pull request by harshgujrati**
Fixes #

#### Describe the changes you have made in this pr -In this PR i have redesigned the Homepage according to new design and have made it responsive.
Screenshot (125)
Screenshot (126)
Screenshot (127)
Screenshot (128)
Screenshot (129)
Screenshot (130)
Screenshot (131)

### CODE REVIEW

**Comment by aayush-05** [comment]
I guess your have merged the code for Examples page in this pr

**Comment by harshgujrati** [comment]
Okay @aayush-05 i will make the recquired correction.

**Comment by tachyons** [comment]
Remove unrelated commits from the PR

**Comment by aayush-05** [comment]
Dropping a new pr for Homepage, this one is too hard to review and manage.

**Comment by nitin10s** [comment]
@tachyons Please close this.

**Pull request closed without merging**
