### PR TITLE
removing reduntant files + some fixes

### PR DESCRIPTION
**Pull request by abstrekt**
### Describe the changes you have made in this PR -
* Removed files that were no longer in use.
* Small fix to custom radios.
* reduced 1 color variable.
* Changes circuit del icon from ```x``` to trash.

image

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by abstrekt** [comment]
@nitin10s @satu0king please review

**Comment by satu0king** [comment]
@abstrekt why are these files no longer in use? is it because we have added them inline in the html?

**Comment by abstrekt** [comment]
> 
> 
> @abstrekt why are these files no longer in use? is it because we have added them inline in the html?

yes the svgs were added inline as to support color themes,

**Comment by satu0king** [comment]
@abstrekt we should try and find a way to not include this inline and support color themes.

**Comment by abstrekt** [comment]
> @abstrekt we should try and find a way to not include this inline and support color themes. Lets keep the files for now, incase we find a way to do so in the future.

okay sure, I'll rebase, there's one plugin that is no longer being used, that surely needs remove.

**Comment by satu0king** [comment]
@abstrekt can u fix this PR?

**Comment by tachyons** [comment]
@abstrekt Is this PR still relevant?

**Pull request closed without merging**
