### PR TITLE
Resolve stretched images in example page and optimize images

### LINKED ISSUE #1336: Stretched images in example page
**Is your feature request related to a problem? Please describe.**
Images on example page are stretched
**Describe the solution you'd like**
Edit the image such that it looks normal and changing the background of all image to white to maintain uniformity

**Additional context**

**Are you working on this? (Yes/No)**
  Yes

### PR DESCRIPTION
**Pull request by harshgujrati**
Fixes #1336

### Screenshots of the changes (If any) -
Screenshot (231)
Screenshot (232)

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aayush-05** [comment]
We cannot rely on explicitly providing images for each example in the future. Let us just get these circuits from the database itself rather than hardcoding. @harshgujrati

**Comment by nitin10s** [comment]
The Examples were hard coded actually.

**Comment by harshgujrati** [comment]
Ok @aayush-05 i will update it and will take image from database

**Comment by aayush-05** [comment]
Exactly, can't we just get the project ids and loop over them. Maybe we can hardcode them in the dev environment because those same circuits won't be present in the user's local database.

**Pull request closed without merging**
