### PR TITLE
reduce top-margin space at phone screens

### LINKED ISSUE #1146: extra white space at top of homePage
**Describe the bug**
extra white space existed at phone screens 

**Screenshots**
home b

**Expected behavior**
It would be better if we reduced that margin top to be like this : 
home

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by mahmodHammad**
Fixes #1146 

### Screenshots of the changes
image

### CODE REVIEW

**Comment by aayush-05** [comment]
Don't change it for every screen size, use media queries.

**Comment by mahmodHammad** [comment]
> Don't change it for every screen size, use media queries.
@tachyons 
Could you please review the changes

**Comment by mahmodHammad** [comment]
@nitin10s 
i used media query for making this changes on Phone screens only

**Comment by mahmodHammad** [comment]
i will check it again

**Comment by mahmodHammad** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1147/#issuecomment-599006671
https://github.com/CircuitVerse/CircuitVerse/pull/1147/#pullrequestreview-376255574
@nitin10s  
i think it's better now , Please Check it again !

tobmargin

**Pull request merged**
