### PR TITLE
Added Hover effect for "Simulator" icon

### PR DESCRIPTION
**Pull request by Vishruth-S**
Fixes #
Added hover effect 
#### Describe the changes you have made in this PR -
All other nav items have hover effect. The simulator icon also needs a nice hover effect as it is the most significant item.
Added hover effect as shown below

###Before 
cv1

###After 
cv2

### CODE REVIEW

**Comment by satu0king** [comment]
@nitin10s @aayush-05 approve either this or #1109 and we can merge.

**Comment by aayush-05** [comment]
This looks good to me, @Vishruth-S can you use sass pseudo selectors ?

**Comment by Vishruth-S** [comment]
@aayush-05 Replaced with Sass pseudo selectors as requested. kindly review

**Comment by nitin10s** [comment]
Can you add a transition like #1105

**Comment by Vishruth-S** [comment]
@nitin10s Done as requested. Kindly confirm if working as expected

**Comment by nitin10s** [comment]
I was asking for hover effects like in the other PR, this one makes the opacity 0 on hover. Pls see and fix @tachyons don't merge please.

**Comment by Vishruth-S** [comment]
@nitin10s I am sorry i didn't understand what u meant..

This is the working of the changes i made
bandicam-2020-03-23-09-09-30-831


Could you please specify what exactly to be modified here

**Comment by Vishruth-S** [comment]
@nitin10s Made changes as requested, kindly review

**Comment by aayush-05** [comment]
Can you update the description with new screenshots/video ?

**Comment by aayush-05** [comment]
@nitin10s shall we close this one, I am planning to implement it myself; since this fix was having inconsistencies ?

**Comment by aayush-05** [comment]
@tachyons can be closed; fixed here >> #1451

**Pull request closed without merging**
