### PR TITLE
Fixes new group page issues

### LINKED ISSUE #1123: Alignment and Position of New Group Page buttons
**Describe the bug**
In Mobile view the _Save_ and _Back_ button are neither aligned nor positioned properly.

**To Reproduce**
1. Go to circuitverse.org
2. Click on *My Groups*
3. Click on *Make New Group*

**Screenshots**
Screenshot from 2020-03-10 21-40-41

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Nitish145**
Fixes #1123 

#### Describe the changes you have made in this PR -
- Added responsiveness in new group page.
- Moved back button to form partial.
- Removed irrelevant css classes.

## BEFORE
Screenshot from 2020-03-13 21-08-39
Screenshot from 2020-03-13 21-23-32
Screenshot from 2020-03-13 21-09-12

## AFTER
Screenshot from 2020-03-13 21-13-51
Screenshot from 2020-03-13 21-14-01
Screenshot from 2020-03-13 21-29-02

### CODE REVIEW

**Comment by Nitish145** [comment]
@nitin10s @aayush-05 reviews please :)

**Comment by tachyons** [comment]
Fix conflicts

**Comment by Nitish145** [comment]
@tachyons done !!

**Comment by Ananthavijay** [comment]
@Nitish145 Please check the new group page

**Comment by Nitish145** [comment]
@Ananthavijay will open a PR for the same 🙂

**Comment by Nitish145** [comment]
@Ananthavijay i think *Back* button makes more sense on left only..

**Comment by Ananthavijay** [comment]
In every other page, the back button is on the right

**Comment by nitin10s** [comment]
Yep, right

**Pull request merged**
