### PR TITLE
Added the LinkedIn icon in the footer and configured the routes for the LinkedIn page.

### LINKED ISSUE #1659: Add LinkedIn Icon in Footer
Add LinkedIn icon similar to Facebook and Twitter icon in the Footer.
image

**Are you working on this? (Yes/No)**
No

### PR DESCRIPTION
**Pull request by hdck007**
Fixes #1659 

#### Describe the changes you have made in this PR -
1. Added a LinkedIn logo image in the footer 
2. Created a new route in the routes.rb for the CircuitVerse LinkedIn page.
3. Added the LinkedIn logo image file
## Before
Screenshot_20200920-161725

## After
Screenshot_20200920-161634

#### When clicked on the LinkedIn Icon it takes the user to the CircuitVerse LinkedIn Page

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by aayush-05** [comment]
Please add screenshots @hdck007

**Comment by hdck007** [comment]
I have added the before and after Screenshots, indicating the changes in the footer.

**Comment by hdck007** [comment]
@aayush-05 I have added the before and after Screenshots, indicating the changes in the footer.

**Comment by hdck007** [comment]
@aayush-05  The ScreenShots uploaded previously were big in size so uploaded small Screenshots now.

**Review by aayush-05 — APPROVED** [review]
LGTM

**Pull request merged**
