### PR TITLE
fix: the size of sponsor logo in footer

### LINKED ISSUE #4398: 🐞 Bug: The size of Zense logo in footer is uneven
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In footer section in main page in circuitverse Zense logo is uneven when we change the width .like sometime it is too big

### Steps To Reproduce

1. https://circuitverse.org/
2. scroll down for footer section
3. change the width

### Expected Behavior

It should not too big when we change the width

### Screenshots

image

image

### Device Information [optional]

```markdown
- OS:Windows
- Browser:Chrome
- version:
```

### Additional context

You can check may this is from my side

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by upsaurav12**
Fixes #4398 

#### Describe the changes you have made in this PR -
I tried to put the sponsor logo in the first line line but the problem was that the footer-links where in display : inline due to this i was unable to change the width of the footer-links. So now i made some breakpoints to set width and it will not be that big 

### Screenshots of the changes (If any) -
Previously it was:-
image

Now it is:-
image

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tanmoysrt** [comment]
Hi @upsaurav12 update the issue link in PR description.

**Comment by tanmoysrt** [comment]
Hi @upsaurav12 remove the commits or changes of cv-frontend-vue from this PR.
It's a seperate submodule.

**Comment by upsaurav12** [comment]
yes it was automatically added in dont know how

**Comment by tanmoysrt** [comment]
> yes it was automatically added in dont know how

If you can't remove, you can open up a new PR and close this

**Comment by upsaurav12** [comment]
opening a new pr

**Pull request closed without merging**
