### PR TITLE
Added Tooltip Text to All Elements 

### LINKED ISSUE #486: Add alert for all options
**Is your feature request related to a problem? Please describe.**
Alert pops up when any element in the input or output option in simulator is hovered but this does not happen in the rest of the options. Those alerts should also be added to maintain symmetry.

**Describe the solution you'd like**
Alert should be added when hovered over options other than input and output.

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #486 

#### Describe the changes you have made in this pr -
I have added a Tooltip text (alert) to all the elements present in the modules.js File. I have added it to Testbench and Sequential files too.

### Screenshots of the changes (If any) -
patch-19

### CODE REVIEW

**Comment by Shivansh2407** [comment]
@ankitkataria and @sakshi1499 I am facing a problem while extending the tooltip to testbench.js and sequential.js . As soon as I add the tooltip there, it does not shows up on reloading ?
Please let me know how to proceed with this ?

**Comment by Shivansh2407** [comment]
Added for all the elements. 👍 Please review and merge

**Comment by nitin10s** [comment]
@tachyons take a look at this.

**Comment by Shivansh2407** [comment]
@tachyons Please review.

**Comment by Shivansh2407** [comment]
Thank You @tachyons Sir 👍

**Pull request merged**
