### PR TITLE
Help link

### PR DESCRIPTION
**Pull request by shubhankarsharma00**
Fixes #1392 
Duplicate #1458 just redirected to a new branch
@satu0king there was no conflict so I moved the same pr.

### CODE REVIEW

**Comment by satu0king** [comment]
@shubhankarsharma00 , the new UI uses code in `public/src`. Also add this as a custom shortcut please. Thanks!

**Comment by shubhankarsharma00** [comment]
👀 I knew I was forgetting something. On it.

**Comment by shubhankarsharma00** [comment]
@satu0king this is done and working fine.

**Comment by satu0king** [comment]
Merged via #1743

**Pull request closed without merging**
