### PR TITLE
fix(my-circuits):  typo fixed

### LINKED ISSUE #3979: [typo]:"my circuits" instead of "circuits"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when you open someone's profile you can see their "My Circuits" section in his profile how???

### Steps To Reproduce

1.search any user in search option of navbar
2.open the user's profile 
3.you able to see "My Circuits" instead of just "circuits"

### Expected Behavior

instead of "MY CIRCUITS" it should be "CIRCUITS"

### Screenshots

Screenshot (243)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #3979 

#### Describe the changes you have made in this PR -
typo fixed "MY CIRCUITS" to "CIRCUITS"
Screenshot (244)

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
cc @vedant-jain03 @VaibhavUpreti

**Comment by harshsharma-11** [comment]
please review the pr
@tachyons

**Comment by VaibhavUpreti** [comment]
Imo, 'My Circuits' is more fitting, other two fields, 'Collaborated' and 'Fav,' also contain circuits. Simply naming it 'Circuits' removes this context.

**Comment by tachyons** [comment]
Another way could be "Created circuits" or "Owned circuits". "circuits" alone misses the context as @VaibhavUpreti pointed out

**Comment by harshsharma-11** [comment]
> Another way could be "Created circuits" or "Owned circuits". "circuits" alone misses the context as @VaibhavUpreti pointed out

so  @tachyons should i work on it and  change it to "Created circuits"

**Comment by VaibhavUpreti** [comment]
Try "Authored Circuits" or maybe you can remove the redundancy by doing something extra, we have `circuits` word in each. We can have a banner text with `Circuit Gallery` right below the user details card and then these 3
1. Authored
2. Favourites
3. Collaborations

**Comment by harshsharma-11** [comment]
> Member

@VaibhavUpreti as my previous workspace in gitpod get deleted so i cannot make changes in previous branch so can i push a new pr for this

**Comment by Arnabdaz** [comment]
> > Member
> 
> @VaibhavUpreti as my previous workspace in gitpod get deleted so i cannot make changes in previous branch so can i push a new pr for this

you can always pull this branch in your new gitpod instance & make the changes, you just need to add your froked repo as a remote in that instance

**Comment by harshsharma-11** [comment]
> > > Member
> > 
> > 
> > @VaibhavUpreti as my previous workspace in gitpod get deleted so i cannot make changes in previous branch so can i push a new pr for this
> 
> you can always pull this branch in your new gitpod instance & make the changes, you just need to add your froked repo as a remote in that instance

okk

**Comment by harshsharma-11** [comment]
@tachyons @VaibhavUpreti done as suggested please review the changes

**Comment by harshsharma-11** [comment]
@tachyons done as suggested please review the changes

**Comment by harshsharma-11** [comment]
@tachyons @Arnabdaz  done as suggested please review the changes

**Comment by Arnabdaz** [comment]
> @tachyons @Arnabdaz done as suggested please review the changes

1. As VaibhavUpreti said add banner text with `Circuit Gallery` right below the user details card 
2. update the screenshot in pr description

**Comment by Arnabdaz** [comment]
> @tachyons @Arnabdaz done as suggested please review the changes

1. As VaibhavUpreti said add banner text with `Circuit Gallery` right below the user details card 
2. update the screenshot in pr description

**Comment by harshsharma-11** [comment]
> > @tachyons @Arnabdaz done as suggested please review the changes
> 
> 1. As VaibhavUpreti said add banner text with `Circuit Gallery` right below the user details card
> 2. update the screenshot in pr description

i don't able to recodnise properly.If i am not wrong @VaibhavUpreti you want that there will be banner with heading circuit gallery and and below it circuit name as you intially suggested

**Comment by harshsharma-11** [comment]
sir gitpod k browser m koi changes show ni hore

**Comment by harshsharma-11** [comment]
@VaibhavUpreti please can you clarify how you want it to be

**Pull request closed without merging**
