### PR TITLE
Issue#2712-Centering social icons in footer- Resolved, style

### LINKED ISSUE #2712: Centering the social icons in the footer
**Describe the bug**
Misalignment of icons: There is a non-uniform margin and padding on the icons.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to 'footer'
4. See the icons

**Screenshots**

Before: 
original
After: 
edited

**Are you working on this issue? (Yes/No)**
 Yes, I will create a PR if the issue is appproved.

### PR DESCRIPTION
**Pull request by PrakritiShetty**
Fixes #2712

#### Changes I have made in this PR -
1. Checked the centering and padding of individual social icons
2. Made the LinkedIn logo square
3. Removed the background of the twitter logo and re-uploaded.

### Screenshots of the changes 

Before :

before

After:

after

### CODE REVIEW

**Comment by PrakritiShetty** [comment]
@gr455 Please review this when you have time, thanks!

**Review by gr455 — CHANGES_REQUESTED** [review]
Hi @PrakritiShetty. Seems like you have changed the social icons, the actual issue was that the icons were not centered inside the anchor tag.

**Comment by PrakritiShetty** [comment]
Great, thanks @gr455. I thought I had done the centering as well, turns out I hadn't saved that..

I'm adding screenshots of before/after below:
Before-
image
image


After-
image
image
image

**Comment by VaibhavUpreti** [comment]
Closing this PR due to inactivity. Feel free to reopen if needed.

**Pull request closed without merging**
