### PR TITLE
Select all Elements

### PR DESCRIPTION
**Pull request by NavonilDas**
Select all Element by CTRL+A #301 

#### Demo
selectall

### CODE REVIEW

**Comment by Amansingla97** [comment]
Looks gr8

**Comment by satu0king** [comment]
What software do you use to make this gif?

**Comment by ankitkataria** [comment]
There are several chrome extensions that do this, [Chrome Capture](https://chrome.google.com/webstore/detail/chrome-capture/ggaabchcecdbomdcnbahdfddfikjmphe?hl=en) is one of them.

**Comment by NavonilDas** [comment]
@satu0king I Just use a screen recorder and then convert that video to Gif using [ezgif.com](https://ezgif.com/video-to-gif).

Chrome extensions doesn't provide to see mouse click or to show pushed keys.

**Comment by satu0king** [comment]
Thanks

**Pull request merged**
