### PR TITLE
Close Cross for Circuit Tabs

### PR DESCRIPTION
**Pull request by krishanu-2001**
This introduces a close cross for circuit tabs in simulator/tabsbar

Fixes: #1267 

#### Describe the changes you have made in this PR -
Introduced a cross icon to close the circuits in front of the circuit name in tabsbar - aim: to improve UI

### Screenshots of the changes (If any) -
fix1

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by krishanu-2001** [comment]
yes, that, it does already. thanks for reviewing
fix2

**Comment by krishanu-2001** [comment]
if there's any problem, I'll be happy to work on it.

**Comment by nitin10s** [comment]
or it's best the main circuit doesn't have a close button actually.

**Comment by krishanu-2001** [comment]
sure!

**Comment by satu0king** [comment]
Please check guidelines on how to raise a PR, reference issue number in PR, title PR appropriately. Thank You

**Comment by satu0king** [comment]
> The alert text should be instead: You can't delete the main circuit.

No circuit is actually main, its just that the first circuit is named as main. Any circuit can be deleted

**Comment by krishanu-2001** [comment]
so, is it required to change it?

**Comment by krishanu-2001** [comment]
> please check guidelines on how to raise a PR, reference issue number in PR, title PR appropriately. Thank You
made necessary changes, thank you!

**Comment by satu0king** [comment]
Good job, I like PRs which add functionality with minimal change :)

**Pull request merged**
