### PR TITLE
Adding Environment Variables 

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes https://github.com/CircuitVerse/CircuitVerse/issues/538
[GCI TASK](https://codein.withgoogle.com/dashboard/task-instances/4543682456322048)

#### Describe the changes you have made in this pr -
- Added an example .env file so that user can configure it and can add environment variables both in local environment and gitpod.

#### Working:
CircuitVerse_CircuitVerse - master

### CODE REVIEW

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209  Have a look

**Comment by ShreyaPrasad1209** [comment]
I guess this is cool! do add the Screenshots for everything as well.

**Comment by Ananthavijay** [comment]
Done @ShreyaPrasad1209 !

**Comment by tachyons** [comment]
Awesome

**Pull request merged**
