### PR TITLE
Added Scrolling when large members are there groups and fixed remove button overflow

### LINKED ISSUE #1185: Remove button on teacher's page for Members isn't completely visible.
**Describe the bug**
Remove button on teacher's page for Members isn't completely visible.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Teachers', then click to view your Groups.
3. See error

**Expected behavior**
Button completely visible as in other window sizes.

**Screenshots**
Screenshot from 2020-03-15 08-57-48
Screenshot from 2020-03-15 08-57-11
Screenshot from 2020-03-15 08-58-42

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Chrome

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by darkshredder**
Fixes #1185 

#### Describe the changes you have made in this PR -
Added Scrolling when large members are there groups and fixed remove button overflow
### Screenshots of the changes (If any) -
ezgif com-video-to-gif (19)

### CODE REVIEW

**Comment by Nitish145** [comment]
Scrolling looks fine but remove button should be inline with the name, Email should be in next line..

Use flex properties to achieve the same
@darkshredder

**Comment by darkshredder** [comment]
@Nitish145 flex property will still have issues with remove button for long names thats why i have used word-wrap. @nitin10s should i use word wrap or overflow: ellipsis?

**Comment by yash15601** [comment]
Word wrap will break the sentence  and overflow :ellipsis will maintain the size of  assignment  using overflow will be helpful @darkshredder

**Comment by darkshredder** [comment]
@nitin10s @tachyons please review

**Pull request merged**
