### PR TITLE
add readonly attribute to group invite textarea

### PR DESCRIPTION
**Pull request by csaa2019**
Fixes #

#### I added a readonly="readonly" attribute to the group invite textarea. To test this, login and go to My Groups -> Create Group -> Add members -> Group Invite Link. 

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by gr455** [comment]
@csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them

**Comment by csaa2019** [comment]
> @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them

Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?

**Comment by gr455** [comment]
> > @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them
> 
> Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?

Can you tell me how you pushed this one?

**Comment by csaa2019** [comment]
> > > @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them
> > 
> > 
> > Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?
> 
> Can you tell me how you pushed this one?

In GitPod, I went to Source Control and then commit changes. The file I changed it labelled with an M, and everything else is labelled with an A. I think it believes that all the other files are new or something along those lines. I'm not sure how to tell it only to commit the file I changed.

**Comment by gr455** [comment]
> > > > @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them
> > > 
> > > 
> > > Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?
> > 
> > 
> > Can you tell me how you pushed this one?
> 
> In GitPod, I went to Source Control and then commit changes. The file I changed is labelled with an M, and everything else is labelled with an A. I think it believes that all the other files are new or something along those lines. I'm not sure how to tell it only to commit the file I changed.

You can move only required changes to staging (all changes listed in staging area are committed when you press commit). Refer this
https://tabris.com/git-version-control-basics-in-gitpod/#:~:text=We%20add%20a%20message%20and%20commit%20the%20staged%20files%20in%20the%20Git%20panel%20(click%20the%20plus%20icon%20to%20move%20the%20files%20from%20changes%20to%20the%20staged%20changes%20section)%3A

**Comment by csaa2019** [comment]
> > > > > @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them
> > > > 
> > > > 
> > > > Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?
> > > 
> > > 
> > > Can you tell me how you pushed this one?
> > 
> > 
> > In GitPod, I went to Source Control and then commit changes. The file I changed is labelled with an M, and everything else is labelled with an A. I think it believes that all the other files are new or something along those lines. I'm not sure how to tell it only to commit the file I changed.
> 
> You can move only required changes to staging (all changes listed in staging area are committed when you press commit). Right click on the change you want to commit and click `stage changes` to do this Refer this https://tabris.com/git-version-control-basics-in-gitpod/#:~:text=We%20add%20a%20message%20and%20commit%20the%20staged%20files%20in%20the%20Git%20panel%20(click%20the%20plus%20icon%20to%20move%20the%20files%20from%20changes%20to%20the%20staged%20changes%20section)%3A

Ok great, I think I understand. Is there any way to easily undo all the unnecessary changes I included with the pull requests? When I do undo last commit and then just commit the change I want, it won't let me push and pull these commits to the pull request branch (I get the following error: The following untracked working tree files would be overwritten by merge). If there's no easy way, I think I can just close this pull request and create a new one.

**Comment by gr455** [comment]
> > > > > > @csaa2019 You seem to have committed more files than required. Use `git add <file_path>` to add only the files you made changes to and commit them
> > > > > 
> > > > > 
> > > > > Hi, thanks for catching my mistake! Do you know how I would do this within GitPod?
> > > > 
> > > > 
> > > > Can you tell me how you pushed this one?
> > > 
> > > 
> > > In GitPod, I went to Source Control and then commit changes. The file I changed is labelled with an M, and everything else is labelled with an A. I think it believes that all the other files are new or something along those lines. I'm not sure how to tell it only to commit the file I changed.
> > 
> > 
> > You can move only required changes to staging (all changes listed in staging area are committed when you press commit). Right click on the change you want to commit and click `stage changes` to do this Refer this https://tabris.com/git-version-control-basics-in-gitpod/#:~:text=We%20add%20a%20message%20and%20commit%20the%20staged%20files%20in%20the%20Git%20panel%20(click%20the%20plus%20icon%20to%20move%20the%20files%20from%20changes%20to%20the%20staged%20changes%20section)%3A
> 
> Ok great, I think I understand. Is there any way to easily undo all the unnecessary changes I included with the pull requests? When I do undo last commit and then just commit the change I want, it won't let me push and pull these commits to the pull request branch (I get the following error: The following untracked working tree files would be overwritten by merge). If there's no easy way, I think I can just close this pull request and create a new one.

I am not sure how to do this on gitpod, but you can just create a new branch and make another PR and close this one

**Comment by csaa2019** [comment]
> I am not sure how to do this on gitpod, but you can just create a new branch and make another PR and close this one

Great, I will go ahead and do that. Thank you so much for all your help!

**Pull request closed without merging**
