### PR TITLE
fix illustration issue in login and sigup

### PR DESCRIPTION
**Pull request by rishipurwar1**
I fixed the illustration issue for the mobile view. Now, it is not shown in the mobile view.

login
signup

### CODE REVIEW

**Comment by ciphereck** [comment]
@rishipurwar1 merge conflicts are there. Can you rebase your branch?

**Comment by aayush-05** [comment]
Hide it on sm displays too @rishipurwar1

**Comment by rishipurwar1** [comment]
ok! I'll fix that.
@aayush-05 @ciphereck

**Comment by rishipurwar1** [comment]
Hello @ciphereck , merge conflict resolved now. Please review my pr.

**Comment by rishipurwar1** [comment]
Ok! I'll fix that.

**Comment by rishipurwar1** [comment]
Hello, @nitin10s  I am facing an issue. Above mentioned change, I made in the new branch. Now when I reopen that page in the browser the font size of title decreases. I don't know how this happen. Please help me with this issue.
issue

issue2

**Comment by nitin10s** [comment]
How are you changing the margins? Share the screenshot on Slack so we could understand the problem and suggest a fix.

**Comment by rishipurwar1** [comment]
After fixing the illustration issue,
I close the server and again reopen it.
After that when I go to the login page these changes are there.
I didn't make any changes for margin.

**Comment by rishipurwar1** [comment]
Is it possible to make a new pr for the same? Because I am having an issue in login&signup#1026 branch

**Comment by aayush-05** [comment]
What if we remove the descriptive text as well, I think it looks clean this way. @nitin10s 
image

**Comment by nitin10s** [comment]
I know right. but it's just that it would be better if we could incorporate the text as well. But now, I think for now we should remove the text indeed, I'll tweak the UI of these pages later to look better with the text. Let's remove it for now @rishipurwar1. You may make the change in this PR itself.

**Comment by rishipurwar1** [comment]
@nitin10s  I am having an issue with this branch.  Can I create a new pull request?

**Comment by aayush-05** [comment]
Sure @rishipurwar1

**Comment by rishipurwar1** [comment]
Thanks @aayush-05 . I am going to close this pr and open a new one.

**Pull request closed without merging**
