### PR TITLE
fix(typo-detail): typo in detail rather should be details

### LINKED ISSUE #3985: [typo]: instead of "detail" it should be "details"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in the about section there written "detail" instead of "details"

### Steps To Reproduce

1.go to about section by clicking about in navbar
2.scroll down a little and you find it

### Expected Behavior

it should be "details"

### Screenshots

Screenshot (250)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

_No response_

### Are you working on this issue?

Yes

### PR DESCRIPTION
**Pull request by harshsharma-11**
Fixes #3985

#### Describe the changes you have made in this PR -

 "detail" replaced by "details"

### Screenshots of the changes (If any) -

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by harshsharma-11** [comment]
@tachyons please review

**Comment by harshsharma-11** [comment]
@tachyons is there any issue ,if let me solve those

**Comment by harshsharma-11** [comment]
@tachyons is everything fine

**Comment by harshsharma-11** [comment]
@tachyons please kindly review the pr

**Comment by harshsharma-11** [comment]
@tachyons @vedant-jain03 @VaibhavUpreti please review the pr

**Review by VaibhavUpreti — CHANGES_REQUESTED** [review]
Nice catch Harsh! Could you also change "Checkout" to "Check out" - checkout is a noun and the correct verb is "Check out"

**Comment by harshsharma-11** [comment]
@VaibhavUpreti sure sir

**Review by VaibhavUpreti — APPROVED** [review]

**Review by vedant-jain03 — APPROVED** [review]

**Pull request merged**
