### PR TITLE
Added delete profile picture functionality

### LINKED ISSUE #2687: Add functionality to delete user profile picture
**Is your feature request related to a problem? Please describe.**
If a user has a profile picture uploaded, then there is no way to delete it (set it back to default).

**Describe the solution you'd like**
Functionality to delete user's profile picture in the edit profile form.

**Are you working on this? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by sakshi-2412**
Fixes #2687

#### Describe the changes you have made in this PR -
I have added a checkbox "Delete Picture" in the user edit profile form which if selected sets user's profile picture back to default after the form is saved.

### Screenshots of the changes (If any) -
https://user-images.githubusercontent.com/85152262/145674797-08371216-413f-4f77-8d0c-8231cdac224e.mp4

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by vedant-jain03** [comment]
I think `delete picture` should be replaced by `remove picture`.

**Comment by sakshi-2412** [comment]
> I think `delete picture` should be replaced by `remove picture`.

Okay, I'll update the changes :sparkles:

**Comment by vedant-jain03** [comment]
@sakshi-2412 can you please try to make the text vertically centered.

**Comment by sakshi-2412** [comment]
Yes sure ! 
Also, can you help me understand why some tests are failing 🤔

**Comment by sakshi-2412** [comment]
align vertically

Updated look

**Comment by vedant-jain03** [comment]
> Yes sure ! Also, can you help me understand why some tests are failing 🤔

- You can go to the details of failed test cases.
- Please resolve the CI test cases as 19 TC failed.

**Comment by sakshi-2412** [comment]
The tests were not failing till I pulled the latest changes from CircuitVerse master branch. The same tests are failing in PR  #2696 and #2698, I am not sure how to fix it :(

**Comment by vedant-jain03** [comment]
> The tests were not failing till I pulled the latest changes from CircuitVerse master branch. The same tests are failing in PR #2696 and #2698, I am not sure how to fix it :(

Okay then, let's wait for @tachyons @nitin10s response.

**Comment by tachyons** [comment]
Rebase with latest master again

**Comment by sakshi-2412** [comment]
Thanks🎉

**Review by nitin10s — APPROVED** [review]

**Pull request merged**
