### PR TITLE
[GCI] Fixed About Page Layout

### LINKED ISSUE #542: Layout problem in about page
**Describe the bug**
There is a major layout problem in the mobile view of about page of the website. The children of the div having class names row and features are taking only half of the width of the page due to which each list item is taking 2-3 lines for a single name. Due to this issue, the mobile view of the website is looking bad. 

**To Reproduce**
1. Go to 'https://circuitverse.org/about'
3. Scroll down to the heading 'Developer Team'

**Expected behavior**
The children of the div with the classes named *row* and *feature* should take the full width of the page.

**Screenshots**
Screenshot from 2019-11-06 14-11-03
Screenshot from 2019-11-06 14-18-08

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Google Chrome
 - Version 77.0.3865.120 

**Additional context**
To remove the problem just change the class name of first children div to col-12 in place of col-6 
As in this screenshot: 
Screenshot from 2019-11-06 14-19-44

**Are you working on this issue? (Yes/No)** No, this issue is for GCI students only.

### PR DESCRIPTION
**Pull request by MrBartusek**
Fixes #542

### CODE REVIEW

**Comment by aayush-05** [comment]
@tachyons @ankitkataria 
I have approved the GCI task for this. 
Please review the pr.

**Comment by tachyons** [comment]
PR to stories/new_ux branch please

**Comment by aayush-05** [comment]
@MrBartusek please do the needful.

**Comment by MrBartusek** [comment]
@tachyons @aayush-05 changed base branch to stories/new_ux

**Comment by MrBartusek** [comment]
New about page has been implemented in #823

**Pull request closed without merging**
