### PR TITLE
Fixed Overlapping of Logo in footer

### LINKED ISSUE #1019: Bottom Logo Overlapping with Text on zoom
**Describe the bug**
The links in the bottom get overlapped by the Logo image when user zooms in.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Zoom to  '150% or 175%'
3. Scroll down to 'footer'

**Expected behavior**
The Overlapping must be removed.

**Screenshots**
Issue5

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Additional context**
I will also be increasing the logo size to make it look more catchy. Let me know your views on this.

**Are you working on this issue? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Shivansh2407**
Fixes #1019 

#### Describe the changes you have made in this PR -

- [x] I have removed overlapping of the logo image in footer on the link text.

- [x] I have increased the Main Logo size a Bit .

### Screenshots of the changes (If any) -
patch23

### CODE REVIEW

**Comment by tachyons** [comment]
Can you separate screenshot/cast for before and after

**Comment by Shivansh2407** [comment]
> Can you separate screenshot/cast for before and after

Before :
Issue5
After :
patch23

@tachyons done 👍

**Comment by tachyons** [comment]
Big logo looks ugly to me

**Comment by Shivansh2407** [comment]
> Big logo looks ugly to me

Should I revert the changes ?

**Comment by tachyons** [comment]
Can we keep the same aspect ratio ?

**Comment by Shivansh2407** [comment]
Are you talking about Main Logo?

**Comment by tachyons** [comment]
CV logo in the footer

**Comment by Shivansh2407** [comment]
> CV logo in the footer

Ok will do the changes soon

**Comment by Shivansh2407** [comment]
@tachyons on keeping the aspect ratio to be same , it is overlapping some part . Could you suggest a better way ?

**Comment by aayush-05** [comment]
Try using max-width attribute and fix it to the parent container, I guess it won't overlap other content then.

**Comment by nitin10s** [comment]
@Shivansh2407 Are you working on this?

**Comment by Shivansh2407** [comment]
@nitin10s Yes I will look for a better alternative for fixing the issue and will let you know soon.

**Comment by Shivansh2407** [comment]
@nitin10s and @tachyons review this please 👍

**Comment by Shivansh2407** [comment]
@nitin10s and @tachyons Please review this . It is fixed now 👍

**Pull request merged**
