### PR TITLE
Modified-about_contoller & about_view

### LINKED ISSUE #2004: Enhance about page
Enhance about page with following details 

Mentors
Core team members 
Alumni
Contributers (as it is)

For inspiration

https://www.rust-lang.org/governance/teams/core
https://rubyonrails.org/community/

### PR DESCRIPTION
**Pull request by AkashChetia**
Fixes #2004 

#### Describe the changes you have made in this PR -
 . Modified about_controller index method for member name & images placeholder
 . Made hardcore about page for related about view.
 . Added some styles.

## Before
 
before

## After
about1
about2

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by nitin10s** [comment]
What is the reason behind changing the styles and segregating the members into different sections like the core team, mentors, etc...?

**Comment by AkashChetia** [comment]
> What is the reason behind changing the styles and segregating the members into different sections like the core team, mentors, etc...?

@nitin10s  I thought changing the styles and segregating the members would make it easy to highlight the members and their roles.

**Comment by nitin10s** [comment]
Sorry for the late reply, yeah, the idea to highlight is good but the design you've proposed looks inconsistent with the overall platform design. For now, Let's keep them styling the same way and just add different categories mentioned in the issue. We can change the styling in case someone proposes a better design aligning with the current platform design. Thank you!

**Comment by tachyons** [comment]
Thanks @AkashChetia , We are closing PR as we merged another design for this

**Pull request closed without merging**
