### PR TITLE
Finalise Assignments Page | Add Project submission description 

### PR DESCRIPTION
**Pull request by aayush-05**
**Screenshots**
1.
image
2.
image
3.
image
4.
image
5.
image
6.
image
7.
image

### CODE REVIEW

**Comment by aayush-05** [comment]
@nitin10s please have a look at this. @satu0king I have added the assignment submission additional description box here (it is the same content as project description, so no new database column required)

**Comment by aayush-05** [comment]
Done @nitin10s 
image

**Comment by nitin10s** [comment]
What does Export do? We can maybe use a better text for that button - Export Results

**Comment by aayush-05** [comment]
Fixed @nitin10s 
image

**Pull request merged**
