### PR TITLE
Added Detailed Instructions For Setting Up this project on Windows

### PR DESCRIPTION
**Pull request by souravpd**
Includes the step by step Procedure along with Links to the Software Required

''''
I am a newbie so any help and suggestions  would be highly appreciated 
Thank you

### CODE REVIEW

**Comment by vik-y** [comment]
@souravpd 
Which version of ruby does this install? `2.5.1` or `2.3.3`?

**Comment by vik-y** [comment]
@souravpd Also, please squash both your commits into a single commit and update the PR.

**Comment by souravpd** [comment]
Sir I believe it is 2.5.1
Ya I'll do it

**Comment by tachyons** [comment]
Markdown formatting seems broken

**Comment by satu0king** [comment]
> Markdown formatting seems broken

@souravpd, Yes the Markdown seems to be a bit off, can you correct it. Preview the markdown here: https://github.com/CircuitVerse/CircuitVerse/blob/8fffb5ece3c4f7939539ea39b51b9d0ccb5bd756/WINDOWS_INSTRUCTIONS.md

**Comment by souravpd** [comment]
Yaa sure I'm on it

**Pull request closed without merging**
