### PR TITLE
[GCI] Add bootstrap search dropdown

### LINKED ISSUE #480: In the dark mode the drop down button shows issues
**Is your feature request related to a problem? Please describe.**
I have dark mode plugin enabled in my latest mozilla firefox browser and the drop down button after logging in to the development environment shows blurred icon.

**Describe the solution you'd like**
The drop down icon can be switched to some other icon.

**Additional context**
Please find enclosed the screenshot.
drop down

### PR DESCRIPTION
**Pull request by junron**
Fixes #480

#### Describe the changes you have made in this pr -
The original issue referenced the old UI. The new UI does not have a search button in the navbar. 
I have created a new bootstrap based search dropdown and button for the new UI navbar that works in both light and dark mode ( tested in chrome)

###  Demo video:
Demo gif

[GCI task](https://codein.withgoogle.com/dashboard/task-instances/5815287719395328/)

### CODE REVIEW

**Comment by junron** [comment]
Please review @ShreyaPrasad1209 @tachyons

**Comment by tachyons** [comment]
@nitin10s

**Comment by ShreyaPrasad1209** [comment]
IMO it looks great! :)

**Comment by nitin10s** [comment]
The new UI doesn't need this addition. A project search bar is provided under Examples section [logically] and the user search bar wasn't really needed as discussed with Satvik. Regarding the change in old UI this looks quite nice.

**Comment by junron** [comment]
@nitin10s Maybe I'll remove the navbar one and keep the one on the search page?

**Pull request closed without merging**
