### PR TITLE
fix(esbuild): update esbuild to latest version, fixes #3573

### LINKED ISSUE #3573: Update esbuild to latest version
The latest version of esbuild changed the configuration format and that broke the [dependabot PR](https://github.com/CircuitVerse/CircuitVerse/pull/3565). This can be fixed by changing the esbuild.config.js file

### PR DESCRIPTION
**Pull request by Arnabdaz**
Fixes #3573 

#### Describe the changes you have made in this PR -
updated esbuild.config.js file to latest version which fixes the the [dependabot](https://github.com/CircuitVerse/CircuitVerse/pull/3565)

### Screenshots of the changes (If any) -
N/A

Note: Please check **Allow edits from maintainers.** if you would like us to assist in the PR.

### CODE REVIEW

**Comment by tachyons** [comment]
You need to update the esbuild version, You need to run `yarn upgrade esbuild`

**Comment by tachyons** [comment]
You need to update the esbuild version, You need to run `yarn upgrade esbuild`

**Comment by Arnabdaz** [comment]
> You need to update the esbuild version, You need to run `yarn upgrade esbuild`

wouldn't the bot update it [here](https://github.com/CircuitVerse/CircuitVerse/pull/3565)?

**Comment by tachyons** [comment]
> wouldn't the bot update it https://github.com/CircuitVerse/CircuitVerse/pull/3565?

As you can see, it failed to update it safely, That is why need to update manually

**Comment by Arnabdaz** [comment]
> > wouldn't the bot update it #3565?
> 
> As you can see, it failed to update it safely, That is why need to update manually

ok sorry I thought after the commit, we could ask the bot to retry ... 

I did it manually please check now.

**Pull request closed without merging**
