### PR TITLE
feature example card sizes

### LINKED ISSUE #532: Example Div elements' size mismatched
**Describe the bug**
The size of the elements in given Examples on the Homepage gets mismatched to each other when the browser window is resized.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Scroll down to 'Featured Examples'
3. Resize the browser window

**Expected behavior**
All the elements showcased should have equal dimensions irrespective of the Heading contents. This can be done using equal and same CSS properties for each and setting a limit to the characters of topic shown.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by abstrekt**
Fixes #532

#### Describe the changes you have made in this PR -
-
#### Screens:
* before:
image
* After 1:
Firefox_Screenshot_2020-04-06T10-50-46 141Z
* After 2:
Firefox_Screenshot_2020-04-06T10-52-07 170Z
* After 3:
Firefox_Screenshot_2020-04-06T10-52-32 108Z

### CODE REVIEW

**Comment by abstrekt** [comment]
@aayush-05 @nitin10s 
Please review changes.

**Comment by abstrekt** [comment]
Firefox_Screenshot_2020-04-06T11-00-55 890Z

**Comment by Shivansh2407** [comment]
Please let me know how to reproduce the screenshot [After 3](https://user-images.githubusercontent.com/42478217/78551132-d53d3180-7822-11ea-8f79-fd3cd180ef6f.png) situation?

**Comment by Shivansh2407** [comment]
Please let me know how to reproduce the screenshot [After 3](https://user-images.githubusercontent.com/42478217/78551132-d53d3180-7822-11ea-8f79-fd3cd180ef6f.png) situation?

**Comment by abstrekt** [comment]
> 
> 
> It is working well @abstrekt for a normal page. While when we resize the page of zoom in then the cards size remain normal for the fit titles. The longer titles push the view button down breaking the div which looks weird. Please look at the screenshot.
> Capture

Idk why it's like this in other browsers, works fine in firefox, but still I have added a hot fix for the same hoping these examples won't change.

**Comment by aayush-05** [comment]
Won't truncating text the most viable option for this @abstrekt ?

**Comment by aayush-05** [comment]
We would be redoing the feature section (requires some discussion), maybe you can close this @abstrekt

**Comment by abstrekt** [comment]
> We would be redoing the feature section (requires some discussion), maybe you can close this @abstrekt 

sure think!

**Pull request closed without merging**
