### PR TITLE
upgrade Bootstrap from v4 to v5

### LINKED ISSUE #4602: Update UI to Bootstrap 5
We are currently using Bootstrap 4. We should update it to latest bootstrap version 5.

### PR DESCRIPTION
**Pull request by salmoneatenbybear**
### **Fixes Issue**

Fixes #4602

### **Description of Changes**

This pull request upgrades the project’s Bootstrap version from v4 to v5. 

The following key changes were made as part of this upgrade:

- Updated Classes and Attributes: Replaced deprecated Bootstrap 4 classes (e.g., .jumbotron, .media, .ml-auto, .float-right) with their Bootstrap 5 equivalents or updated utility classes.
- Data Attribute Renaming: Updated data attributes such as data-toggle and data-target to the new Bootstrap 5 format.
- Bootstrap CDN Links: Replaced any Bootstrap v4 CDN links with the latest Bootstrap v5 versions.
- Utility Class Adjustments: Improved layout and spacing with Bootstrap 5’s updated utility classes.

PS: This is my first contribution to an open-source organization. I’m excited to learn how large projects like this operate and to collaborate with people from around the world—it's truly fascinating. If I’ve overlooked anything, made any mistakes, or if there are changes, big or small, that would improve this PR, please let me know. I'm fully committed to addressing any feedback and iterating on this until the issue is resolved comprehensively.

Thank you for the opportunity to contribute,
Aditya Singh

cc: @tachyons @tanmoysrt

## Release Notes

- **New Features**
  - Enhanced modal components to align with Bootstrap 5 standards, improving user interaction and interface consistency.

- **Bug Fixes**
  - Updated various button classes and attributes for modals and alerts to ensure proper functionality with the latest Bootstrap framework.

- **Documentation**
  - Revised API documentation structure for better compatibility with Bootstrap attributes.

- **Style**
  - Standardized text alignment and spacing across footer and form components for improved layout and readability.

### CODE REVIEW

**Comment by tachyons** [comment]
Add before and after screenshot of all major pages to ensure that nothing is broken

**Comment by salmoneatenbybear** [comment]
> Add before and after screenshot of all major pages to ensure that nothing is broken

the attached is a vid of the site after the changes were made...( The simulator page takes some time to load, pls stay patient ) 

https://github.com/user-attachments/assets/e522e76b-38d1-4a0e-aa6d-77efb3d20566

**Comment by tachyons** [comment]
As you can see, the home page is broken in bootstrap 5. Could you make sure that all such issues are fixed ?

**Comment by salmoneatenbybear** [comment]
Sure @tachyons will work on it, and get it fixed asap.

**Comment by salmoneatenbybear** [comment]
Hi @tachyons,

I’ve reviewed the project thoroughly post-migration and compiled a list of issues that arose during the upgrade from Bootstrap 4 to 5. The attached PDF outlines these details. I’ll be addressing each of these promptly to ensure the migration is smooth and fully compatible.

Thank you for your guidance so far, and I’ll keep you updated as I work through these fixes.

Best,
Aditya Singh
[Bugs v4 to v5 bootstrap.pdf](https://github.com/user-attachments/files/17408806/Bugs.v4.to.v5.bootstrap.pdf)

**Pull request closed without merging**
