### PR TITLE
New Assignment Page: make input fields consistent

### LINKED ISSUE #555: Unequal width and length of Input Fields
**To Reproduce**
Can be found on http://localhost:8080/groups/1/assignments/new

**Screenshots**
Issue

Also, unequal width of input fields for "Name", "Grading Scale" and "Deadline"

### PR DESCRIPTION
**Pull request by yummypasta**
#### Describe changes made in this PR
I changed the width and height of the `Name` and `Deadline` input fields in the New Assignment page to visually match the styling of the `Grading scale` input field.

### Screenshots
Screen Shot 2019-12-31 at 12 44 21 PM

### CODE REVIEW

**Comment by yummypasta** [comment]
BTW commits eb0cfd2 090acd0 89e6905 are all because I moved from committing al my changes on master to actually using feature branches. Please ignore.

**Comment by yummypasta** [comment]
Is there anything I have to do before someone can merge this PR (build a production release, etc)?

**Comment by Ananthavijay** [comment]
No need I guess

**Comment by aayush-05** [comment]
@yummypasta You have a conflicting file do check; make sure your local branch is in sync to the lastest master.
Also it would be better if you make a fresh branch off your master and create this pr. Keep a check on your previous prs as well, removing the commits might affect them. Make sure they are already merged with the master.

**Pull request closed without merging**
